// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authorization.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAuthorizations = `-- name: CountAuthorizations :one
SELECT count(*) FROM m_user_authorization
`

// m_user_authorizationの件数を取得する（日次レポート用）
func (q *Queries) CountAuthorizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthorizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserIDByAuthorization = `-- name: GetUserIDByAuthorization :one
SELECT
    m_user.public_id,
    false AS is_deactivated
FROM
    m_user
WHERE
    m_user.m_user_authorization_id = $1
UNION ALL
SELECT
    h_user.public_id,
    true AS is_deactivated
FROM
    h_user
WHERE
    h_user.m_user_authorization_id = $1
ORDER BY
    is_deactivated
LIMIT
    1
`

type GetUserIDByAuthorizationRow struct {
	PublicID      uuid.UUID
	IsDeactivated bool
}

// authorization_idから、そのユーザーのpublic_idを取得する。
// authorization_idが存在しない場合はpgx.ErrNoRowsが返される。
// 退会済みの場合はtrueが返ってくる。
func (q *Queries) GetUserIDByAuthorization(ctx context.Context, mUserAuthorizationID int64) (GetUserIDByAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, getUserIDByAuthorization, mUserAuthorizationID)
	var i GetUserIDByAuthorizationRow
	err := row.Scan(&i.PublicID, &i.IsDeactivated)
	return i, err
}

const saveAuthorization = `-- name: SaveAuthorization :one
INSERT INTO
    m_user_authorization (issuer, sub, last_logged_in_at, public_id)
VALUES
    ($1, $2, $3, $4)
ON CONFLICT (issuer, sub) DO
UPDATE
SET
    issuer = EXCLUDED.issuer,
    last_logged_in_at = EXCLUDED.last_logged_in_at,
    updated_at = current_timestamp
RETURNING
    m_user_authorization_id,
    (xmax = 0) AS is_created
`

type SaveAuthorizationParams struct {
	Issuer         string
	Sub            string
	LastLoggedInAt time.Time
	PublicID       uuid.UUID
}

type SaveAuthorizationRow struct {
	MUserAuthorizationID int64
	IsCreated            bool
}

// 認証テーブルにIssuerとSubを保存する
// IssuerとSubの組み合わせで一意制約があり、既に存在する場合は、何もしない。
// 重複した場合でも特にエラーは発生せず、既存のレコードが返される。
// 返り値は、m_user_authorization_idとpublic_id、そして新規作成されたかどうかを示すis_createdフラグ。
func (q *Queries) SaveAuthorization(ctx context.Context, arg SaveAuthorizationParams) (SaveAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, saveAuthorization,
		arg.Issuer,
		arg.Sub,
		arg.LastLoggedInAt,
		arg.PublicID,
	)
	var i SaveAuthorizationRow
	err := row.Scan(&i.MUserAuthorizationID, &i.IsCreated)
	return i, err
}
