// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cleanupExpiredJTIBlacklist = `-- name: CleanupExpiredJTIBlacklist :exec
DELETE FROM
    t_jti_blacklist
WHERE
    expires_at < $1
`

// expires_atが過ぎたjtiのブラックリストを削除します。
func (q *Queries) CleanupExpiredJTIBlacklist(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.Exec(ctx, cleanupExpiredJTIBlacklist, expiresAt)
	return err
}

const getRefreshTokens = `-- name: GetRefreshTokens :many
SELECT
    m_refresh_token.public_id,
    m_refresh_token.created_at,
    m_refresh_token.updated_at,
    m_refresh_token.country_code,
    m_refresh_token.city_name,
    m_refresh_token.browser_name
FROM
    m_refresh_token
    INNER JOIN m_user ON m_user.m_user_authorization_id = m_refresh_token.m_user_authorization_id
WHERE
    m_user.public_id = $1
ORDER BY
    m_refresh_token.created_at DESC
LIMIT
    $2 OFFSET $3
`

type GetRefreshTokensParams struct {
	PublicID uuid.UUID
	Limit    int32
	Offset   int32
}

type GetRefreshTokensRow struct {
	PublicID    uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CountryCode string
	CityName    string
	BrowserName string
}

// userテーブルのpublic_idから、そのリフレッシュトークンの一覧を返します。
func (q *Queries) GetRefreshTokens(ctx context.Context, arg GetRefreshTokensParams) ([]GetRefreshTokensRow, error) {
	rows, err := q.db.Query(ctx, getRefreshTokens, arg.PublicID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRefreshTokensRow
	for rows.Next() {
		var i GetRefreshTokensRow
		if err := rows.Scan(
			&i.PublicID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CountryCode,
			&i.CityName,
			&i.BrowserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIDByAuthorization = `-- name: GetUserIDByAuthorization :one
SELECT
    m_user.public_id,
    false AS is_h
FROM
    m_user
WHERE
    m_user.m_user_authorization_id = $1
UNION ALL
SELECT
    h_user.public_id,
    true AS is_h
FROM
    h_user
WHERE
    h_user.m_user_authorization_id = $1
ORDER BY
    is_h
LIMIT
    1
`

type GetUserIDByAuthorizationRow struct {
	PublicID uuid.UUID
	IsH      bool
}

// authorization_idから、そのユーザーのpublic_idを取得する。
// authorization_idが存在しない場合はpgx.ErrNoRowsが返される。
// 退会済みの場合はtrueが返ってくる。
func (q *Queries) GetUserIDByAuthorization(ctx context.Context, mUserAuthorizationID int64) (GetUserIDByAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, getUserIDByAuthorization, mUserAuthorizationID)
	var i GetUserIDByAuthorizationRow
	err := row.Scan(&i.PublicID, &i.IsH)
	return i, err
}

const isJTIBlacklisted = `-- name: IsJTIBlacklisted :one
SELECT
    expires_at
FROM
    t_jti_blacklist
WHERE
    jti = $1
LIMIT
    1
`

// jtiがブラックリストに存在するか確認する。
// jtiが存在しない場合はpgx.ErrTxClosedが返される。
// jtiが存在する場合は、そのexpires_atが返される。
func (q *Queries) IsJTIBlacklisted(ctx context.Context, jti uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, isJTIBlacklisted, jti)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const removeRefreshTokenByIDAndSaveJtiBlacklist = `-- name: RemoveRefreshTokenByIDAndSaveJtiBlacklist :one
WITH deleted AS (
    DELETE FROM
        m_refresh_token USING m_user
    WHERE
        m_user.public_id = $1
        AND m_user.m_user_authorization_id = m_refresh_token.m_user_authorization_id
        AND m_refresh_token.public_id = $2
    RETURNING
        m_refresh_token.public_id,
        m_refresh_token.access_token_jti
),
inserted AS (
    INSERT INTO
        t_jti_blacklist (jti, expires_at)
    SELECT
        access_token_jti,
        $3
    FROM
        deleted
    ON CONFLICT DO NOTHING
    RETURNING
        jti
)
SELECT
    deleted.public_id
FROM
    deleted
LIMIT
    1
`

type RemoveRefreshTokenByIDAndSaveJtiBlacklistParams struct {
	UserPublicID         uuid.UUID
	RefreshTokenPublicID uuid.UUID
	ExpiresAt            time.Time
}

// m_refresh_tokenのpublic_idから、そのレコードを削除します。
// 削除されたレコードに紐づくjtiをブラックリストに保存します。
// 削除されたレコードのpublic_idが返されます。
func (q *Queries) RemoveRefreshTokenByIDAndSaveJtiBlacklist(ctx context.Context, arg RemoveRefreshTokenByIDAndSaveJtiBlacklistParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, removeRefreshTokenByIDAndSaveJtiBlacklist, arg.UserPublicID, arg.RefreshTokenPublicID, arg.ExpiresAt)
	var public_id uuid.UUID
	err := row.Scan(&public_id)
	return public_id, err
}

const removeRefreshTokenByTokenHashAndSaveJtiBlacklist = `-- name: RemoveRefreshTokenByTokenHashAndSaveJtiBlacklist :one
WITH deleted AS (
    DELETE FROM
        m_refresh_token USING m_user
    WHERE
        m_user.public_id = $1
        AND m_user.m_user_authorization_id = m_refresh_token.m_user_authorization_id
        AND m_refresh_token.token_hash = $2
    RETURNING
        m_refresh_token.public_id,
        m_refresh_token.access_token_jti
),
inserted AS (
    INSERT INTO
        t_jti_blacklist (jti, expires_at)
    SELECT
        access_token_jti,
        $3
    FROM
        deleted
    ON CONFLICT DO NOTHING
    RETURNING
        jti
)
SELECT
    deleted.public_id
FROM
    deleted
LIMIT
    1
`

type RemoveRefreshTokenByTokenHashAndSaveJtiBlacklistParams struct {
	UserPublicID uuid.UUID
	TokenHash    string
	ExpiresAt    time.Time
}

// m_refresh_tokenのtoken_hashから、そのレコードを削除します。
// 削除されたレコードに紐づくjtiをブラックリストに保存します。
// 削除されたレコードのpublic_idが返されます。
func (q *Queries) RemoveRefreshTokenByTokenHashAndSaveJtiBlacklist(ctx context.Context, arg RemoveRefreshTokenByTokenHashAndSaveJtiBlacklistParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, removeRefreshTokenByTokenHashAndSaveJtiBlacklist, arg.UserPublicID, arg.TokenHash, arg.ExpiresAt)
	var public_id uuid.UUID
	err := row.Scan(&public_id)
	return public_id, err
}

const saveAuthorization = `-- name: SaveAuthorization :one
INSERT INTO
    m_user_authorization (issuer, sub)
VALUES
    ($1, $2)
ON CONFLICT (issuer, sub) DO
UPDATE
SET
    issuer = EXCLUDED.issuer,
    last_logged_in_at = current_timestamp
RETURNING
    m_user_authorization_id,
    public_id,
    (xmax = 0) AS is_created
`

type SaveAuthorizationParams struct {
	Issuer string
	Sub    string
}

type SaveAuthorizationRow struct {
	MUserAuthorizationID int64
	PublicID             uuid.UUID
	IsCreated            bool
}

// 認証テーブルにIssuerとSubを保存する
// IssuerとSubの組み合わせで一意制約があり、既に存在する場合は、何もしない。
// 重複した場合でも特にエラーは発生せず、既存のレコードが返される。
// 返り値は、m_user_authorization_idとpublic_id、そして新規作成されたかどうかを示すis_createdフラグ。
func (q *Queries) SaveAuthorization(ctx context.Context, arg SaveAuthorizationParams) (SaveAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, saveAuthorization, arg.Issuer, arg.Sub)
	var i SaveAuthorizationRow
	err := row.Scan(&i.MUserAuthorizationID, &i.PublicID, &i.IsCreated)
	return i, err
}

const saveJTIBlacklist = `-- name: SaveJTIBlacklist :exec
INSERT INTO
    t_jti_blacklist (jti, expires_at)
VALUES
    ($1, $2)
ON CONFLICT DO NOTHING
`

type SaveJTIBlacklistParams struct {
	Jti       uuid.UUID
	ExpiresAt time.Time
}

// jtiのブラックリストに追加する。
// jtiに一意制約があり、重複する場合は何もしない。
func (q *Queries) SaveJTIBlacklist(ctx context.Context, arg SaveJTIBlacklistParams) error {
	_, err := q.db.Exec(ctx, saveJTIBlacklist, arg.Jti, arg.ExpiresAt)
	return err
}

const saveRefreshToken = `-- name: SaveRefreshToken :one
INSERT INTO
    m_refresh_token (
        m_user_authorization_id,
        token_hash,
        ip_address,
        device_fingerprint,
        user_agent,
        country_code,
        city_name,
        browser_name,
        device_type,
        expires_at,
        access_token_jti
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING
    m_refresh_token_id
`

type SaveRefreshTokenParams struct {
	MUserAuthorizationID int64
	TokenHash            string
	IpAddress            string
	DeviceFingerprint    string
	UserAgent            string
	CountryCode          string
	CityName             string
	BrowserName          string
	DeviceType           string
	ExpiresAt            time.Time
	AccessTokenJti       uuid.UUID
}

// リフレッシュトークンをテーブルに保存する。
// m_refresh_token_idが返される。
func (q *Queries) SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, saveRefreshToken,
		arg.MUserAuthorizationID,
		arg.TokenHash,
		arg.IpAddress,
		arg.DeviceFingerprint,
		arg.UserAgent,
		arg.CountryCode,
		arg.CityName,
		arg.BrowserName,
		arg.DeviceType,
		arg.ExpiresAt,
		arg.AccessTokenJti,
	)
	var m_refresh_token_id int64
	err := row.Scan(&m_refresh_token_id)
	return m_refresh_token_id, err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :one
WITH updated AS (
    UPDATE
        m_refresh_token
    SET
        token_hash = $1,
        expires_at = $2,
        ip_address = $3,
        device_fingerprint = $4,
        user_agent = $5,
        country_code = $6,
        city_name = $7,
        browser_name = $8,
        device_type = $9,
        updated_at = current_timestamp,
        generation = generation + 1,
        access_token_jti = $10
    WHERE
        token_hash = $11 -- NOTE: token_hashにunique indexがあるため、updated_at, expires_atにインデックスは張らなくてもよい
        AND m_refresh_token.updated_at < $12
        AND expires_at > current_timestamp
    RETURNING
        m_user_authorization_id
)
SELECT
    public_id
FROM
    m_user
    INNER JOIN updated ON m_user.m_user_authorization_id = updated.m_user_authorization_id
LIMIT
    1
`

type UpdateRefreshTokenParams struct {
	NewTokenHash         string
	NewExpiresAt         time.Time
	NewIpAddress         string
	NewDeviceFingerprint string
	NewUserAgent         string
	NewCountryCode       string
	NewCityName          string
	NewBrowserName       string
	NewDeviceType        string
	NewAccessTokenJti    uuid.UUID
	TokenHashForCheck    string
	UpdatedAtForCheck    time.Time
}

// リフレッシュトークンを更新します。
// token_hash = token_hash_for_check
// updated_at < updated_at_for_check
// expires_at > current_timestamp
// の条件をすべて満たす場合にのみ更新されます。条件を満たさない場合は、pgx.ErrTxClosedが返されます。
// リフレッシュトークンに紐づくuser_authorization_idから、それに紐づくuserのpublic_idを返します。
func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateRefreshToken,
		arg.NewTokenHash,
		arg.NewExpiresAt,
		arg.NewIpAddress,
		arg.NewDeviceFingerprint,
		arg.NewUserAgent,
		arg.NewCountryCode,
		arg.NewCityName,
		arg.NewBrowserName,
		arg.NewDeviceType,
		arg.NewAccessTokenJti,
		arg.TokenHashForCheck,
		arg.UpdatedAtForCheck,
	)
	var public_id uuid.UUID
	err := row.Scan(&public_id)
	return public_id, err
}
