// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearStaleChannelCustomID = `-- name: ClearStaleChannelCustomID :exec
UPDATE m_channel
SET external_custom_id = '@' || external_id
WHERE external_custom_id = $1
  AND external_id != $2
`

type ClearStaleChannelCustomIDParams struct {
	ExternalCustomID string
	ExternalID       string
}

// NOTE: SaveChannelの前にこれをする. CTEでやろうと思ったけど、トランザクション...
func (q *Queries) ClearStaleChannelCustomID(ctx context.Context, arg ClearStaleChannelCustomIDParams) error {
	_, err := q.db.Exec(ctx, clearStaleChannelCustomID, arg.ExternalCustomID, arg.ExternalID)
	return err
}

const deleteChannelSubscription = `-- name: DeleteChannelSubscription :execrows
DELETE FROM
    m_user_subscribing_channel
WHERE
    m_user_subscribing_channel.public_id = $1
    AND m_user_subscribing_channel.m_user_id = (
        SELECT
            m_user.m_user_id
        FROM
            m_user
        WHERE
            m_user.public_id = $2
        LIMIT
            1
    )
`

type DeleteChannelSubscriptionParams struct {
	SubscriptionPublicID uuid.UUID
	UserPublicID         uuid.UUID
}

func (q *Queries) DeleteChannelSubscription(ctx context.Context, arg DeleteChannelSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelSubscription, arg.SubscriptionPublicID, arg.UserPublicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannelByIdOrHandle = `-- name: GetChannelByIdOrHandle :one
SELECT
    m_channel.m_channel_id,
    m_channel.public_id,
    m_channel.external_id,
    m_channel.external_custom_id,
    m_channel.external_display_name,
    m_channel.external_description,
    m_channel.external_icon_url,
    m_channel.external_subscribers_count,
    m_channel.external_created_at
FROM
    m_channel
WHERE
    m_channel.external_id = $1
    OR m_channel.external_custom_id = $2
LIMIT
    1
`

type GetChannelByIdOrHandleParams struct {
	ExternalID       string
	ExternalCustomID string
}

type GetChannelByIdOrHandleRow struct {
	MChannelID               int64
	PublicID                 uuid.UUID
	ExternalID               string
	ExternalCustomID         string
	ExternalDisplayName      string
	ExternalDescription      string
	ExternalIconUrl          string
	ExternalSubscribersCount int64
	ExternalCreatedAt        time.Time
}

func (q *Queries) GetChannelByIdOrHandle(ctx context.Context, arg GetChannelByIdOrHandleParams) (GetChannelByIdOrHandleRow, error) {
	row := q.db.QueryRow(ctx, getChannelByIdOrHandle, arg.ExternalID, arg.ExternalCustomID)
	var i GetChannelByIdOrHandleRow
	err := row.Scan(
		&i.MChannelID,
		&i.PublicID,
		&i.ExternalID,
		&i.ExternalCustomID,
		&i.ExternalDisplayName,
		&i.ExternalDescription,
		&i.ExternalIconUrl,
		&i.ExternalSubscribersCount,
		&i.ExternalCreatedAt,
	)
	return i, err
}

const getChannelRSSFetchedAtForUpdate = `-- name: GetChannelRSSFetchedAtForUpdate :one
SELECT
    m_channel.m_channel_id,
    m_channel.rss_fetched_at,
    m_channel.external_id
FROM
    m_channel
WHERE
    m_channel.public_id = $1
LIMIT
    1
FOR UPDATE
`

type GetChannelRSSFetchedAtForUpdateRow struct {
	MChannelID   int64
	RssFetchedAt time.Time
	ExternalID   string
}

func (q *Queries) GetChannelRSSFetchedAtForUpdate(ctx context.Context, channelID uuid.UUID) (GetChannelRSSFetchedAtForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getChannelRSSFetchedAtForUpdate, channelID)
	var i GetChannelRSSFetchedAtForUpdateRow
	err := row.Scan(&i.MChannelID, &i.RssFetchedAt, &i.ExternalID)
	return i, err
}

const getChannelSubscriptions = `-- name: GetChannelSubscriptions :many
SELECT
    m_user_subscribing_channel.public_id,
    m_user_subscribing_channel.created_at,
    m_channel.public_id AS channel_public_id,
    m_channel.external_id,
    m_channel.external_display_name,
    m_channel.external_description,
    m_channel.external_custom_id,
    m_channel.external_icon_url,
    m_channel.external_subscribers_count,
    m_channel.external_created_at
FROM
    m_user_subscribing_channel
    INNER JOIN m_channel ON m_channel.m_channel_id = m_user_subscribing_channel.m_channel_id
WHERE
    m_user_subscribing_channel.m_user_id = (
        SELECT
            m_user.m_user_id
        FROM
            m_user
        WHERE
            m_user.public_id = $1
        LIMIT
            1
    )
    AND (
        $2 :: uuid IS NULL
        OR m_user_subscribing_channel.public_id < $2 :: uuid
    )
ORDER BY
    m_user_subscribing_channel.m_user_id,
    m_user_subscribing_channel.public_id DESC
LIMIT
    $3
`

type GetChannelSubscriptionsParams struct {
	UserPublicID   uuid.UUID
	CursorPublicID *uuid.UUID
	QueryLimit     int32
}

type GetChannelSubscriptionsRow struct {
	PublicID                 uuid.UUID
	CreatedAt                time.Time
	ChannelPublicID          uuid.UUID
	ExternalID               string
	ExternalDisplayName      string
	ExternalDescription      string
	ExternalCustomID         string
	ExternalIconUrl          string
	ExternalSubscribersCount int64
	ExternalCreatedAt        time.Time
}

func (q *Queries) GetChannelSubscriptions(ctx context.Context, arg GetChannelSubscriptionsParams) ([]GetChannelSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, getChannelSubscriptions, arg.UserPublicID, arg.CursorPublicID, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelSubscriptionsRow
	for rows.Next() {
		var i GetChannelSubscriptionsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.CreatedAt,
			&i.ChannelPublicID,
			&i.ExternalID,
			&i.ExternalDisplayName,
			&i.ExternalDescription,
			&i.ExternalCustomID,
			&i.ExternalIconUrl,
			&i.ExternalSubscribersCount,
			&i.ExternalCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelsToFetchRSSForUpdate = `-- name: GetChannelsToFetchRSSForUpdate :many
SELECT
    c.external_id,
    c.m_channel_id
FROM
    m_channel c
INNER JOIN
    m_user_subscribing_channel sub
ON
    c.m_channel_id = sub.m_channel_id
WHERE
    sub.m_user_id = (SELECT u.m_user_id FROM m_user u WHERE u.public_id = $1) AND
    c.rss_fetched_at < $2
ORDER BY c.rss_fetched_at
LIMIT $3
FOR UPDATE
`

type GetChannelsToFetchRSSForUpdateParams struct {
	UserID     uuid.UUID
	RssFetch   time.Time
	QueryLimit int32
}

type GetChannelsToFetchRSSForUpdateRow struct {
	ExternalID string
	MChannelID int64
}

func (q *Queries) GetChannelsToFetchRSSForUpdate(ctx context.Context, arg GetChannelsToFetchRSSForUpdateParams) ([]GetChannelsToFetchRSSForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getChannelsToFetchRSSForUpdate, arg.UserID, arg.RssFetch, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelsToFetchRSSForUpdateRow
	for rows.Next() {
		var i GetChannelsToFetchRSSForUpdateRow
		if err := rows.Scan(&i.ExternalID, &i.MChannelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChannelRSSAsFetched = `-- name: MarkChannelRSSAsFetched :one
UPDATE
    m_channel
SET
    rss_fetched_at = CURRENT_TIMESTAMP
WHERE
    m_channel_id = ANY($1::bigint[])
RETURNING
    public_id
`

func (q *Queries) MarkChannelRSSAsFetched(ctx context.Context, mChannelIds []int64) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, markChannelRSSAsFetched, mChannelIds)
	var public_id uuid.UUID
	err := row.Scan(&public_id)
	return public_id, err
}

const saveChannel = `-- name: SaveChannel :one
INSERT INTO
    m_channel (
        external_id,
        external_display_name,
        external_custom_id,
        external_icon_url,
        external_description,
        external_subscribers_count,
        external_created_at,
        external_uploads_playlist_id
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (external_id) DO UPDATE SET
    external_display_name = EXCLUDED.external_display_name,
    external_custom_id = EXCLUDED.external_custom_id,
    external_icon_url = EXCLUDED.external_icon_url,
    external_description = EXCLUDED.external_description,
    external_subscribers_count = EXCLUDED.external_subscribers_count,
    external_created_at = EXCLUDED.external_created_at,
    external_uploads_playlist_id = EXCLUDED.external_uploads_playlist_id,
    updated_at = CURRENT_TIMESTAMP
RETURNING
    m_channel.m_channel_id,
    m_channel.public_id,
    m_channel.created_at
`

type SaveChannelParams struct {
	ExternalID                string
	ExternalDisplayName       string
	ExternalCustomID          string
	ExternalIconUrl           string
	ExternalDescription       string
	ExternalSubscribersCount  int64
	ExternalCreatedAt         time.Time
	ExternalUploadsPlaylistID string
}

type SaveChannelRow struct {
	MChannelID int64
	PublicID   uuid.UUID
	CreatedAt  time.Time
}

func (q *Queries) SaveChannel(ctx context.Context, arg SaveChannelParams) (SaveChannelRow, error) {
	row := q.db.QueryRow(ctx, saveChannel,
		arg.ExternalID,
		arg.ExternalDisplayName,
		arg.ExternalCustomID,
		arg.ExternalIconUrl,
		arg.ExternalDescription,
		arg.ExternalSubscribersCount,
		arg.ExternalCreatedAt,
		arg.ExternalUploadsPlaylistID,
	)
	var i SaveChannelRow
	err := row.Scan(&i.MChannelID, &i.PublicID, &i.CreatedAt)
	return i, err
}

const saveChannelSubscription = `-- name: SaveChannelSubscription :one
WITH subscriber AS (
    SELECT
        m_user.m_user_id
    FROM
        m_user
    WHERE
        m_user.public_id = $2
    LIMIT
        1
)
INSERT INTO
    m_user_subscribing_channel (m_user_id, m_channel_id)
SELECT
    subscriber.m_user_id AS m_user_id,
    $1 AS m_channel_id
FROM
    subscriber
RETURNING
    m_user_subscribing_channel.public_id,
    m_user_subscribing_channel.created_at
`

type SaveChannelSubscriptionParams struct {
	ChannelID    int64
	UserPublicID uuid.UUID
}

type SaveChannelSubscriptionRow struct {
	PublicID  uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) SaveChannelSubscription(ctx context.Context, arg SaveChannelSubscriptionParams) (SaveChannelSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, saveChannelSubscription, arg.ChannelID, arg.UserPublicID)
	var i SaveChannelSubscriptionRow
	err := row.Scan(&i.PublicID, &i.CreatedAt)
	return i, err
}
