// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearStaleChannelCustomID = `-- name: ClearStaleChannelCustomID :exec
UPDATE
    m_channel
SET
    external_custom_id = '@' || external_id
WHERE
    external_custom_id = $1
    AND external_id != $2
`

type ClearStaleChannelCustomIDParams struct {
	ExternalCustomID string
	ExternalID       string
}

// NOTE: SaveChannelの前にこれをする. CTEでやろうと思ったけど、トランザクション...
func (q *Queries) ClearStaleChannelCustomID(ctx context.Context, arg ClearStaleChannelCustomIDParams) error {
	_, err := q.db.Exec(ctx, clearStaleChannelCustomID, arg.ExternalCustomID, arg.ExternalID)
	return err
}

const deleteSubscription = `-- name: DeleteSubscription :one
DELETE FROM
    m_user_subscribing_channel
WHERE
    m_user_subscribing_channel.m_user_id = (
        SELECT
            m_user.m_user_id
        FROM
            m_user
        WHERE
            m_user.public_id = $1
        LIMIT
            1
    )
    AND m_user_subscribing_channel.m_channel_id = (
        SELECT
            c.m_channel_id
        FROM
            m_channel c
        WHERE
            c.public_id = $2
        LIMIT
            1
    )
RETURNING m_user_subscribing_channel.m_user_subscribing_channel_id
`

type DeleteSubscriptionParams struct {
	UserPublicID uuid.UUID
	ChannelID    uuid.UUID
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteSubscription, arg.UserPublicID, arg.ChannelID)
	var m_user_subscribing_channel_id int64
	err := row.Scan(&m_user_subscribing_channel_id)
	return m_user_subscribing_channel_id, err
}

const findChannelByExternalID = `-- name: FindChannelByExternalID :one
SELECT
    m_channel.m_channel_id,
    m_channel.public_id,
    m_channel.external_id,
    m_channel.external_custom_id,
    m_channel.external_display_name,
    m_channel.external_description,
    m_channel.external_icon_url,
    m_channel.external_subscribers_count,
    m_channel.external_created_at,
    m_channel.external_uploads_playlist_id,
    m_channel.fetched_at,
    m_channel.rss_fetched_at,
    m_channel.bulk_fetched_at
FROM
    m_channel
WHERE
    m_channel.external_id = $1
    OR m_channel.external_custom_id = $2
LIMIT
    1
`

type FindChannelByExternalIDParams struct {
	ExternalID       string
	ExternalCustomID string
}

type FindChannelByExternalIDRow struct {
	MChannelID                int64
	PublicID                  uuid.UUID
	ExternalID                string
	ExternalCustomID          string
	ExternalDisplayName       string
	ExternalDescription       string
	ExternalIconUrl           string
	ExternalSubscribersCount  int64
	ExternalCreatedAt         time.Time
	ExternalUploadsPlaylistID string
	FetchedAt                 time.Time
	RssFetchedAt              time.Time
	BulkFetchedAt             time.Time
}

func (q *Queries) FindChannelByExternalID(ctx context.Context, arg FindChannelByExternalIDParams) (FindChannelByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, findChannelByExternalID, arg.ExternalID, arg.ExternalCustomID)
	var i FindChannelByExternalIDRow
	err := row.Scan(
		&i.MChannelID,
		&i.PublicID,
		&i.ExternalID,
		&i.ExternalCustomID,
		&i.ExternalDisplayName,
		&i.ExternalDescription,
		&i.ExternalIconUrl,
		&i.ExternalSubscribersCount,
		&i.ExternalCreatedAt,
		&i.ExternalUploadsPlaylistID,
		&i.FetchedAt,
		&i.RssFetchedAt,
		&i.BulkFetchedAt,
	)
	return i, err
}

const getChannelByPublicID = `-- name: GetChannelByPublicID :one
SELECT
    m_channel.public_id,
    m_channel.external_custom_id,
    m_channel.external_display_name,
    m_channel.external_description,
    m_channel.external_icon_url,
    m_channel.external_subscribers_count
FROM
    m_channel
WHERE
    m_channel.public_id = $1
LIMIT
    1
`

type GetChannelByPublicIDRow struct {
	PublicID                 uuid.UUID
	ExternalCustomID         string
	ExternalDisplayName      string
	ExternalDescription      string
	ExternalIconUrl          string
	ExternalSubscribersCount int64
}

func (q *Queries) GetChannelByPublicID(ctx context.Context, channelID uuid.UUID) (GetChannelByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getChannelByPublicID, channelID)
	var i GetChannelByPublicIDRow
	err := row.Scan(
		&i.PublicID,
		&i.ExternalCustomID,
		&i.ExternalDisplayName,
		&i.ExternalDescription,
		&i.ExternalIconUrl,
		&i.ExternalSubscribersCount,
	)
	return i, err
}

const getChannelForUpdate = `-- name: GetChannelForUpdate :one
SELECT
    m_channel.public_id,
    m_channel.external_id,
    m_channel.external_display_name,
    m_channel.external_description,
    m_channel.external_custom_id,
    m_channel.external_icon_url,
    m_channel.external_subscribers_count,
    m_channel.external_created_at,
    m_channel.rss_fetched_at,
    m_channel.fetched_at,
    m_channel.external_uploads_playlist_id,
    m_channel.bulk_fetched_at
FROM
    m_channel
WHERE
    m_channel.public_id = $1
LIMIT
    1
FOR UPDATE
`

type GetChannelForUpdateRow struct {
	PublicID                  uuid.UUID
	ExternalID                string
	ExternalDisplayName       string
	ExternalDescription       string
	ExternalCustomID          string
	ExternalIconUrl           string
	ExternalSubscribersCount  int64
	ExternalCreatedAt         time.Time
	RssFetchedAt              time.Time
	FetchedAt                 time.Time
	ExternalUploadsPlaylistID string
	BulkFetchedAt             time.Time
}

func (q *Queries) GetChannelForUpdate(ctx context.Context, channelID uuid.UUID) (GetChannelForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getChannelForUpdate, channelID)
	var i GetChannelForUpdateRow
	err := row.Scan(
		&i.PublicID,
		&i.ExternalID,
		&i.ExternalDisplayName,
		&i.ExternalDescription,
		&i.ExternalCustomID,
		&i.ExternalIconUrl,
		&i.ExternalSubscribersCount,
		&i.ExternalCreatedAt,
		&i.RssFetchedAt,
		&i.FetchedAt,
		&i.ExternalUploadsPlaylistID,
		&i.BulkFetchedAt,
	)
	return i, err
}

const insertSubscription = `-- name: InsertSubscription :one
INSERT INTO
    m_user_subscribing_channel (m_user_id, m_channel_id, subscribed_at)
SELECT
    (
        SELECT
            m_user.m_user_id
        FROM
            m_user
        WHERE
            m_user.public_id = $1
        LIMIT
            1
    ) AS m_user_id,
    (
        SELECT
            m_channel.m_channel_id
        FROM
            m_channel
        WHERE
            m_channel.public_id = $2
        LIMIT
            1
    ),
    $3
RETURNING
    m_user_subscribing_channel.m_user_subscribing_channel_id
`

type InsertSubscriptionParams struct {
	UserPublicID uuid.UUID
	ChannelID    uuid.UUID
	SubscribedAt time.Time
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSubscription, arg.UserPublicID, arg.ChannelID, arg.SubscribedAt)
	var m_user_subscribing_channel_id int64
	err := row.Scan(&m_user_subscribing_channel_id)
	return m_user_subscribing_channel_id, err
}

const listChannelsBulkFetchedBefore = `-- name: ListChannelsBulkFetchedBefore :many
SELECT
    c.public_id,
    c.external_id,
    c.external_display_name,
    c.external_description,
    c.external_custom_id,
    c.external_icon_url,
    c.external_subscribers_count,
    c.external_created_at,
    c.external_uploads_playlist_id,
    c.rss_fetched_at,
    c.fetched_at,
    c.bulk_fetched_at
FROM
    m_channel c
WHERE
    c.bulk_fetched_at < $1
`

type ListChannelsBulkFetchedBeforeRow struct {
	PublicID                  uuid.UUID
	ExternalID                string
	ExternalDisplayName       string
	ExternalDescription       string
	ExternalCustomID          string
	ExternalIconUrl           string
	ExternalSubscribersCount  int64
	ExternalCreatedAt         time.Time
	ExternalUploadsPlaylistID string
	RssFetchedAt              time.Time
	FetchedAt                 time.Time
	BulkFetchedAt             time.Time
}

func (q *Queries) ListChannelsBulkFetchedBefore(ctx context.Context, bulkFetchedBefore time.Time) ([]ListChannelsBulkFetchedBeforeRow, error) {
	rows, err := q.db.Query(ctx, listChannelsBulkFetchedBefore, bulkFetchedBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsBulkFetchedBeforeRow
	for rows.Next() {
		var i ListChannelsBulkFetchedBeforeRow
		if err := rows.Scan(
			&i.PublicID,
			&i.ExternalID,
			&i.ExternalDisplayName,
			&i.ExternalDescription,
			&i.ExternalCustomID,
			&i.ExternalIconUrl,
			&i.ExternalSubscribersCount,
			&i.ExternalCreatedAt,
			&i.ExternalUploadsPlaylistID,
			&i.RssFetchedAt,
			&i.FetchedAt,
			&i.BulkFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleRSSChannelsForUpdate = `-- name: ListStaleRSSChannelsForUpdate :many
SELECT
    c.public_id,
    c.external_id,
    c.external_display_name,
    c.external_description,
    c.external_custom_id,
    c.external_icon_url,
    c.external_subscribers_count,
    c.external_created_at,
    c.external_uploads_playlist_id,
    c.rss_fetched_at,
    c.fetched_at,
    c.bulk_fetched_at
FROM
    m_channel c
    INNER JOIN m_user_subscribing_channel sub ON c.m_channel_id = sub.m_channel_id
WHERE
    sub.m_user_id = (
        SELECT
            u.m_user_id
        FROM
            m_user u
        WHERE
            u.public_id = $1
        LIMIT
            1
    )
    AND c.rss_fetched_at < $2
ORDER BY
    c.rss_fetched_at
LIMIT
    $3
FOR UPDATE
`

type ListStaleRSSChannelsForUpdateParams struct {
	UserID     uuid.UUID
	RssFetch   time.Time
	QueryLimit int32
}

type ListStaleRSSChannelsForUpdateRow struct {
	PublicID                  uuid.UUID
	ExternalID                string
	ExternalDisplayName       string
	ExternalDescription       string
	ExternalCustomID          string
	ExternalIconUrl           string
	ExternalSubscribersCount  int64
	ExternalCreatedAt         time.Time
	ExternalUploadsPlaylistID string
	RssFetchedAt              time.Time
	FetchedAt                 time.Time
	BulkFetchedAt             time.Time
}

func (q *Queries) ListStaleRSSChannelsForUpdate(ctx context.Context, arg ListStaleRSSChannelsForUpdateParams) ([]ListStaleRSSChannelsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listStaleRSSChannelsForUpdate, arg.UserID, arg.RssFetch, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleRSSChannelsForUpdateRow
	for rows.Next() {
		var i ListStaleRSSChannelsForUpdateRow
		if err := rows.Scan(
			&i.PublicID,
			&i.ExternalID,
			&i.ExternalDisplayName,
			&i.ExternalDescription,
			&i.ExternalCustomID,
			&i.ExternalIconUrl,
			&i.ExternalSubscribersCount,
			&i.ExternalCreatedAt,
			&i.ExternalUploadsPlaylistID,
			&i.RssFetchedAt,
			&i.FetchedAt,
			&i.BulkFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribedChannels = `-- name: ListSubscribedChannels :many
SELECT
    m_channel.public_id AS channel_public_id,
    m_channel.external_id,
    m_channel.external_custom_id,
    m_channel.external_display_name,
    m_channel.external_icon_url,
    m_channel.external_subscribers_count
FROM
    m_user_subscribing_channel
    INNER JOIN m_channel ON m_channel.m_channel_id = m_user_subscribing_channel.m_channel_id
WHERE
    m_user_subscribing_channel.m_user_id = (
        SELECT
            m_user.m_user_id
        FROM
            m_user
        WHERE
            m_user.public_id = $1
        LIMIT
            1
    )
    AND (
        $2 :: uuid IS NULL
        OR m_channel.public_id < $2 :: uuid
    )
ORDER BY
    m_channel.public_id DESC
LIMIT
    $3
`

type ListSubscribedChannelsParams struct {
	UserPublicID   uuid.UUID
	CursorPublicID *uuid.UUID
	QueryLimit     int32
}

type ListSubscribedChannelsRow struct {
	ChannelPublicID          uuid.UUID
	ExternalID               string
	ExternalCustomID         string
	ExternalDisplayName      string
	ExternalIconUrl          string
	ExternalSubscribersCount int64
}

func (q *Queries) ListSubscribedChannels(ctx context.Context, arg ListSubscribedChannelsParams) ([]ListSubscribedChannelsRow, error) {
	rows, err := q.db.Query(ctx, listSubscribedChannels, arg.UserPublicID, arg.CursorPublicID, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscribedChannelsRow
	for rows.Next() {
		var i ListSubscribedChannelsRow
		if err := rows.Scan(
			&i.ChannelPublicID,
			&i.ExternalID,
			&i.ExternalCustomID,
			&i.ExternalDisplayName,
			&i.ExternalIconUrl,
			&i.ExternalSubscribersCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChannel = `-- name: UpsertChannel :one
INSERT INTO
    m_channel (
        external_id,
        external_display_name,
        external_custom_id,
        external_icon_url,
        external_description,
        external_subscribers_count,
        external_created_at,
        external_uploads_playlist_id,
        public_id,
        rss_fetched_at,
        fetched_at,
        bulk_fetched_at
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (external_id) DO UPDATE SET
    external_display_name = EXCLUDED.external_display_name,
    external_custom_id = EXCLUDED.external_custom_id,
    external_icon_url = EXCLUDED.external_icon_url,
    external_description = EXCLUDED.external_description,
    external_subscribers_count = EXCLUDED.external_subscribers_count,
    external_created_at = EXCLUDED.external_created_at,
    external_uploads_playlist_id = EXCLUDED.external_uploads_playlist_id,
    updated_at = CURRENT_TIMESTAMP,
    rss_fetched_at = EXCLUDED.rss_fetched_at,
    fetched_at = EXCLUDED.fetched_at,
    bulk_fetched_at = EXCLUDED.bulk_fetched_at
RETURNING
    m_channel.m_channel_id,
    m_channel.public_id
`

type UpsertChannelParams struct {
	ExternalID                string
	ExternalDisplayName       string
	ExternalCustomID          string
	ExternalIconUrl           string
	ExternalDescription       string
	ExternalSubscribersCount  int64
	ExternalCreatedAt         time.Time
	ExternalUploadsPlaylistID string
	PublicID                  uuid.UUID
	RssFetchedAt              time.Time
	FetchedAt                 time.Time
	BulkFetchedAt             time.Time
}

type UpsertChannelRow struct {
	MChannelID int64
	PublicID   uuid.UUID
}

func (q *Queries) UpsertChannel(ctx context.Context, arg UpsertChannelParams) (UpsertChannelRow, error) {
	row := q.db.QueryRow(ctx, upsertChannel,
		arg.ExternalID,
		arg.ExternalDisplayName,
		arg.ExternalCustomID,
		arg.ExternalIconUrl,
		arg.ExternalDescription,
		arg.ExternalSubscribersCount,
		arg.ExternalCreatedAt,
		arg.ExternalUploadsPlaylistID,
		arg.PublicID,
		arg.RssFetchedAt,
		arg.FetchedAt,
		arg.BulkFetchedAt,
	)
	var i UpsertChannelRow
	err := row.Scan(&i.MChannelID, &i.PublicID)
	return i, err
}
