// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForBulkInsertPlaylistVideos implements pgx.CopyFromSource.
type iteratorForBulkInsertPlaylistVideos struct {
	rows                 []BulkInsertPlaylistVideosParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertPlaylistVideos) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertPlaylistVideos) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].MPlaylistID,
		r.rows[0].MVideoID,
		r.rows[0].PlaylistPosition,
	}, nil
}

func (r iteratorForBulkInsertPlaylistVideos) Err() error {
	return nil
}

func (q *Queries) BulkInsertPlaylistVideos(ctx context.Context, arg []BulkInsertPlaylistVideosParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"m_playlist_video"}, []string{"m_playlist_id", "m_video_id", "playlist_position"}, &iteratorForBulkInsertPlaylistVideos{rows: arg})
}

// iteratorForBulkInsertScreenTimeRanges implements pgx.CopyFromSource.
type iteratorForBulkInsertScreenTimeRanges struct {
	rows                 []BulkInsertScreenTimeRangesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertScreenTimeRanges) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertScreenTimeRanges) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].MUserID,
		r.rows[0].ScreenTimeRangeStart,
		r.rows[0].ScreenTimeRangeEnd,
	}, nil
}

func (r iteratorForBulkInsertScreenTimeRanges) Err() error {
	return nil
}

// NOTE: err == nilの場合はlen(param)
func (q *Queries) BulkInsertScreenTimeRanges(ctx context.Context, arg []BulkInsertScreenTimeRangesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"m_user_screen_time_range"}, []string{"m_user_id", "screen_time_range_start", "screen_time_range_end"}, &iteratorForBulkInsertScreenTimeRanges{rows: arg})
}
