// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getDailyWatchSummary = `-- name: GetDailyWatchSummary :one
SELECT
    (
        SELECT
            m_user.daily_screen_time_seconds
        FROM
            m_user
        WHERE
            m_user.public_id = $1
    )::int AS daily_limit_seconds,
    COALESCE(
        EXTRACT(
            EPOCH
            FROM
                SUM(
                    LEAST(t_video_watch.watch_end_at, CURRENT_TIMESTAMP) - t_video_watch.watch_start_at
                )
        )::bigint,
        0
    )::int AS today_watch_total
FROM
    t_video_watch
WHERE
    t_video_watch.m_user_id = (
        SELECT
            m_user.m_user_id
        FROM
            m_user
        WHERE
            m_user.public_id = $1
        LIMIT
            1
    )
    AND CURRENT_DATE <= t_video_watch.watch_start_at
    AND t_video_watch.watch_start_at < CURRENT_DATE + INTERVAL '1 day'
`

type GetDailyWatchSummaryRow struct {
	DailyLimitSeconds int
	TodayWatchTotal   int
}

// m_user.public_idから、そのユーザーが今日視聴していた合計時間(seconds)と設定している制限時間を返す。
// その日に一本も動画を視聴していない場合は0を返します。
func (q *Queries) GetDailyWatchSummary(ctx context.Context, publicID uuid.UUID) (GetDailyWatchSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDailyWatchSummary, publicID)
	var i GetDailyWatchSummaryRow
	err := row.Scan(&i.DailyLimitSeconds, &i.TodayWatchTotal)
	return i, err
}

const getLatestMonthlyVideoWatchSummary = `-- name: GetLatestMonthlyVideoWatchSummary :one
SELECT
    s.ai_summary_title,
    s.ai_summary_description,
    s.created_at
FROM
    s_monthly_video_watch s
WHERE
    s.m_user_id = (SELECT u.m_user_id FROM m_user u WHERE u.public_id = $1 LIMIT 1)
ORDER BY
    s.target_month DESC
LIMIT 1
`

type GetLatestMonthlyVideoWatchSummaryRow struct {
	AiSummaryTitle       string
	AiSummaryDescription string
	CreatedAt            time.Time
}

func (q *Queries) GetLatestMonthlyVideoWatchSummary(ctx context.Context, userID uuid.UUID) (GetLatestMonthlyVideoWatchSummaryRow, error) {
	row := q.db.QueryRow(ctx, getLatestMonthlyVideoWatchSummary, userID)
	var i GetLatestMonthlyVideoWatchSummaryRow
	err := row.Scan(&i.AiSummaryTitle, &i.AiSummaryDescription, &i.CreatedAt)
	return i, err
}

const listDailyWatchStatsByRange = `-- name: ListDailyWatchStatsByRange :many
SELECT
    DATE(video_watch.watch_start_at) AS watch_date,
    COUNT(DISTINCT video_watch.m_video_id) AS video_count,
    EXTRACT(EPOCH FROM SUM(video_watch.watch_end_at - video_watch.watch_start_at))::bigint AS watch_sum
FROM
    t_video_watch video_watch
WHERE
    video_watch.m_user_id = (
        SELECT
            u.m_user_id
        FROM
            m_user u
        WHERE
            u.public_id = $1
        LIMIT
            1
    )
    AND video_watch.watch_start_at BETWEEN $2 AND $3
    AND video_watch.watch_end_at <= CURRENT_TIMESTAMP
GROUP BY
    DATE(video_watch.watch_start_at)
`

type ListDailyWatchStatsByRangeParams struct {
	UserID    uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

type ListDailyWatchStatsByRangeRow struct {
	WatchDate  time.Time
	VideoCount int64
	WatchSum   int64
}

func (q *Queries) ListDailyWatchStatsByRange(ctx context.Context, arg ListDailyWatchStatsByRangeParams) ([]ListDailyWatchStatsByRangeRow, error) {
	rows, err := q.db.Query(ctx, listDailyWatchStatsByRange, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyWatchStatsByRangeRow
	for rows.Next() {
		var i ListDailyWatchStatsByRangeRow
		if err := rows.Scan(&i.WatchDate, &i.VideoCount, &i.WatchSum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchHistory = `-- name: ListWatchHistory :many
SELECT
    m_video.public_id AS video_id,
    m_video.external_title AS external_video_title,
    m_video.external_thumbnail_url AS external_video_thumbnail_url,
    m_video.external_length_seconds AS external_video_length_seconds,
    t_video_watch.watch_position_seconds,
    t_video_watch.watch_start_at AS watched_at,
    m_channel.public_id AS channel_id,
    m_channel.external_display_name AS external_channel_display_name,
    m_channel.external_icon_url AS external_channel_icon_url
FROM
    t_video_watch
    INNER JOIN m_video ON m_video.m_video_id = t_video_watch.m_video_id
    INNER JOIN m_channel ON m_channel.m_channel_id = m_video.m_channel_id
WHERE
    t_video_watch.m_user_id = (
        SELECT
            m_user.m_user_id
        FROM
            m_user
        WHERE
            m_user.public_id = $1
        LIMIT
            1
    )
    AND (
        $2::uuid IS NULL
        OR t_video_watch.public_id < $2::uuid
    )
ORDER BY
    t_video_watch.public_id DESC
LIMIT
    $3
`

type ListWatchHistoryParams struct {
	UserID     uuid.UUID
	Cursor     *uuid.UUID
	QueryLimit int32
}

type ListWatchHistoryRow struct {
	VideoID                    uuid.UUID
	ExternalVideoTitle         string
	ExternalVideoThumbnailUrl  string
	ExternalVideoLengthSeconds int
	WatchPositionSeconds       int
	WatchedAt                  time.Time
	ChannelID                  uuid.UUID
	ExternalChannelDisplayName string
	ExternalChannelIconUrl     string
}

func (q *Queries) ListWatchHistory(ctx context.Context, arg ListWatchHistoryParams) ([]ListWatchHistoryRow, error) {
	rows, err := q.db.Query(ctx, listWatchHistory, arg.UserID, arg.Cursor, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWatchHistoryRow
	for rows.Next() {
		var i ListWatchHistoryRow
		if err := rows.Scan(
			&i.VideoID,
			&i.ExternalVideoTitle,
			&i.ExternalVideoThumbnailUrl,
			&i.ExternalVideoLengthSeconds,
			&i.WatchPositionSeconds,
			&i.WatchedAt,
			&i.ChannelID,
			&i.ExternalChannelDisplayName,
			&i.ExternalChannelIconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWatchHeartbeat = `-- name: UpsertWatchHeartbeat :exec
WITH resolved_user AS (
    SELECT
        m_user_id
    FROM
        m_user
    WHERE
        m_user.public_id = $1
    LIMIT
        1
),
resolved_video AS (
    SELECT
        m_video_id
    FROM
        m_video
    WHERE
        m_video.public_id = $2
    LIMIT
        1
),
close_stale AS (
    -- heartbeatが途絶えた放置セッションをクローズ
    UPDATE
        t_video_watch
    SET
        watch_end_at = t_video_watch.updated_at,
        updated_at = CURRENT_TIMESTAMP
    WHERE
        m_user_id = (SELECT m_user_id FROM resolved_user)
        AND watch_end_at > CURRENT_TIMESTAMP
        AND t_video_watch.updated_at < CURRENT_TIMESTAMP - INTERVAL '2 minutes'
    RETURNING
        t_video_watch_id
),
latest_active AS (
    -- ユーザーの現在アクティブなレコードを取得（タイムアウトしていないもの）
    SELECT
        t_video_watch_id,
        m_video_id
    FROM
        t_video_watch
    WHERE
        m_user_id = (SELECT m_user_id FROM resolved_user)
        AND watch_end_at > CURRENT_TIMESTAMP
        AND updated_at > CURRENT_TIMESTAMP - INTERVAL '2 minutes'
    ORDER BY
        watch_start_at DESC
    LIMIT
        1
),
close_old AS (
    -- 別の動画なら終了させる
    UPDATE
        t_video_watch
    SET
        watch_end_at = CURRENT_TIMESTAMP,
        updated_at = CURRENT_TIMESTAMP
    FROM
        latest_active
    WHERE
        t_video_watch.t_video_watch_id = latest_active.t_video_watch_id
        AND latest_active.m_video_id != (SELECT m_video_id FROM resolved_video)
    RETURNING
        t_video_watch.t_video_watch_id
),
update_same AS (
    -- 同じ動画ならポジションを更新
    UPDATE
        t_video_watch
    SET
        watch_position_seconds = $3,
        updated_at = CURRENT_TIMESTAMP
    FROM
        latest_active
    WHERE
        t_video_watch.t_video_watch_id = latest_active.t_video_watch_id
        AND latest_active.m_video_id = (SELECT m_video_id FROM resolved_video)
    RETURNING
        t_video_watch.t_video_watch_id
),
do_insert AS (
    -- update_same が空 = 同じ動画のアクティブセッションがない -> 新規INSERT
    INSERT INTO
        t_video_watch (
            m_user_id,
            m_video_id,
            public_id,
            watch_start_at,
            watch_end_at,
            watch_position_seconds
        )
    SELECT
        (SELECT m_user_id FROM resolved_user),
        (SELECT m_video_id FROM resolved_video),
        $4,
        $5,
        $6,
        $3
    WHERE
        NOT EXISTS (SELECT 1 FROM update_same)
    RETURNING
        t_video_watch_id
)
SELECT 1
`

type UpsertWatchHeartbeatParams struct {
	UserPublicID         uuid.UUID
	VideoPublicID        uuid.UUID
	WatchPositionSeconds int
	PublicID             uuid.UUID
	WatchStartAt         time.Time
	WatchEndAt           time.Time
}

func (q *Queries) UpsertWatchHeartbeat(ctx context.Context, arg UpsertWatchHeartbeatParams) error {
	_, err := q.db.Exec(ctx, upsertWatchHeartbeat,
		arg.UserPublicID,
		arg.VideoPublicID,
		arg.WatchPositionSeconds,
		arg.PublicID,
		arg.WatchStartAt,
		arg.WatchEndAt,
	)
	return err
}
