// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closeStaleWatchSessions = `-- name: CloseStaleWatchSessions :exec
UPDATE
    t_video_watch
SET
    watch_end_at = t_video_watch.updated_at,
    updated_at = CURRENT_TIMESTAMP
WHERE
    m_user_id = (SELECT m_user_id FROM m_user WHERE m_user.public_id = $1 LIMIT 1)
    AND watch_end_at > CURRENT_TIMESTAMP
    AND t_video_watch.updated_at < CURRENT_TIMESTAMP - INTERVAL '2 minutes'
`

func (q *Queries) CloseStaleWatchSessions(ctx context.Context, userPublicID uuid.UUID) error {
	_, err := q.db.Exec(ctx, closeStaleWatchSessions, userPublicID)
	return err
}

const getDailyWatchSummary = `-- name: GetDailyWatchSummary :one
SELECT
    (
        SELECT
            m_user.daily_screen_time_seconds
        FROM
            m_user
        WHERE
            m_user.public_id = $1
    )::int AS daily_limit_seconds,
    COALESCE(
        EXTRACT(
            EPOCH
            FROM
                SUM(
                    LEAST(t_video_watch.watch_end_at, CURRENT_TIMESTAMP) - t_video_watch.watch_start_at
                )
        )::bigint,
        0
    )::int AS today_watch_total
FROM
    t_video_watch
WHERE
    t_video_watch.m_user_id = (
        SELECT
            m_user.m_user_id
        FROM
            m_user
        WHERE
            m_user.public_id = $1
        LIMIT
            1
    )
    AND $2 <= t_video_watch.watch_start_at
    AND t_video_watch.watch_start_at < $2 + INTERVAL '1 day'
`

type GetDailyWatchSummaryParams struct {
	PublicID   uuid.UUID
	TodayStart time.Time
}

type GetDailyWatchSummaryRow struct {
	DailyLimitSeconds int
	TodayWatchTotal   int
}

// m_user.public_idから、そのユーザーが今日視聴していた合計時間(seconds)と設定している制限時間を返す。
// その日に一本も動画を視聴していない場合は0を返します。
func (q *Queries) GetDailyWatchSummary(ctx context.Context, arg GetDailyWatchSummaryParams) (GetDailyWatchSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDailyWatchSummary, arg.PublicID, arg.TodayStart)
	var i GetDailyWatchSummaryRow
	err := row.Scan(&i.DailyLimitSeconds, &i.TodayWatchTotal)
	return i, err
}

const getLastHeartbeatForUpdate = `-- name: GetLastHeartbeatForUpdate :one
SELECT
    (
        SELECT
            m_video.public_id
        FROM
            m_video
        WHERE
            m_video.m_video_id = t_video_watch.m_video_id
        LIMIT 1
    ) AS video_id,
    (
        SELECT
            m_video.external_length_seconds
        FROM
            m_video
        WHERE
            m_video.m_video_id = t_video_watch.m_video_id
        LIMIT 1
    ) AS video_length,
    t_video_watch.updated_at,
    t_video_watch.public_id,
    t_video_watch.watch_start_at,
    t_video_watch.watch_end_at,
    t_video_watch.watch_position_seconds,
    t_video_watch.t_video_watch_id
FROM
    t_video_watch
WHERE
    m_user_id = (
        SELECT
            m_user_id
        FROM
            m_user
        WHERE
            m_user.public_id = $1
        LIMIT
            1
    )
    AND watch_end_at > CURRENT_TIMESTAMP
LIMIT 1
FOR UPDATE
`

type GetLastHeartbeatForUpdateRow struct {
	VideoID              uuid.UUID
	VideoLength          int
	UpdatedAt            time.Time
	PublicID             uuid.UUID
	WatchStartAt         time.Time
	WatchEndAt           time.Time
	WatchPositionSeconds int
	TVideoWatchID        int64
}

func (q *Queries) GetLastHeartbeatForUpdate(ctx context.Context, userPublicID uuid.UUID) (GetLastHeartbeatForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getLastHeartbeatForUpdate, userPublicID)
	var i GetLastHeartbeatForUpdateRow
	err := row.Scan(
		&i.VideoID,
		&i.VideoLength,
		&i.UpdatedAt,
		&i.PublicID,
		&i.WatchStartAt,
		&i.WatchEndAt,
		&i.WatchPositionSeconds,
		&i.TVideoWatchID,
	)
	return i, err
}

const getLatestMonthlyVideoWatchSummary = `-- name: GetLatestMonthlyVideoWatchSummary :one
SELECT
    s.ai_summary_title,
    s.ai_summary_description,
    s.created_at
FROM
    s_monthly_video_watch s
WHERE
    s.m_user_id = (SELECT u.m_user_id FROM m_user u WHERE u.public_id = $1 LIMIT 1)
ORDER BY
    s.target_month DESC
LIMIT 1
`

type GetLatestMonthlyVideoWatchSummaryRow struct {
	AiSummaryTitle       string
	AiSummaryDescription string
	CreatedAt            time.Time
}

func (q *Queries) GetLatestMonthlyVideoWatchSummary(ctx context.Context, userID uuid.UUID) (GetLatestMonthlyVideoWatchSummaryRow, error) {
	row := q.db.QueryRow(ctx, getLatestMonthlyVideoWatchSummary, userID)
	var i GetLatestMonthlyVideoWatchSummaryRow
	err := row.Scan(&i.AiSummaryTitle, &i.AiSummaryDescription, &i.CreatedAt)
	return i, err
}

const insertHeartbeat = `-- name: InsertHeartbeat :exec
INSERT INTO
    t_video_watch (
        m_user_id,
        m_video_id,
        public_id,
        watch_start_at,
        watch_end_at,
        watch_position_seconds
    )
VALUES (
    (SELECT m_user.m_user_id FROM m_user WHERE m_user.public_id = $1 LIMIT 1),
    (SELECT m_video.m_video_id FROM m_video WHERE m_video.public_id = $2 LIMIT 1),
    $3,
    $4,
    $5,
    $6
)
`

type InsertHeartbeatParams struct {
	UserPublicID         uuid.UUID
	VideoPublicID        uuid.UUID
	PublicID             uuid.UUID
	WatchStartAt         time.Time
	WatchEndAt           time.Time
	WatchPositionSeconds int
}

func (q *Queries) InsertHeartbeat(ctx context.Context, arg InsertHeartbeatParams) error {
	_, err := q.db.Exec(ctx, insertHeartbeat,
		arg.UserPublicID,
		arg.VideoPublicID,
		arg.PublicID,
		arg.WatchStartAt,
		arg.WatchEndAt,
		arg.WatchPositionSeconds,
	)
	return err
}

const listDailyWatchStatsByRange = `-- name: ListDailyWatchStatsByRange :many
SELECT
    DATE(video_watch.watch_start_at + make_interval(secs => $1::int)) AS watch_date,
    COUNT(DISTINCT video_watch.m_video_id) AS video_count,
    EXTRACT(EPOCH FROM SUM(video_watch.watch_end_at - video_watch.watch_start_at))::bigint AS watch_sum
FROM
    t_video_watch video_watch
WHERE
    video_watch.m_user_id = (
        SELECT
            u.m_user_id
        FROM
            m_user u
        WHERE
            u.public_id = $2
        LIMIT
            1
    )
    AND video_watch.watch_start_at BETWEEN $3 AND $4
    AND video_watch.watch_end_at <= CURRENT_TIMESTAMP
GROUP BY
    DATE(video_watch.watch_start_at + make_interval(secs => $1::int))
`

type ListDailyWatchStatsByRangeParams struct {
	TzOffset  int
	UserID    uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

type ListDailyWatchStatsByRangeRow struct {
	WatchDate  time.Time
	VideoCount int64
	WatchSum   int64
}

func (q *Queries) ListDailyWatchStatsByRange(ctx context.Context, arg ListDailyWatchStatsByRangeParams) ([]ListDailyWatchStatsByRangeRow, error) {
	rows, err := q.db.Query(ctx, listDailyWatchStatsByRange,
		arg.TzOffset,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyWatchStatsByRangeRow
	for rows.Next() {
		var i ListDailyWatchStatsByRangeRow
		if err := rows.Scan(&i.WatchDate, &i.VideoCount, &i.WatchSum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchHistory = `-- name: ListWatchHistory :many
SELECT
    t_video_watch.public_id AS watch_id,
    m_video.public_id AS video_id,
    m_video.external_title AS external_video_title,
    m_video.external_thumbnail_url AS external_video_thumbnail_url,
    m_video.external_length_seconds AS external_video_length_seconds,
    t_video_watch.watch_position_seconds,
    t_video_watch.watch_start_at AS watched_at,
    m_channel.public_id AS channel_id,
    m_channel.external_display_name AS external_channel_display_name,
    m_channel.external_icon_url AS external_channel_icon_url
FROM
    t_video_watch
    INNER JOIN m_video ON m_video.m_video_id = t_video_watch.m_video_id
    INNER JOIN m_channel ON m_channel.m_channel_id = m_video.m_channel_id
WHERE
    t_video_watch.m_user_id = (
        SELECT
            m_user.m_user_id
        FROM
            m_user
        WHERE
            m_user.public_id = $1
        LIMIT
            1
    )
    AND (
        $2::uuid IS NULL
        OR t_video_watch.public_id < $2::uuid
    )
ORDER BY
    t_video_watch.public_id DESC
LIMIT
    $3
`

type ListWatchHistoryParams struct {
	UserID     uuid.UUID
	Cursor     *uuid.UUID
	QueryLimit int32
}

type ListWatchHistoryRow struct {
	WatchID                    uuid.UUID
	VideoID                    uuid.UUID
	ExternalVideoTitle         string
	ExternalVideoThumbnailUrl  string
	ExternalVideoLengthSeconds int
	WatchPositionSeconds       int
	WatchedAt                  time.Time
	ChannelID                  uuid.UUID
	ExternalChannelDisplayName string
	ExternalChannelIconUrl     string
}

func (q *Queries) ListWatchHistory(ctx context.Context, arg ListWatchHistoryParams) ([]ListWatchHistoryRow, error) {
	rows, err := q.db.Query(ctx, listWatchHistory, arg.UserID, arg.Cursor, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWatchHistoryRow
	for rows.Next() {
		var i ListWatchHistoryRow
		if err := rows.Scan(
			&i.WatchID,
			&i.VideoID,
			&i.ExternalVideoTitle,
			&i.ExternalVideoThumbnailUrl,
			&i.ExternalVideoLengthSeconds,
			&i.WatchPositionSeconds,
			&i.WatchedAt,
			&i.ChannelID,
			&i.ExternalChannelDisplayName,
			&i.ExternalChannelIconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVideoWatched = `-- name: MarkVideoWatched :exec
INSERT INTO
    t_video_watched (m_user_id, m_video_id)
SELECT
    (SELECT m_user.m_user_id FROM m_user WHERE m_user.public_id = $1 LIMIT 1),
    (SELECT m_video.m_video_id FROM m_video WHERE m_video.public_id = $2 LIMIT 1)
ON CONFLICT (m_user_id, m_video_id) DO NOTHING
`

type MarkVideoWatchedParams struct {
	UserPublicID  uuid.UUID
	VideoPublicID uuid.UUID
}

func (q *Queries) MarkVideoWatched(ctx context.Context, arg MarkVideoWatchedParams) error {
	_, err := q.db.Exec(ctx, markVideoWatched, arg.UserPublicID, arg.VideoPublicID)
	return err
}

const unmarkVideoWatched = `-- name: UnmarkVideoWatched :exec
DELETE FROM
    t_video_watched
WHERE
    m_user_id = (SELECT m_user.m_user_id FROM m_user WHERE m_user.public_id = $1 LIMIT 1)
    AND m_video_id = (SELECT m_video.m_video_id FROM m_video WHERE m_video.public_id = $2 LIMIT 1)
`

type UnmarkVideoWatchedParams struct {
	UserPublicID  uuid.UUID
	VideoPublicID uuid.UUID
}

func (q *Queries) UnmarkVideoWatched(ctx context.Context, arg UnmarkVideoWatchedParams) error {
	_, err := q.db.Exec(ctx, unmarkVideoWatched, arg.UserPublicID, arg.VideoPublicID)
	return err
}

const updateHeartbeat = `-- name: UpdateHeartbeat :exec
UPDATE
    t_video_watch
SET
    watch_position_seconds = $1,
    watch_start_at = $2,
    watch_end_at = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE
    t_video_watch.t_video_watch_id = $4
`

type UpdateHeartbeatParams struct {
	WatchPositionSeconds int
	WatchStartAt         time.Time
	WatchEndAt           time.Time
	TVideoWatchID        int64
}

func (q *Queries) UpdateHeartbeat(ctx context.Context, arg UpdateHeartbeatParams) error {
	_, err := q.db.Exec(ctx, updateHeartbeat,
		arg.WatchPositionSeconds,
		arg.WatchStartAt,
		arg.WatchEndAt,
		arg.TVideoWatchID,
	)
	return err
}
