// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: misc.sql

package sqlc

import (
	"context"
)

const releaseAdvisoryLock = `-- name: ReleaseAdvisoryLock :one
SELECT pg_advisory_unlock($1::bigint) AS released
`

// セッションレベルのアドバイザリロックを解除
func (q *Queries) ReleaseAdvisoryLock(ctx context.Context, lockKey int64) (bool, error) {
	row := q.db.QueryRow(ctx, releaseAdvisoryLock, lockKey)
	var released bool
	err := row.Scan(&released)
	return released, err
}

const tryAcquireAdvisoryLock = `-- name: TryAcquireAdvisoryLock :one
SELECT pg_try_advisory_lock($1::bigint) AS acquired
`

// セッションレベルのロック（ノンブロッキング）
func (q *Queries) TryAcquireAdvisoryLock(ctx context.Context, lockKey int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryAcquireAdvisoryLock, lockKey)
	var acquired bool
	err := row.Scan(&acquired)
	return acquired, err
}

const tryAcquireAdvisoryXactLock = `-- name: TryAcquireAdvisoryXactLock :one
SELECT pg_try_advisory_xact_lock($1::bigint) AS acquired
`

// トランザクションレベルのロック（ノンブロッキング）
func (q *Queries) TryAcquireAdvisoryXactLock(ctx context.Context, lockKey int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryAcquireAdvisoryXactLock, lockKey)
	var acquired bool
	err := row.Scan(&acquired)
	return acquired, err
}
