// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/brqnko/anti-yt/backend/internal/core/database_d/dbtype"
	"github.com/google/uuid"
)

type HUser struct {
	HUserID                int64
	MUserAuthorizationID   int64
	DisplayName            string
	LanguageCode           string
	DailyScreenTimeSeconds int
	JoinedAt               time.Time
	LeftAt                 time.Time
	LeaveReasonCode        int
	CreatedAt              time.Time
	UpdatedAt              time.Time
	PublicID               uuid.UUID
}

type MChannel struct {
	MChannelID                int64
	ExternalID                string
	ExternalDisplayName       string
	ExternalCustomID          string
	ExternalIconUrl           string
	ExternalDescription       string
	ExternalSubscribersCount  int64
	ExternalCreatedAt         time.Time
	FetchedAt                 time.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	PublicID                  uuid.UUID
	RssFetchedAt              time.Time
	ExternalUploadsPlaylistID string
	BulkFetchedAt             time.Time
	LastSeenAt                time.Time
}

type MPlaylist struct {
	MPlaylistID         int64
	MUserID             int64
	VisibilityCode      int
	PlaylistTitle       string
	PlaylistCode        int
	VideoCount          int
	CreatedAt           time.Time
	UpdatedAt           time.Time
	PublicID            uuid.UUID
	PlaylistDescription string
	RegisteredAt        time.Time
	MChannelID          int64
}

type MPlaylistVideo struct {
	MPlaylistVideoID int64
	MPlaylistID      int64
	MVideoID         int64
	PlaylistPosition int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type MRefreshToken struct {
	MRefreshTokenID      int64
	MUserAuthorizationID int64
	TokenHash            string
	Generation           int
	IpAddress            string
	DeviceFingerprint    string
	UserAgent            string
	CountryCode          string
	CityName             string
	BrowserName          string
	DeviceType           string
	ExpiresAt            time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	PublicID             uuid.UUID
	AccessTokenJti       uuid.UUID
	ActivatedAt          time.Time
	LastLoggedInAt       time.Time
}

type MUser struct {
	MUserID                int64
	MUserAuthorizationID   int64
	DisplayName            string
	LanguageCode           string
	DailyScreenTimeSeconds int
	JoinedAt               time.Time
	CreatedAt              time.Time
	UpdatedAt              time.Time
	PublicID               uuid.UUID
	RecentPlaylistIds      []int64
}

type MUserAuthorization struct {
	MUserAuthorizationID int64
	Issuer               string
	Sub                  string
	LastLoggedInAt       time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	PublicID             uuid.UUID
}

type MUserScreenTimeRange struct {
	MUserScreenTimeRangeID int64
	MUserID                int64
	ScreenTimeRangeStart   dbtype.Seconds
	ScreenTimeRangeEnd     dbtype.Seconds
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type MUserSubscribingChannel struct {
	MUserSubscribingChannelID int64
	MUserID                   int64
	MChannelID                int64
	SubscribedAt              time.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

type MValuableChannel struct {
	MValuableChannelID  int64
	MChannelID          int64
	CategoryCode        int
	ValuableDescription string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type MVideo struct {
	MVideoID              int64
	MChannelID            int64
	ExternalID            string
	ExternalTitle         string
	ExternalDescription   string
	FetchedAt             time.Time
	CreatedAt             time.Time
	UpdatedAt             time.Time
	PublicID              uuid.UUID
	ExternalCreatedAt     time.Time
	ExternalThumbnailUrl  string
	ExternalLengthSeconds int
}

type SMonthlyVideoWatch struct {
	SMonthlyVideoWatchID int64
	MUserID              int64
	AiSummaryTitle       string
	AiSummaryDescription string
	AiModel              string
	GeneratedAt          time.Time
	TargetMonth          time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	PublicID             uuid.UUID
}

type TVideoWatch struct {
	TVideoWatchID        int64
	MUserID              int64
	MVideoID             int64
	WatchStartAt         time.Time
	WatchEndAt           time.Time
	WatchPositionSeconds int
	CreatedAt            time.Time
	UpdatedAt            time.Time
	PublicID             uuid.UUID
}

type TVideoWatched struct {
	TVideoWatchedID int64
	MUserID         int64
	MVideoID        int64
}
