// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlist.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type BulkInsertPlaylistVideosParams struct {
	MPlaylistID      int64
	MVideoID         int64
	PlaylistPosition int64
}

const copyPlaylistVideos = `-- name: CopyPlaylistVideos :one
WITH inserted AS (
    INSERT INTO
        m_playlist_video (m_playlist_id, m_video_id, playlist_position)
    SELECT
        $1, pv.m_video_id, pv.playlist_position
    FROM
        m_playlist_video pv
    WHERE
        pv.m_playlist_id = (
            SELECT
                p.m_playlist_id
            FROM
                m_playlist p
            WHERE
                (
                    p.m_user_id = (
                        SELECT
                            u.m_user_id
                        FROM
                            m_user u
                        WHERE
                            u.public_id = $2
                        LIMIT
                            1
                    )
                    OR p.visibility_code = 1
                )
                AND p.public_id = $3
            LIMIT
                1
        )
    RETURNING 1
)
SELECT COUNT(*)::int AS copied_count FROM inserted
`

type CopyPlaylistVideosParams struct {
	DestPlaylistID   int64
	UserID           uuid.UUID
	SourcePlaylistID uuid.UUID
}

func (q *Queries) CopyPlaylistVideos(ctx context.Context, arg CopyPlaylistVideosParams) (int, error) {
	row := q.db.QueryRow(ctx, copyPlaylistVideos, arg.DestPlaylistID, arg.UserID, arg.SourcePlaylistID)
	var copied_count int
	err := row.Scan(&copied_count)
	return copied_count, err
}

const deletePlaylist = `-- name: DeletePlaylist :one
WITH deleted AS (
    DELETE FROM
        m_playlist playlist -- NOTE: cascadeつけてるのでm_playlist_videoは勝手に消えてくれる
    WHERE
        playlist.m_user_id = (
            SELECT
                u.m_user_id
            FROM
                m_user u
            WHERE
                u.public_id = $1
            LIMIT
                1
        )
        AND playlist.public_id = $2
        AND playlist.playlist_code = 0
    RETURNING
        playlist.public_id
)
SELECT
    deleted.public_id
FROM
    deleted
`

type DeletePlaylistParams struct {
	UserID     uuid.UUID
	PlaylistID uuid.UUID
}

func (q *Queries) DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deletePlaylist, arg.UserID, arg.PlaylistID)
	var public_id uuid.UUID
	err := row.Scan(&public_id)
	return public_id, err
}

const deletePlaylistVideo = `-- name: DeletePlaylistVideo :one
DELETE FROM
    m_playlist_video playlist_video
WHERE
    playlist_video.m_playlist_id = (
        SELECT
            playlist.m_playlist_id
        FROM
            m_playlist playlist
        WHERE
            playlist.m_user_id = (
                SELECT
                    u.m_user_id
                FROM
                    m_user u
                WHERE
                    u.public_id = $1
                LIMIT
                    1
            )
            AND playlist.public_id = $2
        LIMIT
            1
    )
    AND playlist_video.m_video_id = (
        SELECT
            video.m_video_id
        FROM
            m_video video
        WHERE
            video.public_id = $3
        LIMIT
            1
    )
RETURNING
    playlist_video.m_playlist_video_id
`

type DeletePlaylistVideoParams struct {
	UserID     uuid.UUID
	PlaylistID uuid.UUID
	VideoID    uuid.UUID
}

func (q *Queries) DeletePlaylistVideo(ctx context.Context, arg DeletePlaylistVideoParams) (int64, error) {
	row := q.db.QueryRow(ctx, deletePlaylistVideo, arg.UserID, arg.PlaylistID, arg.VideoID)
	var m_playlist_video_id int64
	err := row.Scan(&m_playlist_video_id)
	return m_playlist_video_id, err
}

const getPlaylistForUpdate = `-- name: GetPlaylistForUpdate :one
SELECT
    playlist.public_id,
    playlist.playlist_title,
    playlist.playlist_description,
    playlist.visibility_code,
    playlist.playlist_code,
    playlist.video_count,
    playlist.registered_at
FROM
    m_playlist playlist
WHERE
    playlist.m_user_id = (
        SELECT
            u.m_user_id
        FROM
            m_user u
        WHERE
            u.public_id = $1
        LIMIT
            1
    )
    AND playlist.public_id = $2
LIMIT
    1
FOR UPDATE
`

type GetPlaylistForUpdateParams struct {
	UserID     uuid.UUID
	PlaylistID uuid.UUID
}

type GetPlaylistForUpdateRow struct {
	PublicID            uuid.UUID
	PlaylistTitle       string
	PlaylistDescription string
	VisibilityCode      int
	PlaylistCode        int
	VideoCount          int
	RegisteredAt        time.Time
}

func (q *Queries) GetPlaylistForUpdate(ctx context.Context, arg GetPlaylistForUpdateParams) (GetPlaylistForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPlaylistForUpdate, arg.UserID, arg.PlaylistID)
	var i GetPlaylistForUpdateRow
	err := row.Scan(
		&i.PublicID,
		&i.PlaylistTitle,
		&i.PlaylistDescription,
		&i.VisibilityCode,
		&i.PlaylistCode,
		&i.VideoCount,
		&i.RegisteredAt,
	)
	return i, err
}

const getPlaylistWithThumbnail = `-- name: GetPlaylistWithThumbnail :one
SELECT
    playlist.public_id,
    playlist.playlist_title,
    playlist.playlist_description,
    playlist.visibility_code,
    playlist.playlist_code,
    playlist.registered_at,
    playlist.updated_at,
    playlist.video_count,
    COALESCE((
        SELECT
            video.external_thumbnail_url
        FROM
            m_playlist_video playlist_video
            INNER JOIN m_video video ON playlist_video.m_video_id = video.m_video_id
        WHERE
            playlist_video.m_playlist_id = playlist.m_playlist_id
        LIMIT
            1
    ), '')::varchar AS top_thumbnail
FROM
    m_playlist playlist
WHERE
    (
        playlist.m_user_id = (
            SELECT
                u.m_user_id
            FROM
                m_user u
            WHERE
                u.public_id = $1
            LIMIT
                1
        )
        OR playlist.m_channel_id != 0
    )
    AND playlist.public_id = $2
`

type GetPlaylistWithThumbnailParams struct {
	UserID     uuid.UUID
	PlaylistID uuid.UUID
}

type GetPlaylistWithThumbnailRow struct {
	PublicID            uuid.UUID
	PlaylistTitle       string
	PlaylistDescription string
	VisibilityCode      int
	PlaylistCode        int
	RegisteredAt        time.Time
	UpdatedAt           time.Time
	VideoCount          int
	TopThumbnail        string
}

func (q *Queries) GetPlaylistWithThumbnail(ctx context.Context, arg GetPlaylistWithThumbnailParams) (GetPlaylistWithThumbnailRow, error) {
	row := q.db.QueryRow(ctx, getPlaylistWithThumbnail, arg.UserID, arg.PlaylistID)
	var i GetPlaylistWithThumbnailRow
	err := row.Scan(
		&i.PublicID,
		&i.PlaylistTitle,
		&i.PlaylistDescription,
		&i.VisibilityCode,
		&i.PlaylistCode,
		&i.RegisteredAt,
		&i.UpdatedAt,
		&i.VideoCount,
		&i.TopThumbnail,
	)
	return i, err
}

const getWatchLaterForUpdate = `-- name: GetWatchLaterForUpdate :one
SELECT
    playlist.public_id,
    playlist.playlist_title,
    playlist.playlist_description,
    playlist.visibility_code,
    playlist.playlist_code,
    playlist.video_count,
    playlist.registered_at
FROM m_playlist playlist
WHERE
    playlist.m_user_id = (SELECT m_user.m_user_id FROM m_user WHERE m_user.public_id = $1 LIMIT 1)
    AND playlist.playlist_code = 2
LIMIT 1
FOR UPDATE
`

type GetWatchLaterForUpdateRow struct {
	PublicID            uuid.UUID
	PlaylistTitle       string
	PlaylistDescription string
	VisibilityCode      int
	PlaylistCode        int
	VideoCount          int
	RegisteredAt        time.Time
}

func (q *Queries) GetWatchLaterForUpdate(ctx context.Context, userID uuid.UUID) (GetWatchLaterForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getWatchLaterForUpdate, userID)
	var i GetWatchLaterForUpdateRow
	err := row.Scan(
		&i.PublicID,
		&i.PlaylistTitle,
		&i.PlaylistDescription,
		&i.VisibilityCode,
		&i.PlaylistCode,
		&i.VideoCount,
		&i.RegisteredAt,
	)
	return i, err
}

const getWatchLaterPlaylist = `-- name: GetWatchLaterPlaylist :one
SELECT
    playlist.public_id,
    playlist.playlist_title,
    playlist.registered_at,
    playlist.video_count,
    COALESCE((
        SELECT
            video.external_thumbnail_url
        FROM
            m_playlist_video playlist_video
            INNER JOIN m_video video ON playlist_video.m_video_id = video.m_video_id
        WHERE
            playlist_video.m_playlist_id = playlist.m_playlist_id
        LIMIT
            1
    ), '')::varchar AS top_thumbnail
FROM
    m_playlist playlist
WHERE
    playlist.m_user_id = (
        SELECT
            u.m_user_id
        FROM
            m_user u
        WHERE
            u.public_id = $1
        LIMIT
            1
    )
    AND playlist.playlist_code = 2
LIMIT
    1
`

type GetWatchLaterPlaylistRow struct {
	PublicID      uuid.UUID
	PlaylistTitle string
	RegisteredAt  time.Time
	VideoCount    int
	TopThumbnail  string
}

func (q *Queries) GetWatchLaterPlaylist(ctx context.Context, userID uuid.UUID) (GetWatchLaterPlaylistRow, error) {
	row := q.db.QueryRow(ctx, getWatchLaterPlaylist, userID)
	var i GetWatchLaterPlaylistRow
	err := row.Scan(
		&i.PublicID,
		&i.PlaylistTitle,
		&i.RegisteredAt,
		&i.VideoCount,
		&i.TopThumbnail,
	)
	return i, err
}

const insertPlaylistVideo = `-- name: InsertPlaylistVideo :exec
INSERT INTO
    m_playlist_video (
        m_playlist_id,
        m_video_id,
        playlist_position
    )
SELECT
    (
        SELECT
            m_playlist.m_playlist_id
        FROM
            m_playlist
        WHERE
            m_playlist.m_user_id = (
                SELECT
                    m_user.m_user_id
                FROM
                    m_user
                WHERE
                    m_user.public_id = $1
                LIMIT
                    1
            )
            AND m_playlist.public_id = $2
        LIMIT
            1
    ),
    (
        SELECT
            video.m_video_id
        FROM
            m_video video
        WHERE
            video.public_id = $3
        LIMIT
            1
    ),
    COALESCE(
        (
            SELECT
                MAX(m_playlist_video.playlist_position) + 1048576 -- NOTE: 2^20
            FROM
                m_playlist_video
            WHERE
                m_playlist_video.m_playlist_id = (
                    SELECT
                        m_playlist.m_playlist_id
                    FROM
                        m_playlist
                    WHERE
                        m_playlist.m_user_id = (
                            SELECT
                                m_user.m_user_id
                            FROM
                                m_user
                            WHERE
                                m_user.public_id = $1
                            LIMIT
                                1
                        )
                        AND m_playlist.public_id = $2
                    LIMIT
                        1
                )
        ),
        0
    )
`

type InsertPlaylistVideoParams struct {
	UserID     uuid.UUID
	PlaylistID uuid.UUID
	VideoID    uuid.UUID
}

func (q *Queries) InsertPlaylistVideo(ctx context.Context, arg InsertPlaylistVideoParams) error {
	_, err := q.db.Exec(ctx, insertPlaylistVideo, arg.UserID, arg.PlaylistID, arg.VideoID)
	return err
}

const insertWatchLater = `-- name: InsertWatchLater :exec
INSERT INTO
    m_playlist_video (
        m_playlist_id,
        m_video_id,
        playlist_position
    )
SELECT
    m_playlist.m_playlist_id,
    (SELECT m_video.m_video_id FROM m_video WHERE m_video.public_id = $1 LIMIT 1),
    COALESCE(
            (
                SELECT
                    MAX(m_playlist_video.playlist_position) + 1048576 -- NOTE: 2^20
                FROM
                    m_playlist_video
                WHERE
                    m_playlist_video.m_playlist_id = m_playlist.m_playlist_id
            ),
            0
    )
FROM m_playlist
WHERE
    m_playlist.public_id = $2
    AND NOT EXISTS(
        SELECT 1 FROM m_playlist_video
        WHERE
            m_playlist_video.m_playlist_id = m_playlist.m_playlist_id
            AND m_playlist_video.m_video_id = (SELECT m_video.m_video_id FROM m_video WHERE m_video.public_id = $1 LIMIT 1))
`

type InsertWatchLaterParams struct {
	VideoID    uuid.UUID
	PlaylistID uuid.UUID
}

func (q *Queries) InsertWatchLater(ctx context.Context, arg InsertWatchLaterParams) error {
	_, err := q.db.Exec(ctx, insertWatchLater, arg.VideoID, arg.PlaylistID)
	return err
}

const listChannelPlaylists = `-- name: ListChannelPlaylists :many
SELECT
    playlist.public_id,
    playlist.playlist_title,
    playlist.playlist_description,
    playlist.visibility_code,
    playlist.playlist_code,
    playlist.registered_at,
    playlist.updated_at,
    playlist.video_count,
    COALESCE((
        SELECT
            video.external_thumbnail_url
        FROM
            m_playlist_video playlist_video
            INNER JOIN m_video video ON playlist_video.m_video_id = video.m_video_id
        WHERE
            playlist_video.m_playlist_id = playlist.m_playlist_id
        LIMIT
            1
    ), '')::varchar AS top_thumbnail
FROM
    m_playlist playlist
WHERE
    playlist.m_channel_id = (
        SELECT
            ch.m_channel_id
        FROM
            m_channel ch
        WHERE
            ch.public_id = $1
        LIMIT
            1
    )
    AND (
        $2::uuid IS NULL
        OR playlist.public_id < $2::uuid
    )
ORDER BY
    playlist.m_channel_id, playlist.public_id DESC
LIMIT
    $3
`

type ListChannelPlaylistsParams struct {
	ChannelID  uuid.UUID
	Cursor     *uuid.UUID
	QueryLimit int32
}

type ListChannelPlaylistsRow struct {
	PublicID            uuid.UUID
	PlaylistTitle       string
	PlaylistDescription string
	VisibilityCode      int
	PlaylistCode        int
	RegisteredAt        time.Time
	UpdatedAt           time.Time
	VideoCount          int
	TopThumbnail        string
}

func (q *Queries) ListChannelPlaylists(ctx context.Context, arg ListChannelPlaylistsParams) ([]ListChannelPlaylistsRow, error) {
	rows, err := q.db.Query(ctx, listChannelPlaylists, arg.ChannelID, arg.Cursor, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelPlaylistsRow
	for rows.Next() {
		var i ListChannelPlaylistsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.PlaylistTitle,
			&i.PlaylistDescription,
			&i.VisibilityCode,
			&i.PlaylistCode,
			&i.RegisteredAt,
			&i.UpdatedAt,
			&i.VideoCount,
			&i.TopThumbnail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistVideos = `-- name: ListPlaylistVideos :many
SELECT
    video.public_id,
    video.external_thumbnail_url,
    video.external_title,
    video.external_created_at,
    video.external_length_seconds,
    COALESCE((
        SELECT
            t_video_watch.watch_position_seconds
        FROM
            t_video_watch
        WHERE
            t_video_watch.m_user_id = (
                SELECT
                    m_user.m_user_id
                FROM
                    m_user
                WHERE
                    m_user.public_id = $1
                LIMIT
                    1
            )
            AND t_video_watch.m_video_id = video.m_video_id
        ORDER BY
            t_video_watch.m_user_id,
            t_video_watch.m_video_id,
            t_video_watch.watch_start_at DESC
        LIMIT
            1
    ), 0)::int AS last_watch_seconds,
    channel.public_id AS channel_id,
    channel.external_icon_url AS external_channel_icon_url,
    channel.external_display_name AS external_channel_displayname
FROM
    m_playlist_video playlist_video
    INNER JOIN m_video video ON video.m_video_id = playlist_video.m_video_id
    INNER JOIN m_channel channel ON channel.m_channel_id = video.m_channel_id
WHERE
    playlist_video.m_playlist_id = (
        SELECT
            playlist.m_playlist_id
        FROM
            m_playlist playlist
        WHERE
            (
                playlist.m_user_id = (
                    SELECT
                        u.m_user_id
                    FROM
                        m_user u
                    WHERE
                        u.public_id = $1
                    LIMIT
                        1
                )
                OR playlist.visibility_code = 1
            )
            AND playlist.public_id = $2
        LIMIT
            1
    )
    AND (
        $3::uuid IS NULL
        OR playlist_video.playlist_position > (
            SELECT
                pv.playlist_position
            FROM
                m_playlist_video pv
                INNER JOIN m_video v ON v.m_video_id = pv.m_video_id
            WHERE
                v.public_id = $3::uuid
                AND pv.m_playlist_id = (
                    SELECT
                        playlist.m_playlist_id
                    FROM
                        m_playlist playlist
                    WHERE
                        (
                            playlist.m_user_id = (
                                SELECT
                                    u.m_user_id
                                FROM
                                    m_user u
                                WHERE
                                    u.public_id = $1
                                LIMIT
                                    1
                            )
                            OR playlist.m_channel_id != 0
                        )
                        AND playlist.public_id = $2
                    LIMIT
                        1
                )
            LIMIT
                1
        )
    )
ORDER BY
    playlist_video.m_playlist_id, playlist_video.playlist_position
LIMIT
    $4
`

type ListPlaylistVideosParams struct {
	UserID     uuid.UUID
	PlaylistID uuid.UUID
	Cursor     *uuid.UUID
	QueryLimit int32
}

type ListPlaylistVideosRow struct {
	PublicID                   uuid.UUID
	ExternalThumbnailUrl       string
	ExternalTitle              string
	ExternalCreatedAt          time.Time
	ExternalLengthSeconds      int
	LastWatchSeconds           int
	ChannelID                  uuid.UUID
	ExternalChannelIconUrl     string
	ExternalChannelDisplayname string
}

func (q *Queries) ListPlaylistVideos(ctx context.Context, arg ListPlaylistVideosParams) ([]ListPlaylistVideosRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistVideos,
		arg.UserID,
		arg.PlaylistID,
		arg.Cursor,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaylistVideosRow
	for rows.Next() {
		var i ListPlaylistVideosRow
		if err := rows.Scan(
			&i.PublicID,
			&i.ExternalThumbnailUrl,
			&i.ExternalTitle,
			&i.ExternalCreatedAt,
			&i.ExternalLengthSeconds,
			&i.LastWatchSeconds,
			&i.ChannelID,
			&i.ExternalChannelIconUrl,
			&i.ExternalChannelDisplayname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPlaylists = `-- name: ListRecentPlaylists :many
SELECT
    playlist.public_id,
    playlist.playlist_title,
    playlist.registered_at,
    playlist.video_count,
    COALESCE((
        SELECT
            video.external_thumbnail_url
        FROM
            m_playlist_video playlist_video
            INNER JOIN m_video video ON playlist_video.m_video_id = video.m_video_id
        WHERE
            playlist_video.m_playlist_id = playlist.m_playlist_id
        LIMIT
            1
    ), '')::varchar AS top_thumbnail
FROM
    m_user u
    INNER JOIN LATERAL UNNEST(u.recent_playlist_ids) WITH ORDINALITY AS t(pid, ord) ON TRUE
    INNER JOIN m_playlist playlist ON playlist.m_playlist_id = t.pid
WHERE
    u.public_id = $1
ORDER BY
    t.ord
`

type ListRecentPlaylistsRow struct {
	PublicID      uuid.UUID
	PlaylistTitle string
	RegisteredAt  time.Time
	VideoCount    int
	TopThumbnail  string
}

func (q *Queries) ListRecentPlaylists(ctx context.Context, userID uuid.UUID) ([]ListRecentPlaylistsRow, error) {
	rows, err := q.db.Query(ctx, listRecentPlaylists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentPlaylistsRow
	for rows.Next() {
		var i ListRecentPlaylistsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.PlaylistTitle,
			&i.RegisteredAt,
			&i.VideoCount,
			&i.TopThumbnail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPlaylists = `-- name: ListUserPlaylists :many
SELECT
    playlist.public_id,
    playlist.playlist_title,
    playlist.playlist_description,
    playlist.visibility_code,
    playlist.playlist_code,
    playlist.registered_at,
    playlist.updated_at,
    playlist.video_count,
    COALESCE((
        SELECT
            video.external_thumbnail_url
        FROM
            m_playlist_video playlist_video
            INNER JOIN m_video video ON playlist_video.m_video_id = video.m_video_id
        WHERE
            playlist_video.m_playlist_id = playlist.m_playlist_id
        LIMIT
            1
    ), '')::varchar AS top_thumbnail
FROM
    m_playlist playlist
WHERE
    playlist.m_user_id = (
        SELECT
            u.m_user_id
        FROM
            m_user u
        WHERE
            u.public_id = $1
        LIMIT
            1
    )
    AND (
        $2::uuid IS NULL
        OR playlist.public_id < $2::uuid
    )
ORDER BY
    playlist.m_user_id, playlist.public_id DESC
LIMIT
    $3
`

type ListUserPlaylistsParams struct {
	UserID     uuid.UUID
	Cursor     *uuid.UUID
	QueryLimit int32
}

type ListUserPlaylistsRow struct {
	PublicID            uuid.UUID
	PlaylistTitle       string
	PlaylistDescription string
	VisibilityCode      int
	PlaylistCode        int
	RegisteredAt        time.Time
	UpdatedAt           time.Time
	VideoCount          int
	TopThumbnail        string
}

func (q *Queries) ListUserPlaylists(ctx context.Context, arg ListUserPlaylistsParams) ([]ListUserPlaylistsRow, error) {
	rows, err := q.db.Query(ctx, listUserPlaylists, arg.UserID, arg.Cursor, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserPlaylistsRow
	for rows.Next() {
		var i ListUserPlaylistsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.PlaylistTitle,
			&i.PlaylistDescription,
			&i.VisibilityCode,
			&i.PlaylistCode,
			&i.RegisteredAt,
			&i.UpdatedAt,
			&i.VideoCount,
			&i.TopThumbnail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pushRecentPlaylistId = `-- name: PushRecentPlaylistId :exec
UPDATE m_user
SET recent_playlist_ids = (
    SELECT COALESCE(array_agg(val), '{}')
    FROM (
             SELECT val
             FROM UNNEST(
                          ARRAY[(SELECT p.m_playlist_id FROM m_playlist p WHERE p.public_id = $1 LIMIT 1)]
            || m_user.recent_playlist_ids
        ) WITH ORDINALITY AS t(val, ord)
             WHERE val IS NOT NULL
             GROUP BY val
             ORDER BY MIN(ord)
                 LIMIT 5
         ) sub
),
    updated_at = CURRENT_TIMESTAMP
WHERE m_user.public_id = $2
`

type PushRecentPlaylistIdParams struct {
	PlaylistPublicID uuid.UUID
	UserPublicID     uuid.UUID
}

// m_user.recent_playlist_idsを更新する。先頭に追加し、重複を除去し、最大5件に制限する。
func (q *Queries) PushRecentPlaylistId(ctx context.Context, arg PushRecentPlaylistIdParams) error {
	_, err := q.db.Exec(ctx, pushRecentPlaylistId, arg.PlaylistPublicID, arg.UserPublicID)
	return err
}

const upsertPlaylist = `-- name: UpsertPlaylist :one
INSERT INTO
    m_playlist (
        m_user_id,
        m_channel_id,
        playlist_title,
        playlist_description,
        visibility_code,
        playlist_code,
        video_count,
        public_id,
        registered_at
    )
VALUES
    (
        (
            SELECT
                m_user.m_user_id
            FROM
                m_user
            WHERE
                m_user.public_id = $1
            LIMIT
                1
        ),
        COALESCE((
            SELECT
                ch.m_channel_id
            FROM
                m_channel ch
            WHERE
                ch.public_id = $2::uuid
            LIMIT
                1
        ), 0),
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9
    )
ON CONFLICT (public_id) DO UPDATE SET
    playlist_title = EXCLUDED.playlist_title,
    playlist_description = EXCLUDED.playlist_description,
    visibility_code = EXCLUDED.visibility_code,
    playlist_code = EXCLUDED.playlist_code,
    video_count = EXCLUDED.video_count,
    registered_at = EXCLUDED.registered_at,
    updated_at = CURRENT_TIMESTAMP
RETURNING
    m_playlist.m_playlist_id
`

type UpsertPlaylistParams struct {
	UserPublicID        uuid.UUID
	ChannelPublicID     *uuid.UUID
	PlaylistTitle       string
	PlaylistDescription string
	VisibilityCode      int
	PlaylistCode        int
	VideoCount          int
	PublicID            uuid.UUID
	RegisteredAt        time.Time
}

func (q *Queries) UpsertPlaylist(ctx context.Context, arg UpsertPlaylistParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertPlaylist,
		arg.UserPublicID,
		arg.ChannelPublicID,
		arg.PlaylistTitle,
		arg.PlaylistDescription,
		arg.VisibilityCode,
		arg.PlaylistCode,
		arg.VideoCount,
		arg.PublicID,
		arg.RegisteredAt,
	)
	var m_playlist_id int64
	err := row.Scan(&m_playlist_id)
	return m_playlist_id, err
}

const upsertSystemPlaylist = `-- name: UpsertSystemPlaylist :one
INSERT INTO
    m_playlist (
        m_user_id,
        m_channel_id,
        playlist_title,
        playlist_description,
        visibility_code,
        playlist_code,
        video_count,
        public_id,
        registered_at
    )
VALUES
    (
        0,
        COALESCE((
            SELECT
                ch.m_channel_id
            FROM
                m_channel ch
            WHERE
                ch.public_id = $1::uuid
            LIMIT
                1
        ), 0),
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
    )
ON CONFLICT (public_id) DO UPDATE SET
    playlist_title = EXCLUDED.playlist_title,
    playlist_description = EXCLUDED.playlist_description,
    visibility_code = EXCLUDED.visibility_code,
    playlist_code = EXCLUDED.playlist_code,
    video_count = EXCLUDED.video_count,
    registered_at = EXCLUDED.registered_at,
    updated_at = CURRENT_TIMESTAMP
RETURNING
    m_playlist.m_playlist_id
`

type UpsertSystemPlaylistParams struct {
	ChannelPublicID     *uuid.UUID
	PlaylistTitle       string
	PlaylistDescription string
	VisibilityCode      int
	PlaylistCode        int
	VideoCount          int
	PublicID            uuid.UUID
	RegisteredAt        time.Time
}

func (q *Queries) UpsertSystemPlaylist(ctx context.Context, arg UpsertSystemPlaylistParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSystemPlaylist,
		arg.ChannelPublicID,
		arg.PlaylistTitle,
		arg.PlaylistDescription,
		arg.VisibilityCode,
		arg.PlaylistCode,
		arg.VideoCount,
		arg.PublicID,
		arg.RegisteredAt,
	)
	var m_playlist_id int64
	err := row.Scan(&m_playlist_id)
	return m_playlist_id, err
}
