// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlist.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO
    m_playlist (
        m_user_id,
        playlist_title,
        playlist_description,
        visibility_code,
        playlist_code
    )
VALUES
    (
        (SELECT m_user.m_user_id FROM m_user WHERE m_user.public_id = $1 LIMIT 1),
        $2,
        $3,
        $4,
        $5
    )
RETURNING
    m_playlist.public_id,
    m_playlist.playlist_title,
    m_playlist.playlist_description,
    m_playlist.visibility_code,
    m_playlist.playlist_code,
    m_playlist.video_count,
    m_playlist.created_at,
    m_playlist.updated_at
`

type CreatePlaylistParams struct {
	UserPublicID        uuid.UUID
	PlaylistTitle       string
	PlaylistDescription string
	VisibilityCode      int
	PlaylistCode        int
}

type CreatePlaylistRow struct {
	PublicID            uuid.UUID
	PlaylistTitle       string
	PlaylistDescription string
	VisibilityCode      int
	PlaylistCode        int
	VideoCount          int
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (CreatePlaylistRow, error) {
	row := q.db.QueryRow(ctx, createPlaylist,
		arg.UserPublicID,
		arg.PlaylistTitle,
		arg.PlaylistDescription,
		arg.VisibilityCode,
		arg.PlaylistCode,
	)
	var i CreatePlaylistRow
	err := row.Scan(
		&i.PublicID,
		&i.PlaylistTitle,
		&i.PlaylistDescription,
		&i.VisibilityCode,
		&i.PlaylistCode,
		&i.VideoCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
