// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	// m_userをh_userに移動します。
	ArchiveUser(ctx context.Context, arg ArchiveUserParams) error
	BulkInsertPlaylistVideos(ctx context.Context, arg []BulkInsertPlaylistVideosParams) (int64, error)
	// NOTE: err == nilの場合はlen(param)
	BulkInsertScreenTimeRanges(ctx context.Context, arg []BulkInsertScreenTimeRangesParams) (int64, error)
	// NOTE: SaveChannelの前にこれをする. CTEでやろうと思ったけど、トランザクション...
	ClearStaleChannelCustomID(ctx context.Context, arg ClearStaleChannelCustomIDParams) error
	CloseStaleWatchSessions(ctx context.Context, userPublicID uuid.UUID) error
	CopyPlaylistVideos(ctx context.Context, arg CopyPlaylistVideosParams) (int, error)
	// m_user_authorizationの件数を取得する（日次レポート用）
	CountAuthorizations(ctx context.Context) (int64, error)
	// m_user_authorization_idに紐づくh_userとm_userの数を数える
	CountUsersByAuthorization(ctx context.Context, publicID uuid.UUID) (int32, error)
	// authorization_public_idに紐づく退会済みユーザーを削除する（再登録用）。
	// 退会済みユーザーが存在しない場合はpgx.ErrNoRowsが返される。
	DeleteLeftUserByAuthorization(ctx context.Context, userAuthorizationPublicID uuid.UUID) (int64, error)
	DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) (uuid.UUID, error)
	DeletePlaylistVideo(ctx context.Context, arg DeletePlaylistVideoParams) (int64, error)
	// m_user.m_user_idから、そのユーザーのスクリーン時間の範囲制限を削除する
	DeleteScreenTimeRangesByUserID(ctx context.Context, mUserID int64) error
	DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (int64, error)
	DeleteValuableChannel(ctx context.Context, channelPublicID uuid.UUID) error
	// jtiがブラックリストに存在するか確認する。
	// jtiが存在しない場合はpgx.ErrNoRowsが返される。
	// jtiが存在する場合は、そのexpires_atが返される。
	FindBlacklistedJTI(ctx context.Context, jti uuid.UUID) (time.Time, error)
	FindChannelByExternalID(ctx context.Context, arg FindChannelByExternalIDParams) (FindChannelByExternalIDRow, error)
	GetChannelByPublicID(ctx context.Context, channelID uuid.UUID) (GetChannelByPublicIDRow, error)
	GetChannelForUpdate(ctx context.Context, channelID uuid.UUID) (GetChannelForUpdateRow, error)
	// m_user.public_idから、そのユーザーが今日視聴していた合計時間(seconds)と設定している制限時間を返す。
	// その日に一本も動画を視聴していない場合は0を返します。
	GetDailyWatchSummary(ctx context.Context, arg GetDailyWatchSummaryParams) (GetDailyWatchSummaryRow, error)
	GetLastHeartbeatForUpdate(ctx context.Context, userPublicID uuid.UUID) (GetLastHeartbeatForUpdateRow, error)
	GetLatestMonthlyVideoWatchSummary(ctx context.Context, userID uuid.UUID) (GetLatestMonthlyVideoWatchSummaryRow, error)
	GetPlaylistForUpdate(ctx context.Context, arg GetPlaylistForUpdateParams) (GetPlaylistForUpdateRow, error)
	GetPlaylistWithThumbnail(ctx context.Context, arg GetPlaylistWithThumbnailParams) (GetPlaylistWithThumbnailRow, error)
	// m_user.public_idから、ユーザーをロッキングリードする。
	GetUserForUpdate(ctx context.Context, userPublicID uuid.UUID) (GetUserForUpdateRow, error)
	// authorization_idから、そのユーザーのpublic_idを取得する。
	// authorization_idが存在しない場合はpgx.ErrNoRowsが返される。
	// 退会済みの場合はtrueが返ってくる。
	GetUserIDByAuthorization(ctx context.Context, mUserAuthorizationID int64) (GetUserIDByAuthorizationRow, error)
	// m_user.public_idから、ユーザーのプロファイルとスクリーン時間制限範囲を取得する。
	GetUserProfile(ctx context.Context, userPublicID uuid.UUID) ([]GetUserProfileRow, error)
	GetValuableChannelForUpdate(ctx context.Context, channelPublicID uuid.UUID) (GetValuableChannelForUpdateRow, error)
	GetVideoDetail(ctx context.Context, arg GetVideoDetailParams) (GetVideoDetailRow, error)
	GetVideoWatchTitlesByUser(ctx context.Context, lowerID uuid.UUID) ([]GetVideoWatchTitlesByUserRow, error)
	InsertHeartbeat(ctx context.Context, arg InsertHeartbeatParams) error
	InsertPlaylistVideo(ctx context.Context, arg InsertPlaylistVideoParams) error
	// リフレッシュトークンをテーブルに保存する。
	// m_refresh_token_idが返される。
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (int64, error)
	InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) (int64, error)
	// ユーザーを作成する。
	InsertUser(ctx context.Context, arg InsertUserParams) (int64, error)
	ListChannelPlaylists(ctx context.Context, arg ListChannelPlaylistsParams) ([]ListChannelPlaylistsRow, error)
	ListChannelVideos(ctx context.Context, arg ListChannelVideosParams) ([]ListChannelVideosRow, error)
	ListChannelVideosOlder(ctx context.Context, arg ListChannelVideosOlderParams) ([]ListChannelVideosOlderRow, error)
	ListDailyWatchStatsByRange(ctx context.Context, arg ListDailyWatchStatsByRangeParams) ([]ListDailyWatchStatsByRangeRow, error)
	// 退会済みユーザーの一覧を取得する。
	ListLeftUsers(ctx context.Context) ([]ListLeftUsersRow, error)
	ListPlaylistVideos(ctx context.Context, arg ListPlaylistVideosParams) ([]ListPlaylistVideosRow, error)
	ListRecentPlaylists(ctx context.Context, userID uuid.UUID) ([]ListRecentPlaylistsRow, error)
	// userテーブルのpublic_idから、そのリフレッシュトークンの一覧を返します。
	ListRefreshTokens(ctx context.Context, arg ListRefreshTokensParams) ([]ListRefreshTokensRow, error)
	// m_user.public_idのユーザーの視聴制限範囲を取得する。
	ListScreenTimeRanges(ctx context.Context, userPublicID uuid.UUID) ([]ListScreenTimeRangesRow, error)
	ListStaleRSSChannelsForUpdate(ctx context.Context, arg ListStaleRSSChannelsForUpdateParams) ([]ListStaleRSSChannelsForUpdateRow, error)
	ListSubscribedChannels(ctx context.Context, arg ListSubscribedChannelsParams) ([]ListSubscribedChannelsRow, error)
	// ユーザーが登録しているチャンネルがだしている動画を最新順(public_id)で取得する。
	ListSubscriptionFeed(ctx context.Context, arg ListSubscriptionFeedParams) ([]ListSubscriptionFeedRow, error)
	ListUserPlaylists(ctx context.Context, arg ListUserPlaylistsParams) ([]ListUserPlaylistsRow, error)
	ListValuableChannels(ctx context.Context) ([]ListValuableChannelsRow, error)
	ListWatchHistory(ctx context.Context, arg ListWatchHistoryParams) ([]ListWatchHistoryRow, error)
	MarkVideoWatched(ctx context.Context, arg MarkVideoWatchedParams) error
	// expires_atが過ぎたjtiのブラックリストを削除します。
	PurgeExpiredJTIBlacklist(ctx context.Context, expiresAt time.Time) error
	// 退会済みユーザーとその関連データを全て削除する。
	// m_refresh_tokenはm_user_authorizationのCASCADE DELETEで自動削除される。
	PurgeLeftUser(ctx context.Context, arg PurgeLeftUserParams) error
	// m_user.recent_playlist_idsを更新する。先頭に追加し、重複を除去し、最大5件に制限する。
	PushRecentPlaylistId(ctx context.Context, arg PushRecentPlaylistIdParams) error
	// m_refresh_tokenのtoken_hashから、そのレコードを削除します。
	// 削除されたレコードに紐づくjtiをブラックリストに保存します。
	// 削除されたレコードのpublic_idが返されます。
	RevokeRefreshTokenByHash(ctx context.Context, arg RevokeRefreshTokenByHashParams) (uuid.UUID, error)
	// m_refresh_tokenのpublic_idから、そのレコードを削除します。
	// 削除されたレコードに紐づくjtiをブラックリストに保存します。
	// 削除されたレコードのpublic_idが返されます。
	RevokeRefreshTokenByID(ctx context.Context, arg RevokeRefreshTokenByIDParams) (uuid.UUID, error)
	// リフレッシュトークンを更新します。
	// token_hash = token_hash_for_check
	// updated_at < updated_at_for_check
	// expires_at > current_timestamp
	// の条件をすべて満たす場合にのみ更新されます。条件を満たさない場合は、pgx.ErrNoRowsが返されます。
	// リフレッシュトークンに紐づくuser_authorization_idから、それに紐づくuserのpublic_idを返します。
	RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (uuid.UUID, error)
	// 認証テーブルにIssuerとSubを保存する
	// IssuerとSubの組み合わせで一意制約があり、既に存在する場合は、何もしない。
	// 重複した場合でも特にエラーは発生せず、既存のレコードが返される。
	// 返り値は、m_user_authorization_idとpublic_id、そして新規作成されたかどうかを示すis_createdフラグ。
	SaveAuthorization(ctx context.Context, arg SaveAuthorizationParams) (SaveAuthorizationRow, error)
	// トランザクションレベルのロック（ノンブロッキング）
	TryAcquireAdvisoryXactLock(ctx context.Context, dollar_1 int64) (bool, error)
	UnmarkVideoWatched(ctx context.Context, arg UnmarkVideoWatchedParams) error
	UpdateHeartbeat(ctx context.Context, arg UpdateHeartbeatParams) error
	UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (uuid.UUID, error)
	// ユーザーを更新する。
	UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error)
	UpsertChannel(ctx context.Context, arg UpsertChannelParams) (UpsertChannelRow, error)
	UpsertMonthlyVideoWatchSummary(ctx context.Context, arg UpsertMonthlyVideoWatchSummaryParams) error
	UpsertPlaylist(ctx context.Context, arg UpsertPlaylistParams) (int64, error)
	UpsertRatelimit(ctx context.Context, arg UpsertRatelimitParams) (UpsertRatelimitRow, error)
	UpsertValuableChannel(ctx context.Context, arg UpsertValuableChannelParams) (int64, error)
	UpsertVideo(ctx context.Context, arg UpsertVideoParams) (UpsertVideoRow, error)
}

var _ Querier = (*Queries)(nil)
