// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ratelimit.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const upsertRatelimit = `-- name: UpsertRatelimit :one
INSERT INTO t_ratelimit(
    user_public_id,
    consumed_quota
)
VALUES ($1, $2)
ON CONFLICT (user_public_id) DO UPDATE SET
    consumed_quota = CASE
        WHEN updated_at AT TIME ZONE 'US/Pacific' < date_trunc('day', current_timestamp AT TIME ZONE 'US/Pacific') THEN EXCLUDED.consumed_quota
        ELSE consumed_quota + EXCLUDED.consumed_quota
    END,
    updated_at = current_timestamp
RETURNING t_ratelimit_id, consumed_quota
`

type UpsertRatelimitParams struct {
	UserID uuid.UUID
	Quota  int
}

type UpsertRatelimitRow struct {
	TRatelimitID  int64
	ConsumedQuota int
}

func (q *Queries) UpsertRatelimit(ctx context.Context, arg UpsertRatelimitParams) (UpsertRatelimitRow, error) {
	row := q.db.QueryRow(ctx, upsertRatelimit, arg.UserID, arg.Quota)
	var i UpsertRatelimitRow
	err := row.Scan(&i.TRatelimitID, &i.ConsumedQuota)
	return i, err
}
