// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findBlacklistedJTI = `-- name: FindBlacklistedJTI :one
SELECT
    expires_at
FROM
    t_jti_blacklist
WHERE
    jti = $1
LIMIT
    1
`

// jtiがブラックリストに存在するか確認する。
// jtiが存在しない場合はpgx.ErrNoRowsが返される。
// jtiが存在する場合は、そのexpires_atが返される。
func (q *Queries) FindBlacklistedJTI(ctx context.Context, jti uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, findBlacklistedJTI, jti)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO
    m_refresh_token (
        m_user_authorization_id,
        token_hash,
        generation,
        public_id,
        ip_address,
        device_fingerprint,
        user_agent,
        country_code,
        city_name,
        browser_name,
        device_type,
        expires_at,
        access_token_jti,
        activated_at,
        last_logged_in_at
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING
    m_refresh_token_id
`

type InsertRefreshTokenParams struct {
	MUserAuthorizationID int64
	TokenHash            string
	Generation           int
	PublicID             uuid.UUID
	IpAddress            string
	DeviceFingerprint    string
	UserAgent            string
	CountryCode          string
	CityName             string
	BrowserName          string
	DeviceType           string
	ExpiresAt            time.Time
	AccessTokenJti       uuid.UUID
	ActivatedAt          time.Time
	LastLoggedInAt       time.Time
}

// リフレッシュトークンをテーブルに保存する。
// m_refresh_token_idが返される。
func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken,
		arg.MUserAuthorizationID,
		arg.TokenHash,
		arg.Generation,
		arg.PublicID,
		arg.IpAddress,
		arg.DeviceFingerprint,
		arg.UserAgent,
		arg.CountryCode,
		arg.CityName,
		arg.BrowserName,
		arg.DeviceType,
		arg.ExpiresAt,
		arg.AccessTokenJti,
		arg.ActivatedAt,
		arg.LastLoggedInAt,
	)
	var m_refresh_token_id int64
	err := row.Scan(&m_refresh_token_id)
	return m_refresh_token_id, err
}

const listRefreshTokens = `-- name: ListRefreshTokens :many
SELECT
    m_refresh_token.public_id,
    m_refresh_token.activated_at,
    m_refresh_token.last_logged_in_at,
    m_refresh_token.user_agent,
    m_refresh_token.ip_address,
    m_refresh_token.country_code,
    m_refresh_token.city_name,
    m_refresh_token.browser_name,
    m_refresh_token.device_type
FROM
    m_refresh_token
    INNER JOIN m_user ON m_user.m_user_authorization_id = m_refresh_token.m_user_authorization_id
WHERE
    m_user.public_id = $1 AND (
        $2::uuid IS NULL OR
        m_refresh_token.public_id < $2
    )
ORDER BY
    m_refresh_token.public_id DESC
LIMIT
    $3
`

type ListRefreshTokensParams struct {
	UserID     uuid.UUID
	Cursor     *uuid.UUID
	QueryLimit int32
}

type ListRefreshTokensRow struct {
	PublicID       uuid.UUID
	ActivatedAt    time.Time
	LastLoggedInAt time.Time
	UserAgent      string
	IpAddress      string
	CountryCode    string
	CityName       string
	BrowserName    string
	DeviceType     string
}

// userテーブルのpublic_idから、そのリフレッシュトークンの一覧を返します。
func (q *Queries) ListRefreshTokens(ctx context.Context, arg ListRefreshTokensParams) ([]ListRefreshTokensRow, error) {
	rows, err := q.db.Query(ctx, listRefreshTokens, arg.UserID, arg.Cursor, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRefreshTokensRow
	for rows.Next() {
		var i ListRefreshTokensRow
		if err := rows.Scan(
			&i.PublicID,
			&i.ActivatedAt,
			&i.LastLoggedInAt,
			&i.UserAgent,
			&i.IpAddress,
			&i.CountryCode,
			&i.CityName,
			&i.BrowserName,
			&i.DeviceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredJTIBlacklist = `-- name: PurgeExpiredJTIBlacklist :exec
DELETE FROM
    t_jti_blacklist
WHERE
    expires_at < $1
`

// expires_atが過ぎたjtiのブラックリストを削除します。
func (q *Queries) PurgeExpiredJTIBlacklist(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.Exec(ctx, purgeExpiredJTIBlacklist, expiresAt)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :one
WITH deleted AS (
    DELETE FROM
        m_refresh_token USING m_user
    WHERE
        m_user.public_id = $1
        AND m_user.m_user_authorization_id = m_refresh_token.m_user_authorization_id
        AND m_refresh_token.token_hash = $2
    RETURNING
        m_refresh_token.public_id,
        m_refresh_token.access_token_jti
),
inserted AS (
    INSERT INTO
        t_jti_blacklist (jti, expires_at)
    SELECT
        access_token_jti,
        $3
    FROM
        deleted
    ON CONFLICT DO NOTHING
    RETURNING
        jti
)
SELECT
    deleted.public_id
FROM
    deleted
LIMIT
    1
`

type RevokeRefreshTokenByHashParams struct {
	UserPublicID uuid.UUID
	TokenHash    string
	ExpiresAt    time.Time
}

// m_refresh_tokenのtoken_hashから、そのレコードを削除します。
// 削除されたレコードに紐づくjtiをブラックリストに保存します。
// 削除されたレコードのpublic_idが返されます。
func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, arg RevokeRefreshTokenByHashParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeRefreshTokenByHash, arg.UserPublicID, arg.TokenHash, arg.ExpiresAt)
	var public_id uuid.UUID
	err := row.Scan(&public_id)
	return public_id, err
}

const revokeRefreshTokenByID = `-- name: RevokeRefreshTokenByID :one
WITH deleted AS (
    DELETE FROM
        m_refresh_token USING m_user
    WHERE
        m_user.public_id = $1
        AND m_user.m_user_authorization_id = m_refresh_token.m_user_authorization_id
        AND m_refresh_token.public_id = $2
    RETURNING
        m_refresh_token.public_id,
        m_refresh_token.access_token_jti
),
inserted AS (
    INSERT INTO
        t_jti_blacklist (jti, expires_at)
    SELECT
        access_token_jti,
        $3
    FROM
        deleted
    ON CONFLICT DO NOTHING
    RETURNING
        jti
)
SELECT
    deleted.public_id
FROM
    deleted
LIMIT
    1
`

type RevokeRefreshTokenByIDParams struct {
	UserPublicID         uuid.UUID
	RefreshTokenPublicID uuid.UUID
	ExpiresAt            time.Time
}

// m_refresh_tokenのpublic_idから、そのレコードを削除します。
// 削除されたレコードに紐づくjtiをブラックリストに保存します。
// 削除されたレコードのpublic_idが返されます。
func (q *Queries) RevokeRefreshTokenByID(ctx context.Context, arg RevokeRefreshTokenByIDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeRefreshTokenByID, arg.UserPublicID, arg.RefreshTokenPublicID, arg.ExpiresAt)
	var public_id uuid.UUID
	err := row.Scan(&public_id)
	return public_id, err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
WITH updated AS (
    UPDATE
        m_refresh_token
    SET
        token_hash = $1,
        expires_at = $2,
        ip_address = $3,
        device_fingerprint = $4,
        user_agent = $5,
        country_code = $6,
        city_name = $7,
        browser_name = $8,
        device_type = $9,
        updated_at = current_timestamp,
        generation = generation + 1,
        access_token_jti = $10,
        last_logged_in_at = $11
    WHERE
        token_hash = $12 -- NOTE: token_hashにunique indexがあるため、updated_at, expires_atにインデックスは張らなくてもよい
        AND m_refresh_token.updated_at < $13
        AND expires_at > current_timestamp
    RETURNING
        m_user_authorization_id
)
SELECT
    m_user.public_id
FROM
    m_user, updated
WHERE
    m_user.m_user_authorization_id = updated.m_user_authorization_id
LIMIT
    1
`

type RotateRefreshTokenParams struct {
	NewTokenHash         string
	NewExpiresAt         time.Time
	NewIpAddress         string
	NewDeviceFingerprint string
	NewUserAgent         string
	NewCountryCode       string
	NewCityName          string
	NewBrowserName       string
	NewDeviceType        string
	NewAccessTokenJti    uuid.UUID
	LastLoggedInAt       time.Time
	TokenHashForCheck    string
	UpdatedAtForCheck    time.Time
}

// リフレッシュトークンを更新します。
// token_hash = token_hash_for_check
// updated_at < updated_at_for_check
// expires_at > current_timestamp
// の条件をすべて満たす場合にのみ更新されます。条件を満たさない場合は、pgx.ErrNoRowsが返されます。
// リフレッシュトークンに紐づくuser_authorization_idから、それに紐づくuserのpublic_idを返します。
func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken,
		arg.NewTokenHash,
		arg.NewExpiresAt,
		arg.NewIpAddress,
		arg.NewDeviceFingerprint,
		arg.NewUserAgent,
		arg.NewCountryCode,
		arg.NewCityName,
		arg.NewBrowserName,
		arg.NewDeviceType,
		arg.NewAccessTokenJti,
		arg.LastLoggedInAt,
		arg.TokenHashForCheck,
		arg.UpdatedAtForCheck,
	)
	var public_id uuid.UUID
	err := row.Scan(&public_id)
	return public_id, err
}
