// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: summary.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getVideoWatchTitlesByUser = `-- name: GetVideoWatchTitlesByUser :many
SELECT
    vw.m_user_id AS user_id,
    u.language_code AS language_code,
    string_agg(DISTINCT REPLACE(video.external_title, ',', ''), ',') AS title_concat
FROM
    t_video_watch vw
INNER JOIN
    m_video video ON vw.m_video_id = video.m_video_id
INNER JOIN
    m_user u ON vw.m_user_id = u.m_user_id
WHERE
    $1 <= vw.public_id
GROUP BY
    vw.m_user_id, u.language_code
`

type GetVideoWatchTitlesByUserRow struct {
	UserID       int64
	LanguageCode string
	TitleConcat  []byte
}

func (q *Queries) GetVideoWatchTitlesByUser(ctx context.Context, lowerID uuid.UUID) ([]GetVideoWatchTitlesByUserRow, error) {
	rows, err := q.db.Query(ctx, getVideoWatchTitlesByUser, lowerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVideoWatchTitlesByUserRow
	for rows.Next() {
		var i GetVideoWatchTitlesByUserRow
		if err := rows.Scan(&i.UserID, &i.LanguageCode, &i.TitleConcat); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMonthlyVideoWatchSummary = `-- name: UpsertMonthlyVideoWatchSummary :exec
INSERT INTO s_monthly_video_watch (
    m_user_id,
    ai_summary_title,
    ai_summary_description,
    ai_model,
    generated_at,
    target_month,
    public_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    uuidv7()
)
ON CONFLICT (m_user_id, target_month) DO UPDATE SET
    ai_summary_title = EXCLUDED.ai_summary_title,
    ai_summary_description = EXCLUDED.ai_summary_description,
    ai_model = EXCLUDED.ai_model,
    generated_at = EXCLUDED.generated_at,
    updated_at = current_timestamp
`

type UpsertMonthlyVideoWatchSummaryParams struct {
	UserID               int64
	AiSummaryTitle       string
	AiSummaryDescription string
	AiModel              string
	GeneratedAt          time.Time
	TargetMonth          time.Time
}

func (q *Queries) UpsertMonthlyVideoWatchSummary(ctx context.Context, arg UpsertMonthlyVideoWatchSummaryParams) error {
	_, err := q.db.Exec(ctx, upsertMonthlyVideoWatchSummary,
		arg.UserID,
		arg.AiSummaryTitle,
		arg.AiSummaryDescription,
		arg.AiModel,
		arg.GeneratedAt,
		arg.TargetMonth,
	)
	return err
}
