// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
	"time"

	"github.com/brqnko/anti-yt/backend/internal/core/database_d/dbtype"
	"github.com/google/uuid"
)

const archiveUser = `-- name: ArchiveUser :exec
WITH deleted AS (
    DELETE FROM
        m_user
    WHERE
        m_user.public_id = $2
    RETURNING
        m_user.m_user_id,
        m_user.m_user_authorization_id,
        m_user.display_name,
        m_user.language_code,
        m_user.daily_screen_time_seconds,
        m_user.joined_at,
        m_user.public_id
)
INSERT INTO
    h_user (
        h_user_id,
        m_user_authorization_id,
        display_name,
        language_code,
        daily_screen_time_seconds,
        joined_at,
        left_at,
        leave_reason_code,
        public_id
    )
SELECT
    deleted.m_user_id AS h_user_id,
    deleted.m_user_authorization_id AS m_user_authorization_id,
    deleted.display_name AS display_name,
    deleted.language_code AS language_code,
    deleted.daily_screen_time_seconds AS daily_screen_time_seconds,
    deleted.joined_at AS joined_at,
    CURRENT_TIMESTAMP AS left_at,
    $1 AS leave_reason_code,
    deleted.public_id AS public_id
FROM
    deleted
`

type ArchiveUserParams struct {
	LeaveReasonCode int
	UserPublicID    uuid.UUID
}

// m_userをh_userに移動します。
func (q *Queries) ArchiveUser(ctx context.Context, arg ArchiveUserParams) error {
	_, err := q.db.Exec(ctx, archiveUser, arg.LeaveReasonCode, arg.UserPublicID)
	return err
}

type BulkInsertScreenTimeRangesParams struct {
	MUserID              int64
	ScreenTimeRangeStart dbtype.Seconds
	ScreenTimeRangeEnd   dbtype.Seconds
}

const countUsersByAuthorization = `-- name: CountUsersByAuthorization :one
WITH auth AS (
    SELECT
        m_user_authorization_id
    FROM
        m_user_authorization
    WHERE
        m_user_authorization.public_id = $1
    LIMIT
        1
)
SELECT
    (
        SELECT
            COUNT(*)
        FROM
            h_user
        WHERE
            m_user_authorization_id = (
                SELECT
                    auth.m_user_authorization_id
                FROM
                    auth
            )
    ) + (
        SELECT
            COUNT(*)
        FROM
            m_user
        WHERE
            m_user_authorization_id = (
                SELECT
                    auth.m_user_authorization_id
                FROM
                    auth
            )
    ) AS total_count
`

// m_user_authorization_idに紐づくh_userとm_userの数を数える
func (q *Queries) CountUsersByAuthorization(ctx context.Context, authorizationPublicID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUsersByAuthorization, authorizationPublicID)
	var total_count int32
	err := row.Scan(&total_count)
	return total_count, err
}

const deleteScreenTimeRangesByUserID = `-- name: DeleteScreenTimeRangesByUserID :exec
DELETE FROM
    m_user_screen_time_range
WHERE
    m_user_screen_time_range.m_user_id = $1
`

// m_user.m_user_idから、そのユーザーのスクリーン時間の範囲制限を削除する
func (q *Queries) DeleteScreenTimeRangesByUserID(ctx context.Context, mUserID int64) error {
	_, err := q.db.Exec(ctx, deleteScreenTimeRangesByUserID, mUserID)
	return err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT
    m_user.public_id,
    m_user.display_name,
    m_user.language_code,
    m_user.joined_at,
    m_user.daily_screen_time_seconds
FROM
    m_user
WHERE
    m_user.public_id = $1
LIMIT
    1
FOR UPDATE
`

type GetUserForUpdateRow struct {
	PublicID               uuid.UUID
	DisplayName            string
	LanguageCode           string
	JoinedAt               time.Time
	DailyScreenTimeSeconds int
}

// m_user.public_idから、ユーザーをロッキングリードする。
func (q *Queries) GetUserForUpdate(ctx context.Context, userPublicID uuid.UUID) (GetUserForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, userPublicID)
	var i GetUserForUpdateRow
	err := row.Scan(
		&i.PublicID,
		&i.DisplayName,
		&i.LanguageCode,
		&i.JoinedAt,
		&i.DailyScreenTimeSeconds,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :many
SELECT
    m_user.display_name,
    m_user.language_code,
    m_user.joined_at,
    m_user.daily_screen_time_seconds,
    m_user_screen_time_range.screen_time_range_start,
    m_user_screen_time_range.screen_time_range_end
FROM
    m_user
    LEFT JOIN m_user_screen_time_range ON m_user_screen_time_range.m_user_id = m_user.m_user_id
WHERE
    m_user.public_id = $1
ORDER BY
    m_user_screen_time_range.screen_time_range_start
`

type GetUserProfileRow struct {
	DisplayName            string
	LanguageCode           string
	JoinedAt               time.Time
	DailyScreenTimeSeconds int
	ScreenTimeRangeStart   *dbtype.Seconds
	ScreenTimeRangeEnd     *dbtype.Seconds
}

// m_user.public_idから、ユーザーのプロファイルとスクリーン時間制限範囲を取得する。
func (q *Queries) GetUserProfile(ctx context.Context, userPublicID uuid.UUID) ([]GetUserProfileRow, error) {
	rows, err := q.db.Query(ctx, getUserProfile, userPublicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserProfileRow
	for rows.Next() {
		var i GetUserProfileRow
		if err := rows.Scan(
			&i.DisplayName,
			&i.LanguageCode,
			&i.JoinedAt,
			&i.DailyScreenTimeSeconds,
			&i.ScreenTimeRangeStart,
			&i.ScreenTimeRangeEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUser = `-- name: InsertUser :one
INSERT INTO
    m_user (
        m_user_authorization_id,
        display_name,
        language_code,
        daily_screen_time_seconds,
        joined_at,
        public_id,
        recent_playlist_ids
    )
SELECT
    m_user_authorization.m_user_authorization_id,
    $1,
    $2,
    $3,
    $4,
    $5,
    '{}'::bigint[]
FROM
    m_user_authorization
WHERE
    m_user_authorization.public_id = $6
LIMIT
    1
RETURNING
    m_user_id
`

type InsertUserParams struct {
	DisplayName               string
	LanguageCode              string
	DailyScreenTimeSeconds    int
	JoinedAt                  time.Time
	PublicID                  uuid.UUID
	UserAuthorizationPublicID uuid.UUID
}

// ユーザーを作成する。
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.DisplayName,
		arg.LanguageCode,
		arg.DailyScreenTimeSeconds,
		arg.JoinedAt,
		arg.PublicID,
		arg.UserAuthorizationPublicID,
	)
	var m_user_id int64
	err := row.Scan(&m_user_id)
	return m_user_id, err
}

const listAllActiveUserIDs = `-- name: ListAllActiveUserIDs :many
SELECT m_user.public_id FROM m_user
`

// アクティブな全ユーザーのpublic_idを取得する。Redis feedのseed/refill用途。
func (q *Queries) ListAllActiveUserIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAllActiveUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var public_id uuid.UUID
		if err := rows.Scan(&public_id); err != nil {
			return nil, err
		}
		items = append(items, public_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeftUsers = `-- name: ListLeftUsers :many
SELECT h_user_id, m_user_authorization_id, public_id FROM h_user
`

type ListLeftUsersRow struct {
	HUserID              int64
	MUserAuthorizationID int64
	PublicID             uuid.UUID
}

// 退会済みユーザーの一覧を取得する。
func (q *Queries) ListLeftUsers(ctx context.Context) ([]ListLeftUsersRow, error) {
	rows, err := q.db.Query(ctx, listLeftUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLeftUsersRow
	for rows.Next() {
		var i ListLeftUsersRow
		if err := rows.Scan(&i.HUserID, &i.MUserAuthorizationID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScreenTimeRanges = `-- name: ListScreenTimeRanges :many
SELECT
    m_user_screen_time_range.screen_time_range_start,
    m_user_screen_time_range.screen_time_range_end
FROM
    m_user_screen_time_range
WHERE
    m_user_screen_time_range.m_user_id = (
        SELECT
            m_user.m_user_id
        FROM
            m_user
        WHERE
            m_user.public_id = $1
        LIMIT
            1
    )
ORDER BY
    m_user_screen_time_range.screen_time_range_start
`

type ListScreenTimeRangesRow struct {
	ScreenTimeRangeStart dbtype.Seconds
	ScreenTimeRangeEnd   dbtype.Seconds
}

// m_user.public_idのユーザーの視聴制限範囲を取得する。
func (q *Queries) ListScreenTimeRanges(ctx context.Context, userPublicID uuid.UUID) ([]ListScreenTimeRangesRow, error) {
	rows, err := q.db.Query(ctx, listScreenTimeRanges, userPublicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScreenTimeRangesRow
	for rows.Next() {
		var i ListScreenTimeRangesRow
		if err := rows.Scan(&i.ScreenTimeRangeStart, &i.ScreenTimeRangeEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeLeftUser = `-- name: PurgeLeftUser :exec
WITH d_playlist_video AS (
    DELETE FROM m_playlist_video
    WHERE m_playlist_video.m_playlist_id IN (SELECT m_playlist.m_playlist_id FROM m_playlist WHERE m_playlist.m_user_id = $2)
),
d_playlist AS (
    DELETE FROM m_playlist WHERE m_playlist.m_user_id = $2
),
d_subscription AS (
    DELETE FROM m_user_subscribing_channel WHERE m_user_subscribing_channel.m_user_id = $2
),
d_screen_time AS (
    DELETE FROM m_user_screen_time_range WHERE m_user_screen_time_range.m_user_id = $2
),
d_video_watch AS (
    DELETE FROM t_video_watch WHERE t_video_watch.m_user_id = $2
),
d_video_watched AS (
    DELETE FROM t_video_watched WHERE t_video_watched.m_user_id = $2
),
d_summary AS (
    DELETE FROM s_monthly_video_watch WHERE s_monthly_video_watch.m_user_id = $2
),
d_h_user AS (
    DELETE FROM h_user WHERE h_user.h_user_id = $2
)
DELETE FROM m_user_authorization WHERE m_user_authorization.m_user_authorization_id = $1
`

type PurgeLeftUserParams struct {
	AuthorizationID int64
	HUserID         int64
}

// 退会済みユーザーとその関連データを全て削除する。
// m_refresh_tokenはm_user_authorizationのCASCADE DELETEで自動削除される。
func (q *Queries) PurgeLeftUser(ctx context.Context, arg PurgeLeftUserParams) error {
	_, err := q.db.Exec(ctx, purgeLeftUser, arg.AuthorizationID, arg.HUserID)
	return err
}

const restoreUserFromHistory = `-- name: RestoreUserFromHistory :one
WITH auth AS (
    SELECT m_user_authorization_id
    FROM m_user_authorization
    WHERE m_user_authorization.public_id = $1
    LIMIT 1
),
restored AS (
    DELETE FROM h_user
    WHERE h_user.m_user_authorization_id = (SELECT m_user_authorization_id FROM auth)
    RETURNING
        h_user_id,
        m_user_authorization_id,
        display_name,
        language_code,
        daily_screen_time_seconds,
        joined_at,
        public_id
),
inserted AS (
    INSERT INTO
        m_user (
            m_user_id,
            m_user_authorization_id,
            display_name,
            language_code,
            daily_screen_time_seconds,
            joined_at,
            public_id,
            recent_playlist_ids
        )
    OVERRIDING SYSTEM VALUE
    SELECT
        h_user_id,
        m_user_authorization_id,
        display_name,
        language_code,
        daily_screen_time_seconds,
        joined_at,
        public_id,
        '{}'::bigint[]
    FROM restored
    RETURNING m_user_authorization_id, public_id
)
SELECT m_user_authorization_id, public_id FROM inserted
`

type RestoreUserFromHistoryRow struct {
	MUserAuthorizationID int64
	PublicID             uuid.UUID
}

// authorization_public_idに紐づく退会済みユーザーをh_userからm_userに復元する。
// 元のm_user_id (=h_user_id) を保ったまま戻すため、購読・プレイリスト・視聴履歴などの
// 関連データのFKがそのまま生きる。
// 退会済みユーザーが存在しない場合はpgx.ErrNoRowsが返される。
// 復元したm_userのpublic_idと、m_user_authorization_id (bigint)を返す。
func (q *Queries) RestoreUserFromHistory(ctx context.Context, userAuthorizationPublicID uuid.UUID) (RestoreUserFromHistoryRow, error) {
	row := q.db.QueryRow(ctx, restoreUserFromHistory, userAuthorizationPublicID)
	var i RestoreUserFromHistoryRow
	err := row.Scan(&i.MUserAuthorizationID, &i.PublicID)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE
    m_user
SET
    display_name = $1,
    language_code = $2,
    daily_screen_time_seconds = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE
    m_user.public_id = $4
RETURNING
    m_user_id
`

type UpdateUserParams struct {
	DisplayName            string
	LanguageCode           string
	DailyScreenTimeSeconds int
	UserPublicID           uuid.UUID
}

// ユーザーを更新する。
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.DisplayName,
		arg.LanguageCode,
		arg.DailyScreenTimeSeconds,
		arg.UserPublicID,
	)
	var m_user_id int64
	err := row.Scan(&m_user_id)
	return m_user_id, err
}
