// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: valuable_channel.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteValuableChannel = `-- name: DeleteValuableChannel :exec
DELETE FROM
    m_valuable_channel
USING
    m_channel
WHERE
    m_channel.m_channel_id = m_valuable_channel.m_channel_id
    AND m_channel.public_id = $1
`

func (q *Queries) DeleteValuableChannel(ctx context.Context, channelPublicID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteValuableChannel, channelPublicID)
	return err
}

const getValuableChannelForUpdate = `-- name: GetValuableChannelForUpdate :one
SELECT
    m_channel.public_id AS channel_public_id,
    m_valuable_channel.category_code,
    m_valuable_channel.valuable_description
FROM
    m_valuable_channel
    INNER JOIN m_channel ON m_channel.m_channel_id = m_valuable_channel.m_channel_id
WHERE
    m_channel.public_id = $1
LIMIT 1
FOR UPDATE OF m_valuable_channel
`

type GetValuableChannelForUpdateRow struct {
	ChannelPublicID     uuid.UUID
	CategoryCode        int
	ValuableDescription string
}

func (q *Queries) GetValuableChannelForUpdate(ctx context.Context, channelPublicID uuid.UUID) (GetValuableChannelForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getValuableChannelForUpdate, channelPublicID)
	var i GetValuableChannelForUpdateRow
	err := row.Scan(&i.ChannelPublicID, &i.CategoryCode, &i.ValuableDescription)
	return i, err
}

const listValuableChannels = `-- name: ListValuableChannels :many
SELECT
    m_channel.public_id AS channel_public_id,
    m_channel.external_custom_id,
    m_channel.external_display_name,
    m_channel.external_icon_url,
    m_valuable_channel.category_code,
    m_valuable_channel.valuable_description
FROM
    m_valuable_channel
    INNER JOIN m_channel ON m_channel.m_channel_id = m_valuable_channel.m_channel_id
ORDER BY
    m_valuable_channel.m_valuable_channel_id DESC
`

type ListValuableChannelsRow struct {
	ChannelPublicID     uuid.UUID
	ExternalCustomID    string
	ExternalDisplayName string
	ExternalIconUrl     string
	CategoryCode        int
	ValuableDescription string
}

func (q *Queries) ListValuableChannels(ctx context.Context) ([]ListValuableChannelsRow, error) {
	rows, err := q.db.Query(ctx, listValuableChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListValuableChannelsRow
	for rows.Next() {
		var i ListValuableChannelsRow
		if err := rows.Scan(
			&i.ChannelPublicID,
			&i.ExternalCustomID,
			&i.ExternalDisplayName,
			&i.ExternalIconUrl,
			&i.CategoryCode,
			&i.ValuableDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertValuableChannel = `-- name: UpsertValuableChannel :one
INSERT INTO
    m_valuable_channel (m_channel_id, category_code, valuable_description)
SELECT
    m_channel.m_channel_id, $1, $2
FROM
    m_channel
WHERE
    m_channel.public_id = $3
LIMIT 1
ON CONFLICT (m_channel_id) DO UPDATE SET
    category_code = EXCLUDED.category_code,
    valuable_description = EXCLUDED.valuable_description,
    updated_at = current_timestamp
RETURNING
    m_valuable_channel_id
`

type UpsertValuableChannelParams struct {
	CategoryCode        int
	ValuableDescription string
	ChannelPublicID     uuid.UUID
}

func (q *Queries) UpsertValuableChannel(ctx context.Context, arg UpsertValuableChannelParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertValuableChannel, arg.CategoryCode, arg.ValuableDescription, arg.ChannelPublicID)
	var m_valuable_channel_id int64
	err := row.Scan(&m_valuable_channel_id)
	return m_valuable_channel_id, err
}
