// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: valuable_channel.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listValuableChannels = `-- name: ListValuableChannels :many
SELECT
    m_channel.public_id AS channel_public_id,
    m_channel.external_custom_id,
    m_channel.external_display_name,
    m_channel.external_icon_url,
    m_valuable_channel.category_code,
    m_valuable_channel.valuable_description
FROM
    m_valuable_channel
    INNER JOIN m_channel ON m_channel.m_channel_id = m_valuable_channel.m_channel_id
ORDER BY
    m_valuable_channel.m_valuable_channel_id DESC
`

type ListValuableChannelsRow struct {
	ChannelPublicID     uuid.UUID
	ExternalCustomID    string
	ExternalDisplayName string
	ExternalIconUrl     string
	CategoryCode        int
	ValuableDescription string
}

func (q *Queries) ListValuableChannels(ctx context.Context) ([]ListValuableChannelsRow, error) {
	rows, err := q.db.Query(ctx, listValuableChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListValuableChannelsRow
	for rows.Next() {
		var i ListValuableChannelsRow
		if err := rows.Scan(
			&i.ChannelPublicID,
			&i.ExternalCustomID,
			&i.ExternalDisplayName,
			&i.ExternalIconUrl,
			&i.CategoryCode,
			&i.ValuableDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
