// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getChannelVideos = `-- name: GetChannelVideos :many
SELECT
    m_video.public_id,
    m_video.external_id,
    m_video.external_thumbnail_url,
    m_video.external_title,
    m_video.external_description,
    m_video.external_created_at,
    m_video.external_length_seconds,
    COALESCE((
        SELECT
            t_video_watch.watch_position_seconds
        FROM
            t_video_watch
        WHERE
            t_video_watch.m_user_id = (
                SELECT
                    m_user.m_user_id
                FROM
                    m_user
                WHERE
                    m_user.public_id = $1
                LIMIT 1
            )
            AND t_video_watch.m_video_id = m_video.m_video_id
        ORDER BY
            t_video_watch.m_user_id,
            t_video_watch.m_video_id,
            t_video_watch.watch_start_at DESC
        LIMIT
            1
    ), 0)::int AS last_watch_seconds,
    m_channel.public_id AS channel_id,
    m_channel.external_id AS external_channel_id,
    m_channel.external_icon_url AS external_channel_icon_url,
    m_channel.external_display_name AS external_channel_displayname
FROM
    m_video
    INNER JOIN m_channel ON m_channel.m_channel_id = m_video.m_channel_id
WHERE
    m_channel.public_id = $2
    AND (
        $3 :: uuid IS NULL
        OR (
            m_video.external_created_at < (
                SELECT
                    mv.external_created_at
                FROM
                    m_video mv
                WHERE
                    mv.public_id = $3 :: uuid
                LIMIT
                    1
            )
        )
        OR (
            m_video.external_created_at = (
                SELECT
                    mv.external_created_at
                FROM
                    m_video mv
                WHERE
                    mv.public_id = $3 :: uuid
                LIMIT
                    1
            )
            AND m_video.public_id < $3 :: uuid
        )
    )
ORDER BY
    m_video.external_created_at DESC,
    m_video.public_id DESC
LIMIT
    $4
`

type GetChannelVideosParams struct {
	UserID     uuid.UUID
	ChannelID  uuid.UUID
	Cursor     *uuid.UUID
	QueryLimit int32
}

type GetChannelVideosRow struct {
	PublicID                   uuid.UUID
	ExternalID                 string
	ExternalThumbnailUrl       string
	ExternalTitle              string
	ExternalDescription        string
	ExternalCreatedAt          time.Time
	ExternalLengthSeconds      int
	LastWatchSeconds           int
	ChannelID                  uuid.UUID
	ExternalChannelID          string
	ExternalChannelIconUrl     string
	ExternalChannelDisplayname string
}

func (q *Queries) GetChannelVideos(ctx context.Context, arg GetChannelVideosParams) ([]GetChannelVideosRow, error) {
	rows, err := q.db.Query(ctx, getChannelVideos,
		arg.UserID,
		arg.ChannelID,
		arg.Cursor,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelVideosRow
	for rows.Next() {
		var i GetChannelVideosRow
		if err := rows.Scan(
			&i.PublicID,
			&i.ExternalID,
			&i.ExternalThumbnailUrl,
			&i.ExternalTitle,
			&i.ExternalDescription,
			&i.ExternalCreatedAt,
			&i.ExternalLengthSeconds,
			&i.LastWatchSeconds,
			&i.ChannelID,
			&i.ExternalChannelID,
			&i.ExternalChannelIconUrl,
			&i.ExternalChannelDisplayname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscribingChannelFeed = `-- name: GetSubscribingChannelFeed :many
SELECT
    m_video.public_id AS video_id,
    m_video.external_id AS external_video_id,
    m_video.external_thumbnail_url AS external_video_thumbnail_url,
    m_video.external_title AS external_title,
    m_video.external_description AS external_description,
    m_video.external_created_at AS external_created_at,
    m_video.external_length_seconds AS external_length_seconds,
    COALESCE((
        SELECT
            t_video_watch.watch_position_seconds
        FROM
            t_video_watch
        WHERE
            t_video_watch.m_user_id = (
                SELECT
                    m_user.m_user_id
                FROM
                    m_user
                WHERE
                    m_user.public_id = $1
            )
            AND t_video_watch.m_video_id = m_video.m_video_id
        ORDER BY
            t_video_watch.m_user_id,
            t_video_watch.m_video_id,
            t_video_watch.watch_start_at DESC
        LIMIT
            1
    ), 0)::int AS last_watch_seconds,
    m_channel.public_id AS channel_id,
    m_channel.external_id AS external_channel_id,
    m_channel.external_icon_url AS external_channel_icon_url,
    m_channel.external_display_name AS external_displayname
FROM
    m_video
    INNER JOIN m_user_subscribing_channel ON m_video.m_channel_id = m_user_subscribing_channel.m_channel_id
    INNER JOIN m_channel ON m_channel.m_channel_id = m_video.m_channel_id
WHERE
    m_user_subscribing_channel.m_user_id = (
        SELECT
            m_user.m_user_id
        FROM
            m_user
        WHERE
            m_user.public_id = $1
        LIMIT
            1
    )
    AND (
        -- 日付がカーソルより昔 or (日付がカーソルと同じ and public_idがカーソルより昔)
        $2 :: uuid IS NULL
        OR (
            m_video.external_created_at < (
                SELECT
                    m_video.external_created_at
                FROM
                    m_video
                WHERE
                    m_video.public_id = $2 :: uuid
                LIMIT
                    1
            )
        )
        OR (
            m_video.external_created_at = (
                SELECT
                    m_video.external_created_at
                FROM
                    m_video
                WHERE
                    m_video.public_id = $2 :: uuid
                LIMIT
                    1
            )
            AND m_video.public_id < $2 :: uuid
        )
    )
ORDER BY
    m_video.external_created_at DESC,
    m_video.public_id DESC
LIMIT
    $3
`

type GetSubscribingChannelFeedParams struct {
	UserID     uuid.UUID
	Cursor     *uuid.UUID
	QueryLimit int32
}

type GetSubscribingChannelFeedRow struct {
	VideoID                   uuid.UUID
	ExternalVideoID           string
	ExternalVideoThumbnailUrl string
	ExternalTitle             string
	ExternalDescription       string
	ExternalCreatedAt         time.Time
	ExternalLengthSeconds     int
	LastWatchSeconds          int
	ChannelID                 uuid.UUID
	ExternalChannelID         string
	ExternalChannelIconUrl    string
	ExternalDisplayname       string
}

// ユーザーが登録しているチャンネルがだしている動画を最新順(public_id)で取得する。
func (q *Queries) GetSubscribingChannelFeed(ctx context.Context, arg GetSubscribingChannelFeedParams) ([]GetSubscribingChannelFeedRow, error) {
	rows, err := q.db.Query(ctx, getSubscribingChannelFeed, arg.UserID, arg.Cursor, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubscribingChannelFeedRow
	for rows.Next() {
		var i GetSubscribingChannelFeedRow
		if err := rows.Scan(
			&i.VideoID,
			&i.ExternalVideoID,
			&i.ExternalVideoThumbnailUrl,
			&i.ExternalTitle,
			&i.ExternalDescription,
			&i.ExternalCreatedAt,
			&i.ExternalLengthSeconds,
			&i.LastWatchSeconds,
			&i.ChannelID,
			&i.ExternalChannelID,
			&i.ExternalChannelIconUrl,
			&i.ExternalDisplayname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideoDetail = `-- name: GetVideoDetail :one
SELECT
    video.public_id AS id,
    video.external_id,
    video.external_title,
    video.external_description,
    video.external_thumbnail_url,
    channel.public_id AS channel_id,
    channel.external_id AS channel_external_id,
    channel.external_display_name,
    channel.external_custom_id AS channel_custom_id,
    channel.external_icon_url,
    channel.external_subscribers_count
FROM
    m_video video
INNER JOIN
    m_channel channel
ON
    video.m_channel_id = channel.m_channel_id
WHERE
    video.public_id = $1
LIMIT 1
`

type GetVideoDetailRow struct {
	ID                       uuid.UUID
	ExternalID               string
	ExternalTitle            string
	ExternalDescription      string
	ExternalThumbnailUrl     string
	ChannelID                uuid.UUID
	ChannelExternalID        string
	ExternalDisplayName      string
	ChannelCustomID          string
	ExternalIconUrl          string
	ExternalSubscribersCount int64
}

func (q *Queries) GetVideoDetail(ctx context.Context, videoID uuid.UUID) (GetVideoDetailRow, error) {
	row := q.db.QueryRow(ctx, getVideoDetail, videoID)
	var i GetVideoDetailRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ExternalTitle,
		&i.ExternalDescription,
		&i.ExternalThumbnailUrl,
		&i.ChannelID,
		&i.ChannelExternalID,
		&i.ExternalDisplayName,
		&i.ChannelCustomID,
		&i.ExternalIconUrl,
		&i.ExternalSubscribersCount,
	)
	return i, err
}

const saveVideo = `-- name: SaveVideo :one
INSERT INTO
    m_video (
        m_channel_id,
        external_id,
        external_title,
        external_description,
        fetched_at,
        external_created_at,
        external_thumbnail_url,
        external_length_seconds
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (external_id) DO UPDATE SET
    external_title = EXCLUDED.external_title,
    external_description = EXCLUDED.external_description,
    external_thumbnail_url = EXCLUDED.external_thumbnail_url,
    external_length_seconds = EXCLUDED.external_length_seconds,
    fetched_at = EXCLUDED.fetched_at,
    updated_at = CURRENT_TIMESTAMP
RETURNING m_video_id
`

type SaveVideoParams struct {
	MChannelID            int64
	ExternalID            string
	ExternalTitle         string
	ExternalDescription   string
	FetchedAt             time.Time
	ExternalCreatedAt     time.Time
	ExternalThumbnailUrl  string
	ExternalLengthSeconds int
}

func (q *Queries) SaveVideo(ctx context.Context, arg SaveVideoParams) (int64, error) {
	row := q.db.QueryRow(ctx, saveVideo,
		arg.MChannelID,
		arg.ExternalID,
		arg.ExternalTitle,
		arg.ExternalDescription,
		arg.FetchedAt,
		arg.ExternalCreatedAt,
		arg.ExternalThumbnailUrl,
		arg.ExternalLengthSeconds,
	)
	var m_video_id int64
	err := row.Scan(&m_video_id)
	return m_video_id, err
}
