// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getVideoDetail = `-- name: GetVideoDetail :one
SELECT
    video.public_id AS id,
    video.external_id,
    video.external_title,
    video.external_description,
    video.external_thumbnail_url,
    video.external_created_at,
    channel.public_id AS channel_id,
    channel.external_id AS channel_external_id,
    channel.external_display_name,
    channel.external_custom_id AS channel_custom_id,
    channel.external_icon_url,
    channel.external_subscribers_count,
    EXISTS (
        SELECT 1 FROM t_video_watched
        WHERE t_video_watched.m_video_id = video.m_video_id
            AND t_video_watched.m_user_id = (
                SELECT m_user.m_user_id FROM m_user WHERE m_user.public_id = $1 LIMIT 1
            )
    )::bool AS is_watched,
    EXISTS (
        SELECT 1 FROM m_playlist_video pv
        WHERE pv.m_playlist_id = (
                SELECT p.m_playlist_id FROM m_playlist p
                WHERE p.m_user_id = (
                        SELECT m_user.m_user_id FROM m_user WHERE m_user.public_id = $1 LIMIT 1
                    )
                    AND p.playlist_code = 2
                LIMIT 1
            )
            AND pv.m_video_id = video.m_video_id
    )::bool AS is_in_watch_later
FROM
    m_video video
    INNER JOIN m_channel channel ON video.m_channel_id = channel.m_channel_id
WHERE
    video.public_id = $2
LIMIT
    1
`

type GetVideoDetailParams struct {
	UserID  uuid.UUID
	VideoID uuid.UUID
}

type GetVideoDetailRow struct {
	ID                       uuid.UUID
	ExternalID               string
	ExternalTitle            string
	ExternalDescription      string
	ExternalThumbnailUrl     string
	ExternalCreatedAt        time.Time
	ChannelID                uuid.UUID
	ChannelExternalID        string
	ExternalDisplayName      string
	ChannelCustomID          string
	ExternalIconUrl          string
	ExternalSubscribersCount int64
	IsWatched                bool
	IsInWatchLater           bool
}

func (q *Queries) GetVideoDetail(ctx context.Context, arg GetVideoDetailParams) (GetVideoDetailRow, error) {
	row := q.db.QueryRow(ctx, getVideoDetail, arg.UserID, arg.VideoID)
	var i GetVideoDetailRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ExternalTitle,
		&i.ExternalDescription,
		&i.ExternalThumbnailUrl,
		&i.ExternalCreatedAt,
		&i.ChannelID,
		&i.ChannelExternalID,
		&i.ExternalDisplayName,
		&i.ChannelCustomID,
		&i.ExternalIconUrl,
		&i.ExternalSubscribersCount,
		&i.IsWatched,
		&i.IsInWatchLater,
	)
	return i, err
}

const listChannelVideoIDs = `-- name: ListChannelVideoIDs :many
SELECT
    m_video.public_id
FROM
    m_video
    INNER JOIN m_channel ON m_channel.m_channel_id = m_video.m_channel_id
WHERE
    m_channel.public_id = $1
    AND NOT EXISTS (
        SELECT 1 FROM t_video_watched
        WHERE t_video_watched.m_video_id = m_video.m_video_id
            AND t_video_watched.m_user_id = (
                SELECT m_user.m_user_id FROM m_user WHERE m_user.public_id = $2 LIMIT 1
            )
    )
ORDER BY
    m_video.public_id DESC
LIMIT
    $3
`

type ListChannelVideoIDsParams struct {
	ChannelID  uuid.UUID
	UserID     uuid.UUID
	QueryLimit int32
}

// 指定ユーザーが未視聴の、チャンネルの動画IDを最新順で取得する。
// feedへの挿入・削除で利用する。視聴済み動画は feed 側で既に削除されている前提。
func (q *Queries) ListChannelVideoIDs(ctx context.Context, arg ListChannelVideoIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listChannelVideoIDs, arg.ChannelID, arg.UserID, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var public_id uuid.UUID
		if err := rows.Scan(&public_id); err != nil {
			return nil, err
		}
		items = append(items, public_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelVideos = `-- name: ListChannelVideos :many
SELECT
    m_video.public_id,
    m_video.external_thumbnail_url,
    m_video.external_title,
    m_video.external_created_at,
    m_video.external_length_seconds,
    COALESCE((
        SELECT
            t_video_watch.watch_position_seconds
        FROM
            t_video_watch
        WHERE
            t_video_watch.m_user_id = (
                SELECT
                    m_user.m_user_id
                FROM
                    m_user
                WHERE
                    m_user.public_id = $1
                LIMIT
                    1
            )
            AND t_video_watch.m_video_id = m_video.m_video_id
        ORDER BY
            t_video_watch.m_user_id,
            t_video_watch.m_video_id,
            t_video_watch.watch_start_at DESC
        LIMIT
            1
    ), 0)::int AS last_watch_seconds,
    EXISTS (
        SELECT 1 FROM t_video_watched
        WHERE t_video_watched.m_video_id = m_video.m_video_id
            AND t_video_watched.m_user_id = (
                SELECT m_user.m_user_id FROM m_user WHERE m_user.public_id = $1 LIMIT 1
            )
    )::bool AS is_watched
FROM
    m_video
    INNER JOIN m_channel ON m_channel.m_channel_id = m_video.m_channel_id
WHERE
    m_channel.public_id = $2
    AND (
        $3::uuid IS NULL
        OR m_video.public_id < $3::uuid
    )
ORDER BY
    m_video.public_id DESC
LIMIT
    $4
`

type ListChannelVideosParams struct {
	UserID     uuid.UUID
	ChannelID  uuid.UUID
	Cursor     *uuid.UUID
	QueryLimit int32
}

type ListChannelVideosRow struct {
	PublicID              uuid.UUID
	ExternalThumbnailUrl  string
	ExternalTitle         string
	ExternalCreatedAt     time.Time
	ExternalLengthSeconds int
	LastWatchSeconds      int
	IsWatched             bool
}

func (q *Queries) ListChannelVideos(ctx context.Context, arg ListChannelVideosParams) ([]ListChannelVideosRow, error) {
	rows, err := q.db.Query(ctx, listChannelVideos,
		arg.UserID,
		arg.ChannelID,
		arg.Cursor,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelVideosRow
	for rows.Next() {
		var i ListChannelVideosRow
		if err := rows.Scan(
			&i.PublicID,
			&i.ExternalThumbnailUrl,
			&i.ExternalTitle,
			&i.ExternalCreatedAt,
			&i.ExternalLengthSeconds,
			&i.LastWatchSeconds,
			&i.IsWatched,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelVideosOlder = `-- name: ListChannelVideosOlder :many
SELECT
    m_video.public_id,
    m_video.external_thumbnail_url,
    m_video.external_title,
    m_video.external_created_at,
    m_video.external_length_seconds,
    COALESCE((
        SELECT
            t_video_watch.watch_position_seconds
        FROM
            t_video_watch
        WHERE
            t_video_watch.m_user_id = (
                SELECT
                    m_user.m_user_id
                FROM
                    m_user
                WHERE
                    m_user.public_id = $1
                LIMIT
                    1
            )
            AND t_video_watch.m_video_id = m_video.m_video_id
        ORDER BY
            t_video_watch.m_user_id,
            t_video_watch.m_video_id,
            t_video_watch.watch_start_at DESC
        LIMIT
            1
    ), 0)::int AS last_watch_seconds,
    EXISTS (
        SELECT 1 FROM t_video_watched
        WHERE t_video_watched.m_video_id = m_video.m_video_id
            AND t_video_watched.m_user_id = (
                SELECT m_user.m_user_id FROM m_user WHERE m_user.public_id = $1 LIMIT 1
            )
    )::bool AS is_watched
FROM
    m_video
    INNER JOIN m_channel ON m_channel.m_channel_id = m_video.m_channel_id
WHERE
    m_channel.public_id = $2
    AND (
        $3::uuid IS NULL
        OR m_video.public_id > $3::uuid
    )
ORDER BY
    m_video.public_id ASC
LIMIT
    $4
`

type ListChannelVideosOlderParams struct {
	UserID     uuid.UUID
	ChannelID  uuid.UUID
	Cursor     *uuid.UUID
	QueryLimit int32
}

type ListChannelVideosOlderRow struct {
	PublicID              uuid.UUID
	ExternalThumbnailUrl  string
	ExternalTitle         string
	ExternalCreatedAt     time.Time
	ExternalLengthSeconds int
	LastWatchSeconds      int
	IsWatched             bool
}

func (q *Queries) ListChannelVideosOlder(ctx context.Context, arg ListChannelVideosOlderParams) ([]ListChannelVideosOlderRow, error) {
	rows, err := q.db.Query(ctx, listChannelVideosOlder,
		arg.UserID,
		arg.ChannelID,
		arg.Cursor,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelVideosOlderRow
	for rows.Next() {
		var i ListChannelVideosOlderRow
		if err := rows.Scan(
			&i.PublicID,
			&i.ExternalThumbnailUrl,
			&i.ExternalTitle,
			&i.ExternalCreatedAt,
			&i.ExternalLengthSeconds,
			&i.LastWatchSeconds,
			&i.IsWatched,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionFeed = `-- name: ListSubscriptionFeed :many
SELECT
    m_video.public_id AS video_id
FROM
    m_video
    INNER JOIN m_user_subscribing_channel ON m_video.m_channel_id = m_user_subscribing_channel.m_channel_id
WHERE
    m_user_subscribing_channel.m_user_id = (
        SELECT
            m_user.m_user_id
        FROM
            m_user
        WHERE
            m_user.public_id = $1
        LIMIT
            1
    )
    AND NOT EXISTS (
        SELECT 1 FROM t_video_watched
        WHERE t_video_watched.m_user_id = m_user_subscribing_channel.m_user_id
            AND t_video_watched.m_video_id = m_video.m_video_id
    )
ORDER BY
    m_video.public_id DESC
LIMIT
    $2
`

type ListSubscriptionFeedParams struct {
	UserID     uuid.UUID
	QueryLimit int32
}

// ユーザーが登録しているチャンネルがだしている未視聴動画IDを最新順(public_id)で取得する。
// Redis feedの補充で利用する。hydrateは ListVideoFeedByIDs で別途行う。
func (q *Queries) ListSubscriptionFeed(ctx context.Context, arg ListSubscriptionFeedParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSubscriptionFeed, arg.UserID, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var video_id uuid.UUID
		if err := rows.Scan(&video_id); err != nil {
			return nil, err
		}
		items = append(items, video_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoFeedByIDs = `-- name: ListVideoFeedByIDs :many
SELECT
    m_video.public_id AS video_id,
    m_video.external_thumbnail_url AS external_video_thumbnail_url,
    m_video.external_title AS external_title,
    m_video.external_created_at AS external_created_at,
    m_video.external_length_seconds AS external_length_seconds,
    COALESCE((
        SELECT
            t_video_watch.watch_position_seconds
        FROM
            t_video_watch
        WHERE
            t_video_watch.m_user_id = (
                SELECT
                    m_user.m_user_id
                FROM
                    m_user
                WHERE
                    m_user.public_id = $1
                LIMIT
                    1
            )
            AND t_video_watch.m_video_id = m_video.m_video_id
        ORDER BY
            t_video_watch.m_user_id,
            t_video_watch.m_video_id,
            t_video_watch.watch_start_at DESC
        LIMIT
            1
    ), 0)::int AS last_watch_seconds,
    m_channel.public_id AS channel_id,
    m_channel.external_icon_url AS external_channel_icon_url,
    m_channel.external_display_name AS external_displayname
FROM
    m_video
    INNER JOIN m_channel ON m_channel.m_channel_id = m_video.m_channel_id
WHERE
    m_video.public_id = ANY($2::uuid[])
ORDER BY
    array_position($2::uuid[], m_video.public_id)
`

type ListVideoFeedByIDsParams struct {
	UserID   uuid.UUID
	VideoIds []uuid.UUID
}

type ListVideoFeedByIDsRow struct {
	VideoID                   uuid.UUID
	ExternalVideoThumbnailUrl string
	ExternalTitle             string
	ExternalCreatedAt         time.Time
	ExternalLengthSeconds     int
	LastWatchSeconds          int
	ChannelID                 uuid.UUID
	ExternalChannelIconUrl    string
	ExternalDisplayname       string
}

// 指定されたvideo_idsのフィード用データを、入力順序を保持して取得する。
// Redisフィードのハイドレーション用。視聴済みフィルタはRedis側で管理されているためここでは行わない。
func (q *Queries) ListVideoFeedByIDs(ctx context.Context, arg ListVideoFeedByIDsParams) ([]ListVideoFeedByIDsRow, error) {
	rows, err := q.db.Query(ctx, listVideoFeedByIDs, arg.UserID, arg.VideoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVideoFeedByIDsRow
	for rows.Next() {
		var i ListVideoFeedByIDsRow
		if err := rows.Scan(
			&i.VideoID,
			&i.ExternalVideoThumbnailUrl,
			&i.ExternalTitle,
			&i.ExternalCreatedAt,
			&i.ExternalLengthSeconds,
			&i.LastWatchSeconds,
			&i.ChannelID,
			&i.ExternalChannelIconUrl,
			&i.ExternalDisplayname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVideo = `-- name: UpsertVideo :one
INSERT INTO
    m_video (
        m_channel_id,
        external_id,
        external_title,
        external_description,
        fetched_at,
        external_created_at,
        external_thumbnail_url,
        external_length_seconds,
        public_id
    )
SELECT
    (
        SELECT
            channel.m_channel_id
        FROM
            m_channel channel
        WHERE
            channel.public_id = $1
        LIMIT
            1
    ),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
ON CONFLICT (external_id) DO UPDATE SET
    external_title = EXCLUDED.external_title,
    external_description = EXCLUDED.external_description,
    external_thumbnail_url = EXCLUDED.external_thumbnail_url,
    external_length_seconds = EXCLUDED.external_length_seconds,
    external_created_at = EXCLUDED.external_created_at,
    fetched_at = EXCLUDED.fetched_at,
    updated_at = CURRENT_TIMESTAMP
RETURNING
    m_video_id, public_id
`

type UpsertVideoParams struct {
	ChannelID             uuid.UUID
	ExternalID            string
	ExternalTitle         string
	ExternalDescription   string
	FetchedAt             time.Time
	ExternalCreatedAt     time.Time
	ExternalThumbnailUrl  string
	ExternalLengthSeconds int
	ID                    uuid.UUID
}

type UpsertVideoRow struct {
	MVideoID int64
	PublicID uuid.UUID
}

func (q *Queries) UpsertVideo(ctx context.Context, arg UpsertVideoParams) (UpsertVideoRow, error) {
	row := q.db.QueryRow(ctx, upsertVideo,
		arg.ChannelID,
		arg.ExternalID,
		arg.ExternalTitle,
		arg.ExternalDescription,
		arg.FetchedAt,
		arg.ExternalCreatedAt,
		arg.ExternalThumbnailUrl,
		arg.ExternalLengthSeconds,
		arg.ID,
	)
	var i UpsertVideoRow
	err := row.Scan(&i.MVideoID, &i.PublicID)
	return i, err
}
