services:
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/server.crt:/etc/nginx/certs/server.crt:ro
      - ./nginx/server.key:/etc/nginx/certs/server.key:ro
    depends_on:
      server:
        condition: service_started
      frontend:
        condition: service_started
  server:
    build:
      target: dev
    volumes:
    - ./backend:/src
    - ./shared:/src/shared:ro
    secrets:
      - db-password
      - oidc-google-client-secret
      - jwt-private
      - jwt-public
      - google-oidc-secret
    env_file:
      - backend/.env
  frontend:
    build:
      target: dev
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules 
      - ./shared:/usr/src/app/shared:ro
    environment:
      NODE_ENV: development
    expose:
      - "3000"
  db:
   restart: always
   user: postgres
   secrets:
     - db-password
   volumes:
     - db-data:/var/lib/postgresql
   environment:
     - POSTGRES_DB=example
     - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
   expose:
     - 5432
volumes:
 db-data:
secrets:
 db-password:
   file: backend/password.txt
 oidc-google-client-secret:
   file: backend/oidc_secret.txt
 jwt-private:
   file: backend/jwt_private.pem
 jwt-public:
   file: backend/jwt_public.pem
 google-oidc-secret:
   file: backend/google_oidc_secret.txt
