services:
  backend:
    build:
      context: ./backend
    expose:
      - "8080"
    env_file:
      - .env
    secrets:
      - db-password
      - oidc-google-client-secret
      - jwt-private
      - jwt-public
      - google-oidc-secret
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend-dist:/output
    restart: "no"

volumes:
  frontend-dist:
    external: true
    name: anti-yt-frontend-dist

secrets:
  db-password:
    file: ./secrets/db-password.txt
  oidc-google-client-secret:
    file: ./secrets/oidc_secret.txt
  jwt-private:
    file: ./secrets/jwt_private.pem
  jwt-public:
    file: ./secrets/jwt_public.pem
  google-oidc-secret:
    file: ./secrets/google_oidc_secret.txt

networks:
  app-network:
    external: true
    name: anti-yt-network
