services:
  server:
    build:
      context: backend
      dockerfile: "Dockerfile"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: frontend
      dockerfile: "Dockerfile"
  db:
    image: "postgres:18.1-alpine3.23"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
