// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateUserScreenTimeRanges implements pgx.CopyFromSource.
type iteratorForCreateUserScreenTimeRanges struct {
	rows                 []CreateUserScreenTimeRangesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateUserScreenTimeRanges) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateUserScreenTimeRanges) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].MUserID,
		r.rows[0].ScreenTimeRangeStart,
		r.rows[0].ScreenTimeRangeEnd,
	}, nil
}

func (r iteratorForCreateUserScreenTimeRanges) Err() error {
	return nil
}

func (q *Queries) CreateUserScreenTimeRanges(ctx context.Context, arg []CreateUserScreenTimeRangesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"m_user_screen_time_range"}, []string{"m_user_id", "screen_time_range_start", "screen_time_range_end"}, &iteratorForCreateUserScreenTimeRanges{rows: arg})
}
