// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForSaveUserScreenTimeRanges implements pgx.CopyFromSource.
type iteratorForSaveUserScreenTimeRanges struct {
	rows                 []SaveUserScreenTimeRangesParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveUserScreenTimeRanges) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveUserScreenTimeRanges) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].MUserID,
		r.rows[0].ScreenTimeRangeStart,
		r.rows[0].ScreenTimeRangeEnd,
	}, nil
}

func (r iteratorForSaveUserScreenTimeRanges) Err() error {
	return nil
}

// NOTE: err == nilの場合はlen(param)
func (q *Queries) SaveUserScreenTimeRanges(ctx context.Context, arg []SaveUserScreenTimeRangesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"m_user_screen_time_range"}, []string{"m_user_id", "screen_time_range_start", "screen_time_range_end"}, &iteratorForSaveUserScreenTimeRanges{rows: arg})
}
