// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getTotalWatchSeconds = `-- name: GetTotalWatchSeconds :one
SELECT COALESCE(EXTRACT(EPOCH FROM SUM(t_video_watch.watch_end_at - t_video_watch.watch_start_at)), 0)::int FROM t_video_watch
WHERE t_video_watch.m_user_id = (SELECT m_user.m_user_id FROM m_user WHERE m_user.public_id = $1)
    AND CURRENT_DATE <= t_video_watch.watch_start_at AND t_video_watch.watch_start_at < CURRENT_DATE + INTERVAL '1 day'
`

// m_user.public_idから、そのユーザーが今日視聴していた合計時間(seconds)を返す。
// その日に一本も動画を視聴していない場合は0を返します。
func (q *Queries) GetTotalWatchSeconds(ctx context.Context, publicID uuid.UUID) (int, error) {
	row := q.db.QueryRow(ctx, getTotalWatchSeconds, publicID)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}
