// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HSearch struct {
	HSearchID     int64
	MUserID       int64
	SearchKeyword string
	SearchedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type HUser struct {
	HUserID                int64
	MUserAuthorizationID   int64
	DisplayName            string
	LanguageCode           string
	DailyScreenTimeSeconds int32
	JoinedAt               pgtype.Timestamptz
	LeftAt                 pgtype.Timestamptz
	LeaveReasonCode        int32
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	PublicID               pgtype.UUID
}

type MChannel struct {
	MChannelID               int64
	ExternalID               string
	ExternalDisplayName      string
	ExternalCustomID         string
	ExternalIconUrl          string
	ExternalDescription      string
	ExternalSubscribersCount int64
	ExternalCreatedAt        pgtype.Timestamptz
	FetchedAt                pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	PublicID                 pgtype.UUID
}

type MComment struct {
	MCommentID              int64
	MVideoID                int64
	ExternalID              string
	ExternalContent         string
	ExternalLikeCount       int64
	ExternalUserID          string
	ExternalUserDisplayName string
	ExternalUserCustomID    string
	ExternalEditedFlg       bool
	ExternalCreatedAt       pgtype.Timestamptz
	FetchedAt               pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	PublicID                pgtype.UUID
}

type MPlaylist struct {
	MPlaylistID                     int64
	MUserID                         int64
	VisibilityCode                  int32
	PlaylistTitle                   string
	PlaylistCode                    int32
	VideoCount                      int32
	PlaylistTotalVideoLengthSeconds int32
	CreatedAt                       pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
	PublicID                        pgtype.UUID
}

type MPlaylistVideo struct {
	MPlaylistVideoID int64
	MPlaylistID      int64
	MVideoID         int64
	PlaylistPosition int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type MRefreshToken struct {
	MRefreshTokenID      int64
	MUserAuthorizationID int64
	TokenHash            string
	Generation           int32
	IpAddress            string
	DeviceFingerprint    string
	UserAgent            string
	CountryCode          string
	CityName             string
	BrowserName          string
	DeviceType           string
	ExpiresAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type MUser struct {
	MUserID                int64
	MUserAuthorizationID   int64
	DisplayName            string
	LanguageCode           string
	DailyScreenTimeSeconds int32
	JoinedAt               pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	PublicID               pgtype.UUID
}

type MUserAuthorization struct {
	MUserAuthorizationID int64
	Issuer               string
	Sub                  string
	LastLoggedInAt       pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type MUserScreenTimeRange struct {
	MUserScreenTimeRangeID int64
	MUserID                int64
	ScreenTimeRangeStart   pgtype.Time
	ScreenTimeRangeEnd     pgtype.Time
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	PublicID               pgtype.UUID
}

type MUserSubscribingChannel struct {
	MUserSubscribingChannelID int64
	MUserID                   int64
	MChannelID                int64
	SubscribedAt              pgtype.Timestamptz
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	PublicID                  pgtype.UUID
}

type MVideo struct {
	MVideoID            int64
	MChannelID          int64
	ExternalID          string
	ExternalTitle       string
	ExternalDescription string
	ExternalLikeCount   int64
	ExternalWatchCount  int64
	LengthSeconds       int64
	FetchedAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	PublicID            pgtype.UUID
}

type SMonthlyVideoWatch struct {
	SMonthlyVideoWatchID int64
	MUserID              int64
	AiSummaryTitle       string
	AiSummaryDescription string
	AiModel              string
	GeneratedAt          pgtype.Timestamptz
	TargetMonth          pgtype.Date
	WMonthlyVideoWatchID int64
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	PublicID             pgtype.UUID
}

type TJtiBlacklist struct {
	Jti       pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

type TVideoWatch struct {
	TVideoWatchID        int64
	MUserID              int64
	MVideoID             int64
	WatchStartAt         pgtype.Timestamptz
	WatchEndAt           pgtype.Timestamptz
	WatchPositionSeconds int32
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	PublicID             pgtype.UUID
}

type WMonthlyVideoWatch struct {
	WMonthlyVideoWatchID int64
	MUserID              int64
	BatchStatusCode      int32
	AiModel              string
	StartedAt            pgtype.Timestamptz
	FinishedAt           pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}
