// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
	"time"

	"github.com/brqnko/anti-yt/backend/internal/core/database"
	"github.com/google/uuid"
)

const countUsersByAuthorization = `-- name: CountUsersByAuthorization :one
WITH auth AS (
    SELECT m_user_authorization_id
    FROM m_user_authorization
    WHERE m_user_authorization.public_id = $1
    LIMIT 1
)
SELECT
    (SELECT COUNT(*) FROM h_user WHERE m_user_authorization_id = (SELECT auth.m_user_authorization_id FROM auth)) +
    (SELECT COUNT(*) FROM m_user WHERE m_user_authorization_id = (SELECT auth.m_user_authorization_id FROM auth))
    AS total_count
`

// m_user_authorization_idに紐づくh_userとm_userの数を数える
func (q *Queries) CountUsersByAuthorization(ctx context.Context, publicID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUsersByAuthorization, publicID)
	var total_count int32
	err := row.Scan(&total_count)
	return total_count, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT m_user.m_user_id, m_user.joined_at, m_user.display_name, m_user.daily_screen_time_seconds, m_user.language_code FROM m_user
WHERE m_user.public_id = $1
LIMIT 1
`

type GetUserProfileRow struct {
	MUserID                int64
	JoinedAt               time.Time
	DisplayName            string
	DailyScreenTimeSeconds int
	LanguageCode           string
}

// m_user.public_idから、ユーザーのプロファイルを取得する。
func (q *Queries) GetUserProfile(ctx context.Context, userPublicID uuid.UUID) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userPublicID)
	var i GetUserProfileRow
	err := row.Scan(
		&i.MUserID,
		&i.JoinedAt,
		&i.DisplayName,
		&i.DailyScreenTimeSeconds,
		&i.LanguageCode,
	)
	return i, err
}

const getUserScreenTimeRanges = `-- name: GetUserScreenTimeRanges :many
SELECT m_user_screen_time_range.screen_time_range_start, m_user_screen_time_range.screen_time_range_end, m_user_screen_time_range.public_id FROM m_user_screen_time_range
WHERE m_user_screen_time_range.m_user_id = (SELECT m_user.m_user_id FROM m_user WHERE m_user.public_id = $1)
ORDER BY m_user_screen_time_range.screen_time_range_start
`

type GetUserScreenTimeRangesRow struct {
	ScreenTimeRangeStart database.Seconds
	ScreenTimeRangeEnd   database.Seconds
	PublicID             uuid.UUID
}

// m_user.public_idのユーザーの視聴制限範囲を取得する。
func (q *Queries) GetUserScreenTimeRanges(ctx context.Context, userPublicID uuid.UUID) ([]GetUserScreenTimeRangesRow, error) {
	rows, err := q.db.Query(ctx, getUserScreenTimeRanges, userPublicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserScreenTimeRangesRow
	for rows.Next() {
		var i GetUserScreenTimeRangesRow
		if err := rows.Scan(&i.ScreenTimeRangeStart, &i.ScreenTimeRangeEnd, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeScreenTimeRangesByUserId = `-- name: RemoveScreenTimeRangesByUserId :exec
DELETE FROM m_user_screen_time_range WHERE m_user_screen_time_range.m_user_id = $1
`

// m_user.m_user_idから、そのユーザーのスクリーン時間の範囲制限を削除する
func (q *Queries) RemoveScreenTimeRangesByUserId(ctx context.Context, mUserID int64) error {
	_, err := q.db.Exec(ctx, removeScreenTimeRangesByUserId, mUserID)
	return err
}

const removeUser = `-- name: RemoveUser :exec
WITH deleted AS (
    DELETE FROM m_user WHERE m_user.public_id = $2
    RETURNING m_user.m_user_id, m_user.m_user_authorization_id, m_user.display_name, m_user.language_code,
    m_user.daily_screen_time_seconds, m_user.joined_at, m_user.public_id
)
INSERT INTO h_user(h_user_id, m_user_authorization_id, display_name, language_code, daily_screen_time_seconds, joined_at, leave_reason_code, public_id) SELECT
deleted.m_user_id AS h_user_id,
deleted.m_user_authorization_id AS m_user_authorization_id,
deleted.display_name AS display_name,
deleted.language_code AS language_code,
deleted.daily_screen_time_seconds AS daily_screen_time_seconds,
deleted.joined_at AS joined_at,
$1 AS leave_reason_code,
deleted.public_id AS public_id
FROM deleted
`

type RemoveUserParams struct {
	LeaveReasonCode int
	UserPublicID    uuid.UUID
}

// m_userをh_userに移動します。
func (q *Queries) RemoveUser(ctx context.Context, arg RemoveUserParams) error {
	_, err := q.db.Exec(ctx, removeUser, arg.LeaveReasonCode, arg.UserPublicID)
	return err
}

const saveUser = `-- name: SaveUser :one
INSERT INTO m_user (m_user_authorization_id, display_name, language_code, daily_screen_time_seconds)
SELECT m_user_authorization.m_user_authorization_id, $1, $2, $3 FROM m_user_authorization
WHERE m_user_authorization.public_id = $4 LIMIT 1
RETURNING m_user_id, joined_at, public_id
`

type SaveUserParams struct {
	DisplayName               string
	LanguageCode              string
	DailyScreenTimeSeconds    int
	UserAuthorizationPublicID uuid.UUID
}

type SaveUserRow struct {
	MUserID  int64
	JoinedAt time.Time
	PublicID uuid.UUID
}

// 新しいユーザーを挿入する。
func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) (SaveUserRow, error) {
	row := q.db.QueryRow(ctx, saveUser,
		arg.DisplayName,
		arg.LanguageCode,
		arg.DailyScreenTimeSeconds,
		arg.UserAuthorizationPublicID,
	)
	var i SaveUserRow
	err := row.Scan(&i.MUserID, &i.JoinedAt, &i.PublicID)
	return i, err
}

type SaveUserScreenTimeRangesParams struct {
	MUserID              int64
	ScreenTimeRangeStart database.Seconds
	ScreenTimeRangeEnd   database.Seconds
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE m_user SET
    display_name = COALESCE($1, m_user.display_name),
    daily_screen_time_seconds = COALESCE($2, m_user.daily_screen_time_seconds),
    language_code = COALESCE($3, m_user.language_code),
    updated_at = CURRENT_TIMESTAMP
WHERE m_user.public_id = $4
RETURNING m_user.m_user_id, m_user.public_id, m_user.joined_at, m_user.display_name, m_user.daily_screen_time_seconds, m_user.language_code
`

type UpdateUserProfileParams struct {
	NewDisplayName            *string
	NewDailyScreenTimeSeconds *int
	NewLanguageCode           *string
	UserPublicID              uuid.UUID
}

type UpdateUserProfileRow struct {
	MUserID                int64
	PublicID               uuid.UUID
	JoinedAt               time.Time
	DisplayName            string
	DailyScreenTimeSeconds int
	LanguageCode           string
}

// m_user.public_idから、ユーザーのプロファイルを更新する
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.NewDisplayName,
		arg.NewDailyScreenTimeSeconds,
		arg.NewLanguageCode,
		arg.UserPublicID,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.MUserID,
		&i.PublicID,
		&i.JoinedAt,
		&i.DisplayName,
		&i.DailyScreenTimeSeconds,
		&i.LanguageCode,
	)
	return i, err
}
