// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO m_user (m_user_authorization_id, display_name, language_code, daily_screen_time_seconds)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
RETURNING m_user_id, display_name, language_code, joined_at, daily_screen_time_seconds, public_id
`

type CreateUserParams struct {
	MUserAuthorizationID   int64
	DisplayName            string
	LanguageCode           string
	DailyScreenTimeSeconds int32
}

type CreateUserRow struct {
	MUserID                int64
	DisplayName            string
	LanguageCode           string
	JoinedAt               time.Time
	DailyScreenTimeSeconds int32
	PublicID               uuid.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.MUserAuthorizationID,
		arg.DisplayName,
		arg.LanguageCode,
		arg.DailyScreenTimeSeconds,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.MUserID,
		&i.DisplayName,
		&i.LanguageCode,
		&i.JoinedAt,
		&i.DailyScreenTimeSeconds,
		&i.PublicID,
	)
	return i, err
}

type CreateUserScreenTimeRangesParams struct {
	MUserID              int64
	ScreenTimeRangeStart pgtype.Time
	ScreenTimeRangeEnd   pgtype.Time
}

const getUserScreenTimeRanges = `-- name: GetUserScreenTimeRanges :many
SELECT m_user_id, public_id, screen_time_range_start, screen_time_range_end FROM m_user_screen_time_range
`

type GetUserScreenTimeRangesRow struct {
	MUserID              int64
	PublicID             uuid.UUID
	ScreenTimeRangeStart pgtype.Time
	ScreenTimeRangeEnd   pgtype.Time
}

func (q *Queries) GetUserScreenTimeRanges(ctx context.Context) ([]GetUserScreenTimeRangesRow, error) {
	rows, err := q.db.Query(ctx, getUserScreenTimeRanges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserScreenTimeRangesRow
	for rows.Next() {
		var i GetUserScreenTimeRangesRow
		if err := rows.Scan(
			&i.MUserID,
			&i.PublicID,
			&i.ScreenTimeRangeStart,
			&i.ScreenTimeRangeEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
