// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth_test

import (
	"context"
	"github.com/brqnko/anti-yt/backend/internal/core/oidc"
	"sync"
)

// Ensure, that GoogleOIDCServiceMock does implement oidc.GoogleOIDCService.
// If this is not the case, regenerate this file with moq.
var _ oidc.GoogleOIDCService = &GoogleOIDCServiceMock{}

// GoogleOIDCServiceMock is a mock implementation of oidc.GoogleOIDCService.
//
//	func TestSomethingThatUsesGoogleOIDCService(t *testing.T) {
//
//		// make and configure a mocked oidc.GoogleOIDCService
//		mockedGoogleOIDCService := &GoogleOIDCServiceMock{
//			AuthCodeURLFunc: func(state string) string {
//				panic("mock out the AuthCodeURL method")
//			},
//			ExchangeAndVerifyFunc: func(ctx context.Context, code string) (string, error) {
//				panic("mock out the ExchangeAndVerify method")
//			},
//		}
//
//		// use mockedGoogleOIDCService in code that requires oidc.GoogleOIDCService
//		// and then make assertions.
//
//	}
type GoogleOIDCServiceMock struct {
	// AuthCodeURLFunc mocks the AuthCodeURL method.
	AuthCodeURLFunc func(state string) string

	// ExchangeAndVerifyFunc mocks the ExchangeAndVerify method.
	ExchangeAndVerifyFunc func(ctx context.Context, code string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// AuthCodeURL holds details about calls to the AuthCodeURL method.
		AuthCodeURL []struct {
			// State is the state argument value.
			State string
		}
		// ExchangeAndVerify holds details about calls to the ExchangeAndVerify method.
		ExchangeAndVerify []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Code is the code argument value.
			Code string
		}
	}
	lockAuthCodeURL       sync.RWMutex
	lockExchangeAndVerify sync.RWMutex
}

// AuthCodeURL calls AuthCodeURLFunc.
func (mock *GoogleOIDCServiceMock) AuthCodeURL(state string) string {
	if mock.AuthCodeURLFunc == nil {
		panic("GoogleOIDCServiceMock.AuthCodeURLFunc: method is nil but GoogleOIDCService.AuthCodeURL was just called")
	}
	callInfo := struct {
		State string
	}{
		State: state,
	}
	mock.lockAuthCodeURL.Lock()
	mock.calls.AuthCodeURL = append(mock.calls.AuthCodeURL, callInfo)
	mock.lockAuthCodeURL.Unlock()
	return mock.AuthCodeURLFunc(state)
}

// AuthCodeURLCalls gets all the calls that were made to AuthCodeURL.
// Check the length with:
//
//	len(mockedGoogleOIDCService.AuthCodeURLCalls())
func (mock *GoogleOIDCServiceMock) AuthCodeURLCalls() []struct {
	State string
} {
	var calls []struct {
		State string
	}
	mock.lockAuthCodeURL.RLock()
	calls = mock.calls.AuthCodeURL
	mock.lockAuthCodeURL.RUnlock()
	return calls
}

// ExchangeAndVerify calls ExchangeAndVerifyFunc.
func (mock *GoogleOIDCServiceMock) ExchangeAndVerify(ctx context.Context, code string) (string, error) {
	if mock.ExchangeAndVerifyFunc == nil {
		panic("GoogleOIDCServiceMock.ExchangeAndVerifyFunc: method is nil but GoogleOIDCService.ExchangeAndVerify was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Code string
	}{
		Ctx:  ctx,
		Code: code,
	}
	mock.lockExchangeAndVerify.Lock()
	mock.calls.ExchangeAndVerify = append(mock.calls.ExchangeAndVerify, callInfo)
	mock.lockExchangeAndVerify.Unlock()
	return mock.ExchangeAndVerifyFunc(ctx, code)
}

// ExchangeAndVerifyCalls gets all the calls that were made to ExchangeAndVerify.
// Check the length with:
//
//	len(mockedGoogleOIDCService.ExchangeAndVerifyCalls())
func (mock *GoogleOIDCServiceMock) ExchangeAndVerifyCalls() []struct {
	Ctx  context.Context
	Code string
} {
	var calls []struct {
		Ctx  context.Context
		Code string
	}
	mock.lockExchangeAndVerify.RLock()
	calls = mock.calls.ExchangeAndVerify
	mock.lockExchangeAndVerify.RUnlock()
	return calls
}
