// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package channel

import (
	"context"
	"github.com/brqnko/anti-yt/backend/internal/core/youtube_d"
	"sync"
)

// Ensure, that ServiceMock does implement youtube_d.Service.
// If this is not the case, regenerate this file with moq.
var _ youtube_d.Service = &ServiceMock{}

// ServiceMock is a mock implementation of youtube_d.Service.
//
//	func TestSomethingThatUsesService(t *testing.T) {
//
//		// make and configure a mocked youtube_d.Service
//		mockedService := &ServiceMock{
//			FetchChannelDetailFunc: func(ctx context.Context, channelIDs []youtube_d.ChannelID) (map[youtube_d.ChannelID]youtube_d.Channel, error) {
//				panic("mock out the FetchChannelDetail method")
//			},
//			FetchChannelDetailByIDOrHandleFunc: func(ctx context.Context, channelID string) (youtube_d.Channel, error) {
//				panic("mock out the FetchChannelDetailByIDOrHandle method")
//			},
//			FetchPlaylistVideoIDsFunc: func(ctx context.Context, playlistID string, pageToken string) ([]youtube_d.VideoID, string, error) {
//				panic("mock out the FetchPlaylistVideoIDs method")
//			},
//			FetchRSSFeedFunc: func(ctx context.Context, channelID youtube_d.ChannelID) ([]youtube_d.VideoID, error) {
//				panic("mock out the FetchRSSFeed method")
//			},
//			FetchVideoDetailFunc: func(ctx context.Context, videoIDs []youtube_d.VideoID) (map[youtube_d.VideoID]youtube_d.Video, error) {
//				panic("mock out the FetchVideoDetail method")
//			},
//			SearchVideoIDsFunc: func(ctx context.Context, query string, pageToken string, language *string) ([]youtube_d.VideoID, string, error) {
//				panic("mock out the SearchVideoIDs method")
//			},
//		}
//
//		// use mockedService in code that requires youtube_d.Service
//		// and then make assertions.
//
//	}
type ServiceMock struct {
	// FetchChannelDetailFunc mocks the FetchChannelDetail method.
	FetchChannelDetailFunc func(ctx context.Context, channelIDs []youtube_d.ChannelID) (map[youtube_d.ChannelID]youtube_d.Channel, error)

	// FetchChannelDetailByIDOrHandleFunc mocks the FetchChannelDetailByIDOrHandle method.
	FetchChannelDetailByIDOrHandleFunc func(ctx context.Context, channelID string) (youtube_d.Channel, error)

	// FetchPlaylistVideoIDsFunc mocks the FetchPlaylistVideoIDs method.
	FetchPlaylistVideoIDsFunc func(ctx context.Context, playlistID string, pageToken string) ([]youtube_d.VideoID, string, error)

	// FetchRSSFeedFunc mocks the FetchRSSFeed method.
	FetchRSSFeedFunc func(ctx context.Context, channelID youtube_d.ChannelID) ([]youtube_d.VideoID, error)

	// FetchVideoDetailFunc mocks the FetchVideoDetail method.
	FetchVideoDetailFunc func(ctx context.Context, videoIDs []youtube_d.VideoID) (map[youtube_d.VideoID]youtube_d.Video, error)

	// SearchVideoIDsFunc mocks the SearchVideoIDs method.
	SearchVideoIDsFunc func(ctx context.Context, query string, pageToken string, language *string) ([]youtube_d.VideoID, string, error)

	// calls tracks calls to the methods.
	calls struct {
		// FetchChannelDetail holds details about calls to the FetchChannelDetail method.
		FetchChannelDetail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChannelIDs is the channelIDs argument value.
			ChannelIDs []youtube_d.ChannelID
		}
		// FetchChannelDetailByIDOrHandle holds details about calls to the FetchChannelDetailByIDOrHandle method.
		FetchChannelDetailByIDOrHandle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChannelID is the channelID argument value.
			ChannelID string
		}
		// FetchPlaylistVideoIDs holds details about calls to the FetchPlaylistVideoIDs method.
		FetchPlaylistVideoIDs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PlaylistID is the playlistID argument value.
			PlaylistID string
			// PageToken is the pageToken argument value.
			PageToken string
		}
		// FetchRSSFeed holds details about calls to the FetchRSSFeed method.
		FetchRSSFeed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChannelID is the channelID argument value.
			ChannelID youtube_d.ChannelID
		}
		// FetchVideoDetail holds details about calls to the FetchVideoDetail method.
		FetchVideoDetail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VideoIDs is the videoIDs argument value.
			VideoIDs []youtube_d.VideoID
		}
		// SearchVideoIDs holds details about calls to the SearchVideoIDs method.
		SearchVideoIDs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// PageToken is the pageToken argument value.
			PageToken string
			// Language is the language argument value.
			Language *string
		}
	}
	lockFetchChannelDetail             sync.RWMutex
	lockFetchChannelDetailByIDOrHandle sync.RWMutex
	lockFetchPlaylistVideoIDs          sync.RWMutex
	lockFetchRSSFeed                   sync.RWMutex
	lockFetchVideoDetail               sync.RWMutex
	lockSearchVideoIDs                 sync.RWMutex
}

// FetchChannelDetail calls FetchChannelDetailFunc.
func (mock *ServiceMock) FetchChannelDetail(ctx context.Context, channelIDs []youtube_d.ChannelID) (map[youtube_d.ChannelID]youtube_d.Channel, error) {
	if mock.FetchChannelDetailFunc == nil {
		panic("ServiceMock.FetchChannelDetailFunc: method is nil but Service.FetchChannelDetail was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ChannelIDs []youtube_d.ChannelID
	}{
		Ctx:        ctx,
		ChannelIDs: channelIDs,
	}
	mock.lockFetchChannelDetail.Lock()
	mock.calls.FetchChannelDetail = append(mock.calls.FetchChannelDetail, callInfo)
	mock.lockFetchChannelDetail.Unlock()
	return mock.FetchChannelDetailFunc(ctx, channelIDs)
}

// FetchChannelDetailCalls gets all the calls that were made to FetchChannelDetail.
// Check the length with:
//
//	len(mockedService.FetchChannelDetailCalls())
func (mock *ServiceMock) FetchChannelDetailCalls() []struct {
	Ctx        context.Context
	ChannelIDs []youtube_d.ChannelID
} {
	var calls []struct {
		Ctx        context.Context
		ChannelIDs []youtube_d.ChannelID
	}
	mock.lockFetchChannelDetail.RLock()
	calls = mock.calls.FetchChannelDetail
	mock.lockFetchChannelDetail.RUnlock()
	return calls
}

// FetchChannelDetailByIDOrHandle calls FetchChannelDetailByIDOrHandleFunc.
func (mock *ServiceMock) FetchChannelDetailByIDOrHandle(ctx context.Context, channelID string) (youtube_d.Channel, error) {
	if mock.FetchChannelDetailByIDOrHandleFunc == nil {
		panic("ServiceMock.FetchChannelDetailByIDOrHandleFunc: method is nil but Service.FetchChannelDetailByIDOrHandle was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ChannelID string
	}{
		Ctx:       ctx,
		ChannelID: channelID,
	}
	mock.lockFetchChannelDetailByIDOrHandle.Lock()
	mock.calls.FetchChannelDetailByIDOrHandle = append(mock.calls.FetchChannelDetailByIDOrHandle, callInfo)
	mock.lockFetchChannelDetailByIDOrHandle.Unlock()
	return mock.FetchChannelDetailByIDOrHandleFunc(ctx, channelID)
}

// FetchChannelDetailByIDOrHandleCalls gets all the calls that were made to FetchChannelDetailByIDOrHandle.
// Check the length with:
//
//	len(mockedService.FetchChannelDetailByIDOrHandleCalls())
func (mock *ServiceMock) FetchChannelDetailByIDOrHandleCalls() []struct {
	Ctx       context.Context
	ChannelID string
} {
	var calls []struct {
		Ctx       context.Context
		ChannelID string
	}
	mock.lockFetchChannelDetailByIDOrHandle.RLock()
	calls = mock.calls.FetchChannelDetailByIDOrHandle
	mock.lockFetchChannelDetailByIDOrHandle.RUnlock()
	return calls
}

// FetchPlaylistVideoIDs calls FetchPlaylistVideoIDsFunc.
func (mock *ServiceMock) FetchPlaylistVideoIDs(ctx context.Context, playlistID string, pageToken string) ([]youtube_d.VideoID, string, error) {
	if mock.FetchPlaylistVideoIDsFunc == nil {
		panic("ServiceMock.FetchPlaylistVideoIDsFunc: method is nil but Service.FetchPlaylistVideoIDs was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		PlaylistID string
		PageToken  string
	}{
		Ctx:        ctx,
		PlaylistID: playlistID,
		PageToken:  pageToken,
	}
	mock.lockFetchPlaylistVideoIDs.Lock()
	mock.calls.FetchPlaylistVideoIDs = append(mock.calls.FetchPlaylistVideoIDs, callInfo)
	mock.lockFetchPlaylistVideoIDs.Unlock()
	return mock.FetchPlaylistVideoIDsFunc(ctx, playlistID, pageToken)
}

// FetchPlaylistVideoIDsCalls gets all the calls that were made to FetchPlaylistVideoIDs.
// Check the length with:
//
//	len(mockedService.FetchPlaylistVideoIDsCalls())
func (mock *ServiceMock) FetchPlaylistVideoIDsCalls() []struct {
	Ctx        context.Context
	PlaylistID string
	PageToken  string
} {
	var calls []struct {
		Ctx        context.Context
		PlaylistID string
		PageToken  string
	}
	mock.lockFetchPlaylistVideoIDs.RLock()
	calls = mock.calls.FetchPlaylistVideoIDs
	mock.lockFetchPlaylistVideoIDs.RUnlock()
	return calls
}

// FetchRSSFeed calls FetchRSSFeedFunc.
func (mock *ServiceMock) FetchRSSFeed(ctx context.Context, channelID youtube_d.ChannelID) ([]youtube_d.VideoID, error) {
	if mock.FetchRSSFeedFunc == nil {
		panic("ServiceMock.FetchRSSFeedFunc: method is nil but Service.FetchRSSFeed was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ChannelID youtube_d.ChannelID
	}{
		Ctx:       ctx,
		ChannelID: channelID,
	}
	mock.lockFetchRSSFeed.Lock()
	mock.calls.FetchRSSFeed = append(mock.calls.FetchRSSFeed, callInfo)
	mock.lockFetchRSSFeed.Unlock()
	return mock.FetchRSSFeedFunc(ctx, channelID)
}

// FetchRSSFeedCalls gets all the calls that were made to FetchRSSFeed.
// Check the length with:
//
//	len(mockedService.FetchRSSFeedCalls())
func (mock *ServiceMock) FetchRSSFeedCalls() []struct {
	Ctx       context.Context
	ChannelID youtube_d.ChannelID
} {
	var calls []struct {
		Ctx       context.Context
		ChannelID youtube_d.ChannelID
	}
	mock.lockFetchRSSFeed.RLock()
	calls = mock.calls.FetchRSSFeed
	mock.lockFetchRSSFeed.RUnlock()
	return calls
}

// FetchVideoDetail calls FetchVideoDetailFunc.
func (mock *ServiceMock) FetchVideoDetail(ctx context.Context, videoIDs []youtube_d.VideoID) (map[youtube_d.VideoID]youtube_d.Video, error) {
	if mock.FetchVideoDetailFunc == nil {
		panic("ServiceMock.FetchVideoDetailFunc: method is nil but Service.FetchVideoDetail was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		VideoIDs []youtube_d.VideoID
	}{
		Ctx:      ctx,
		VideoIDs: videoIDs,
	}
	mock.lockFetchVideoDetail.Lock()
	mock.calls.FetchVideoDetail = append(mock.calls.FetchVideoDetail, callInfo)
	mock.lockFetchVideoDetail.Unlock()
	return mock.FetchVideoDetailFunc(ctx, videoIDs)
}

// FetchVideoDetailCalls gets all the calls that were made to FetchVideoDetail.
// Check the length with:
//
//	len(mockedService.FetchVideoDetailCalls())
func (mock *ServiceMock) FetchVideoDetailCalls() []struct {
	Ctx      context.Context
	VideoIDs []youtube_d.VideoID
} {
	var calls []struct {
		Ctx      context.Context
		VideoIDs []youtube_d.VideoID
	}
	mock.lockFetchVideoDetail.RLock()
	calls = mock.calls.FetchVideoDetail
	mock.lockFetchVideoDetail.RUnlock()
	return calls
}

// SearchVideoIDs calls SearchVideoIDsFunc.
func (mock *ServiceMock) SearchVideoIDs(ctx context.Context, query string, pageToken string, language *string) ([]youtube_d.VideoID, string, error) {
	if mock.SearchVideoIDsFunc == nil {
		panic("ServiceMock.SearchVideoIDsFunc: method is nil but Service.SearchVideoIDs was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Query     string
		PageToken string
		Language  *string
	}{
		Ctx:       ctx,
		Query:     query,
		PageToken: pageToken,
		Language:  language,
	}
	mock.lockSearchVideoIDs.Lock()
	mock.calls.SearchVideoIDs = append(mock.calls.SearchVideoIDs, callInfo)
	mock.lockSearchVideoIDs.Unlock()
	return mock.SearchVideoIDsFunc(ctx, query, pageToken, language)
}

// SearchVideoIDsCalls gets all the calls that were made to SearchVideoIDs.
// Check the length with:
//
//	len(mockedService.SearchVideoIDsCalls())
func (mock *ServiceMock) SearchVideoIDsCalls() []struct {
	Ctx       context.Context
	Query     string
	PageToken string
	Language  *string
} {
	var calls []struct {
		Ctx       context.Context
		Query     string
		PageToken string
		Language  *string
	}
	mock.lockSearchVideoIDs.RLock()
	calls = mock.calls.SearchVideoIDs
	mock.lockSearchVideoIDs.RUnlock()
	return calls
}
