// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package channel_test

import (
	"context"
	"github.com/brqnko/anti-yt/backend/internal/core/youtube_d"
	"sync"
)

// Ensure, that ClientMock does implement youtube_d.Client.
// If this is not the case, regenerate this file with moq.
var _ youtube_d.Client = &ClientMock{}

// ClientMock is a mock implementation of youtube_d.Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked youtube_d.Client
//		mockedClient := &ClientMock{
//			FetchChannelDetailFunc: func(ctx context.Context, channelIDs []youtube_d.ChannelID) (map[youtube_d.ChannelID]youtube_d.Channel, error) {
//				panic("mock out the FetchChannelDetail method")
//			},
//			FetchChannelDetailByIDOrHandleFunc: func(ctx context.Context, channelID string) (youtube_d.Channel, error) {
//				panic("mock out the FetchChannelDetailByIDOrHandle method")
//			},
//			FetchChannelPlaylistsFunc: func(ctx context.Context, channelID youtube_d.ChannelID, pageToken string) ([]youtube_d.Playlist, string, error) {
//				panic("mock out the FetchChannelPlaylists method")
//			},
//			FetchPlaylistVideoIDsFunc: func(ctx context.Context, playlistID string, pageToken string) ([]youtube_d.VideoID, string, error) {
//				panic("mock out the FetchPlaylistVideoIDs method")
//			},
//			FetchVideoDetailFunc: func(ctx context.Context, videoIDs []youtube_d.VideoID) (map[youtube_d.VideoID]youtube_d.Video, error) {
//				panic("mock out the FetchVideoDetail method")
//			},
//			OAuthAuthCodeURLFunc: func(state string) string {
//				panic("mock out the OAuthAuthCodeURL method")
//			},
//			OAuthExchangeFunc: func(ctx context.Context, code string) (*youtube_d.OAuthClient, error) {
//				panic("mock out the OAuthExchange method")
//			},
//			SearchVideoIDsFunc: func(ctx context.Context, query string, pageToken string, opts youtube_d.SearchOptions) ([]youtube_d.VideoID, string, error) {
//				panic("mock out the SearchVideoIDs method")
//			},
//		}
//
//		// use mockedClient in code that requires youtube_d.Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// FetchChannelDetailFunc mocks the FetchChannelDetail method.
	FetchChannelDetailFunc func(ctx context.Context, channelIDs []youtube_d.ChannelID) (map[youtube_d.ChannelID]youtube_d.Channel, error)

	// FetchChannelDetailByIDOrHandleFunc mocks the FetchChannelDetailByIDOrHandle method.
	FetchChannelDetailByIDOrHandleFunc func(ctx context.Context, channelID string) (youtube_d.Channel, error)

	// FetchChannelPlaylistsFunc mocks the FetchChannelPlaylists method.
	FetchChannelPlaylistsFunc func(ctx context.Context, channelID youtube_d.ChannelID, pageToken string) ([]youtube_d.Playlist, string, error)

	// FetchPlaylistVideoIDsFunc mocks the FetchPlaylistVideoIDs method.
	FetchPlaylistVideoIDsFunc func(ctx context.Context, playlistID string, pageToken string) ([]youtube_d.VideoID, string, error)

	// FetchVideoDetailFunc mocks the FetchVideoDetail method.
	FetchVideoDetailFunc func(ctx context.Context, videoIDs []youtube_d.VideoID) (map[youtube_d.VideoID]youtube_d.Video, error)

	// OAuthAuthCodeURLFunc mocks the OAuthAuthCodeURL method.
	OAuthAuthCodeURLFunc func(state string) string

	// OAuthExchangeFunc mocks the OAuthExchange method.
	OAuthExchangeFunc func(ctx context.Context, code string) (*youtube_d.OAuthClient, error)

	// SearchVideoIDsFunc mocks the SearchVideoIDs method.
	SearchVideoIDsFunc func(ctx context.Context, query string, pageToken string, opts youtube_d.SearchOptions) ([]youtube_d.VideoID, string, error)

	// calls tracks calls to the methods.
	calls struct {
		// FetchChannelDetail holds details about calls to the FetchChannelDetail method.
		FetchChannelDetail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChannelIDs is the channelIDs argument value.
			ChannelIDs []youtube_d.ChannelID
		}
		// FetchChannelDetailByIDOrHandle holds details about calls to the FetchChannelDetailByIDOrHandle method.
		FetchChannelDetailByIDOrHandle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChannelID is the channelID argument value.
			ChannelID string
		}
		// FetchChannelPlaylists holds details about calls to the FetchChannelPlaylists method.
		FetchChannelPlaylists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChannelID is the channelID argument value.
			ChannelID youtube_d.ChannelID
			// PageToken is the pageToken argument value.
			PageToken string
		}
		// FetchPlaylistVideoIDs holds details about calls to the FetchPlaylistVideoIDs method.
		FetchPlaylistVideoIDs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PlaylistID is the playlistID argument value.
			PlaylistID string
			// PageToken is the pageToken argument value.
			PageToken string
		}
		// FetchVideoDetail holds details about calls to the FetchVideoDetail method.
		FetchVideoDetail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VideoIDs is the videoIDs argument value.
			VideoIDs []youtube_d.VideoID
		}
		// OAuthAuthCodeURL holds details about calls to the OAuthAuthCodeURL method.
		OAuthAuthCodeURL []struct {
			// State is the state argument value.
			State string
		}
		// OAuthExchange holds details about calls to the OAuthExchange method.
		OAuthExchange []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Code is the code argument value.
			Code string
		}
		// SearchVideoIDs holds details about calls to the SearchVideoIDs method.
		SearchVideoIDs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// PageToken is the pageToken argument value.
			PageToken string
			// Opts is the opts argument value.
			Opts youtube_d.SearchOptions
		}
	}
	lockFetchChannelDetail             sync.RWMutex
	lockFetchChannelDetailByIDOrHandle sync.RWMutex
	lockFetchChannelPlaylists          sync.RWMutex
	lockFetchPlaylistVideoIDs          sync.RWMutex
	lockFetchVideoDetail               sync.RWMutex
	lockOAuthAuthCodeURL               sync.RWMutex
	lockOAuthExchange                  sync.RWMutex
	lockSearchVideoIDs                 sync.RWMutex
}

// FetchChannelDetail calls FetchChannelDetailFunc.
func (mock *ClientMock) FetchChannelDetail(ctx context.Context, channelIDs []youtube_d.ChannelID) (map[youtube_d.ChannelID]youtube_d.Channel, error) {
	if mock.FetchChannelDetailFunc == nil {
		panic("ClientMock.FetchChannelDetailFunc: method is nil but Client.FetchChannelDetail was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ChannelIDs []youtube_d.ChannelID
	}{
		Ctx:        ctx,
		ChannelIDs: channelIDs,
	}
	mock.lockFetchChannelDetail.Lock()
	mock.calls.FetchChannelDetail = append(mock.calls.FetchChannelDetail, callInfo)
	mock.lockFetchChannelDetail.Unlock()
	return mock.FetchChannelDetailFunc(ctx, channelIDs)
}

// FetchChannelDetailCalls gets all the calls that were made to FetchChannelDetail.
// Check the length with:
//
//	len(mockedClient.FetchChannelDetailCalls())
func (mock *ClientMock) FetchChannelDetailCalls() []struct {
	Ctx        context.Context
	ChannelIDs []youtube_d.ChannelID
} {
	var calls []struct {
		Ctx        context.Context
		ChannelIDs []youtube_d.ChannelID
	}
	mock.lockFetchChannelDetail.RLock()
	calls = mock.calls.FetchChannelDetail
	mock.lockFetchChannelDetail.RUnlock()
	return calls
}

// FetchChannelDetailByIDOrHandle calls FetchChannelDetailByIDOrHandleFunc.
func (mock *ClientMock) FetchChannelDetailByIDOrHandle(ctx context.Context, channelID string) (youtube_d.Channel, error) {
	if mock.FetchChannelDetailByIDOrHandleFunc == nil {
		panic("ClientMock.FetchChannelDetailByIDOrHandleFunc: method is nil but Client.FetchChannelDetailByIDOrHandle was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ChannelID string
	}{
		Ctx:       ctx,
		ChannelID: channelID,
	}
	mock.lockFetchChannelDetailByIDOrHandle.Lock()
	mock.calls.FetchChannelDetailByIDOrHandle = append(mock.calls.FetchChannelDetailByIDOrHandle, callInfo)
	mock.lockFetchChannelDetailByIDOrHandle.Unlock()
	return mock.FetchChannelDetailByIDOrHandleFunc(ctx, channelID)
}

// FetchChannelDetailByIDOrHandleCalls gets all the calls that were made to FetchChannelDetailByIDOrHandle.
// Check the length with:
//
//	len(mockedClient.FetchChannelDetailByIDOrHandleCalls())
func (mock *ClientMock) FetchChannelDetailByIDOrHandleCalls() []struct {
	Ctx       context.Context
	ChannelID string
} {
	var calls []struct {
		Ctx       context.Context
		ChannelID string
	}
	mock.lockFetchChannelDetailByIDOrHandle.RLock()
	calls = mock.calls.FetchChannelDetailByIDOrHandle
	mock.lockFetchChannelDetailByIDOrHandle.RUnlock()
	return calls
}

// FetchChannelPlaylists calls FetchChannelPlaylistsFunc.
func (mock *ClientMock) FetchChannelPlaylists(ctx context.Context, channelID youtube_d.ChannelID, pageToken string) ([]youtube_d.Playlist, string, error) {
	if mock.FetchChannelPlaylistsFunc == nil {
		panic("ClientMock.FetchChannelPlaylistsFunc: method is nil but Client.FetchChannelPlaylists was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ChannelID youtube_d.ChannelID
		PageToken string
	}{
		Ctx:       ctx,
		ChannelID: channelID,
		PageToken: pageToken,
	}
	mock.lockFetchChannelPlaylists.Lock()
	mock.calls.FetchChannelPlaylists = append(mock.calls.FetchChannelPlaylists, callInfo)
	mock.lockFetchChannelPlaylists.Unlock()
	return mock.FetchChannelPlaylistsFunc(ctx, channelID, pageToken)
}

// FetchChannelPlaylistsCalls gets all the calls that were made to FetchChannelPlaylists.
// Check the length with:
//
//	len(mockedClient.FetchChannelPlaylistsCalls())
func (mock *ClientMock) FetchChannelPlaylistsCalls() []struct {
	Ctx       context.Context
	ChannelID youtube_d.ChannelID
	PageToken string
} {
	var calls []struct {
		Ctx       context.Context
		ChannelID youtube_d.ChannelID
		PageToken string
	}
	mock.lockFetchChannelPlaylists.RLock()
	calls = mock.calls.FetchChannelPlaylists
	mock.lockFetchChannelPlaylists.RUnlock()
	return calls
}

// FetchPlaylistVideoIDs calls FetchPlaylistVideoIDsFunc.
func (mock *ClientMock) FetchPlaylistVideoIDs(ctx context.Context, playlistID string, pageToken string) ([]youtube_d.VideoID, string, error) {
	if mock.FetchPlaylistVideoIDsFunc == nil {
		panic("ClientMock.FetchPlaylistVideoIDsFunc: method is nil but Client.FetchPlaylistVideoIDs was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		PlaylistID string
		PageToken  string
	}{
		Ctx:        ctx,
		PlaylistID: playlistID,
		PageToken:  pageToken,
	}
	mock.lockFetchPlaylistVideoIDs.Lock()
	mock.calls.FetchPlaylistVideoIDs = append(mock.calls.FetchPlaylistVideoIDs, callInfo)
	mock.lockFetchPlaylistVideoIDs.Unlock()
	return mock.FetchPlaylistVideoIDsFunc(ctx, playlistID, pageToken)
}

// FetchPlaylistVideoIDsCalls gets all the calls that were made to FetchPlaylistVideoIDs.
// Check the length with:
//
//	len(mockedClient.FetchPlaylistVideoIDsCalls())
func (mock *ClientMock) FetchPlaylistVideoIDsCalls() []struct {
	Ctx        context.Context
	PlaylistID string
	PageToken  string
} {
	var calls []struct {
		Ctx        context.Context
		PlaylistID string
		PageToken  string
	}
	mock.lockFetchPlaylistVideoIDs.RLock()
	calls = mock.calls.FetchPlaylistVideoIDs
	mock.lockFetchPlaylistVideoIDs.RUnlock()
	return calls
}

// FetchVideoDetail calls FetchVideoDetailFunc.
func (mock *ClientMock) FetchVideoDetail(ctx context.Context, videoIDs []youtube_d.VideoID) (map[youtube_d.VideoID]youtube_d.Video, error) {
	if mock.FetchVideoDetailFunc == nil {
		panic("ClientMock.FetchVideoDetailFunc: method is nil but Client.FetchVideoDetail was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		VideoIDs []youtube_d.VideoID
	}{
		Ctx:      ctx,
		VideoIDs: videoIDs,
	}
	mock.lockFetchVideoDetail.Lock()
	mock.calls.FetchVideoDetail = append(mock.calls.FetchVideoDetail, callInfo)
	mock.lockFetchVideoDetail.Unlock()
	return mock.FetchVideoDetailFunc(ctx, videoIDs)
}

// FetchVideoDetailCalls gets all the calls that were made to FetchVideoDetail.
// Check the length with:
//
//	len(mockedClient.FetchVideoDetailCalls())
func (mock *ClientMock) FetchVideoDetailCalls() []struct {
	Ctx      context.Context
	VideoIDs []youtube_d.VideoID
} {
	var calls []struct {
		Ctx      context.Context
		VideoIDs []youtube_d.VideoID
	}
	mock.lockFetchVideoDetail.RLock()
	calls = mock.calls.FetchVideoDetail
	mock.lockFetchVideoDetail.RUnlock()
	return calls
}

// OAuthAuthCodeURL calls OAuthAuthCodeURLFunc.
func (mock *ClientMock) OAuthAuthCodeURL(state string) string {
	if mock.OAuthAuthCodeURLFunc == nil {
		panic("ClientMock.OAuthAuthCodeURLFunc: method is nil but Client.OAuthAuthCodeURL was just called")
	}
	callInfo := struct {
		State string
	}{
		State: state,
	}
	mock.lockOAuthAuthCodeURL.Lock()
	mock.calls.OAuthAuthCodeURL = append(mock.calls.OAuthAuthCodeURL, callInfo)
	mock.lockOAuthAuthCodeURL.Unlock()
	return mock.OAuthAuthCodeURLFunc(state)
}

// OAuthAuthCodeURLCalls gets all the calls that were made to OAuthAuthCodeURL.
// Check the length with:
//
//	len(mockedClient.OAuthAuthCodeURLCalls())
func (mock *ClientMock) OAuthAuthCodeURLCalls() []struct {
	State string
} {
	var calls []struct {
		State string
	}
	mock.lockOAuthAuthCodeURL.RLock()
	calls = mock.calls.OAuthAuthCodeURL
	mock.lockOAuthAuthCodeURL.RUnlock()
	return calls
}

// OAuthExchange calls OAuthExchangeFunc.
func (mock *ClientMock) OAuthExchange(ctx context.Context, code string) (*youtube_d.OAuthClient, error) {
	if mock.OAuthExchangeFunc == nil {
		panic("ClientMock.OAuthExchangeFunc: method is nil but Client.OAuthExchange was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Code string
	}{
		Ctx:  ctx,
		Code: code,
	}
	mock.lockOAuthExchange.Lock()
	mock.calls.OAuthExchange = append(mock.calls.OAuthExchange, callInfo)
	mock.lockOAuthExchange.Unlock()
	return mock.OAuthExchangeFunc(ctx, code)
}

// OAuthExchangeCalls gets all the calls that were made to OAuthExchange.
// Check the length with:
//
//	len(mockedClient.OAuthExchangeCalls())
func (mock *ClientMock) OAuthExchangeCalls() []struct {
	Ctx  context.Context
	Code string
} {
	var calls []struct {
		Ctx  context.Context
		Code string
	}
	mock.lockOAuthExchange.RLock()
	calls = mock.calls.OAuthExchange
	mock.lockOAuthExchange.RUnlock()
	return calls
}

// SearchVideoIDs calls SearchVideoIDsFunc.
func (mock *ClientMock) SearchVideoIDs(ctx context.Context, query string, pageToken string, opts youtube_d.SearchOptions) ([]youtube_d.VideoID, string, error) {
	if mock.SearchVideoIDsFunc == nil {
		panic("ClientMock.SearchVideoIDsFunc: method is nil but Client.SearchVideoIDs was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Query     string
		PageToken string
		Opts      youtube_d.SearchOptions
	}{
		Ctx:       ctx,
		Query:     query,
		PageToken: pageToken,
		Opts:      opts,
	}
	mock.lockSearchVideoIDs.Lock()
	mock.calls.SearchVideoIDs = append(mock.calls.SearchVideoIDs, callInfo)
	mock.lockSearchVideoIDs.Unlock()
	return mock.SearchVideoIDsFunc(ctx, query, pageToken, opts)
}

// SearchVideoIDsCalls gets all the calls that were made to SearchVideoIDs.
// Check the length with:
//
//	len(mockedClient.SearchVideoIDsCalls())
func (mock *ClientMock) SearchVideoIDsCalls() []struct {
	Ctx       context.Context
	Query     string
	PageToken string
	Opts      youtube_d.SearchOptions
} {
	var calls []struct {
		Ctx       context.Context
		Query     string
		PageToken string
		Opts      youtube_d.SearchOptions
	}
	mock.lockSearchVideoIDs.RLock()
	calls = mock.calls.SearchVideoIDs
	mock.lockSearchVideoIDs.RUnlock()
	return calls
}
