// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// ProblemDetailError defines model for ProblemDetailError.
type ProblemDetailError struct {
	Detail string `json:"detail"`
	Title  string `json:"title"`
}

// CookieCsrfToken defines model for CookieCsrfToken.
type CookieCsrfToken = string

// HeaderCsrfToken CSRF Token
type HeaderCsrfToken = string

// Forbidden defines model for Forbidden.
type Forbidden = ProblemDetailError

// InternalServerError defines model for InternalServerError.
type InternalServerError = ProblemDetailError

// NotFound defines model for NotFound.
type NotFound = ProblemDetailError

// Unauthorized defines model for Unauthorized.
type Unauthorized = ProblemDetailError

// GetAuthGoogleCallbackParams defines parameters for GetAuthGoogleCallback.
type GetAuthGoogleCallbackParams struct {
	// Code Googleから発行された認可コード
	Code string `form:"code" json:"code"`

	// State CSRF対策用
	State string `form:"state" json:"state"`

	// Error エラー
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// PostAuthRefreshParams defines parameters for PostAuthRefresh.
type PostAuthRefreshParams struct {
	XCsrfToken   HeaderCsrfToken `json:"X-csrf-token"`
	RefreshToken string          `form:"refresh_token" json:"refresh_token"`

	// CsrfToken CSRF Token
	CsrfToken CookieCsrfToken `form:"csrf_token" json:"csrf_token"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Google authentication
	// (POST /api/v1/auth/google)
	PostAuthGoogle(ctx echo.Context) error
	// Google Authorization Code Callback
	// (GET /api/v1/auth/google/callback)
	GetAuthGoogleCallback(ctx echo.Context, params GetAuthGoogleCallbackParams) error
	// Refresh access token
	// (POST /api/v1/auth/refresh)
	PostAuthRefresh(ctx echo.Context, params PostAuthRefreshParams) error
	// Health check
	// (GET /health)
	GetHealth(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostAuthGoogle converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthGoogle(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthGoogle(ctx)
	return err
}

// GetAuthGoogleCallback converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuthGoogleCallback(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthGoogleCallbackParams
	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameter("form", true, true, "code", ctx.QueryParams(), &params.Code)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter code: %s", err))
	}

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, true, "state", ctx.QueryParams(), &params.State)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter state: %s", err))
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameter("form", true, false, "error", ctx.QueryParams(), &params.Error)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter error: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuthGoogleCallback(ctx, params)
	return err
}

// PostAuthRefresh converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthRefresh(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAuthRefreshParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-csrf-token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-csrf-token")]; found {
		var XCsrfToken HeaderCsrfToken
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-csrf-token, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-csrf-token", valueList[0], &XCsrfToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-csrf-token: %s", err))
		}

		params.XCsrfToken = XCsrfToken
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-csrf-token is required, but not found"))
	}

	if cookie, err := ctx.Cookie("refresh_token"); err == nil {

		var value string
		err = runtime.BindStyledParameterWithOptions("simple", "refresh_token", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter refresh_token: %s", err))
		}
		params.RefreshToken = value

	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Query argument refresh_token is required, but not found"))
	}

	if cookie, err := ctx.Cookie("csrf_token"); err == nil {

		var value CookieCsrfToken
		err = runtime.BindStyledParameterWithOptions("simple", "csrf_token", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter csrf_token: %s", err))
		}
		params.CsrfToken = value

	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Query argument csrf_token is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthRefresh(ctx, params)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/api/v1/auth/google", wrapper.PostAuthGoogle)
	router.GET(baseURL+"/api/v1/auth/google/callback", wrapper.GetAuthGoogleCallback)
	router.POST(baseURL+"/api/v1/auth/refresh", wrapper.PostAuthRefresh)
	router.GET(baseURL+"/health", wrapper.GetHealth)

}

type ForbiddenJSONResponse ProblemDetailError

type InternalServerErrorJSONResponse ProblemDetailError

type NotFoundJSONResponse ProblemDetailError

type UnauthorizedJSONResponse ProblemDetailError

type PostAuthGoogleRequestObject struct {
}

type PostAuthGoogleResponseObject interface {
	VisitPostAuthGoogleResponse(w http.ResponseWriter) error
}

type PostAuthGoogle302ResponseHeaders struct {
	Location  string
	SetCookie string
}

type PostAuthGoogle302Response struct {
	Headers PostAuthGoogle302ResponseHeaders
}

func (response PostAuthGoogle302Response) VisitPostAuthGoogleResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(302)
	return nil
}

type PostAuthGoogle401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostAuthGoogle401JSONResponse) VisitPostAuthGoogleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthGoogle403JSONResponse struct{ ForbiddenJSONResponse }

func (response PostAuthGoogle403JSONResponse) VisitPostAuthGoogleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthGoogle404JSONResponse struct{ NotFoundJSONResponse }

func (response PostAuthGoogle404JSONResponse) VisitPostAuthGoogleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthGoogle500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostAuthGoogle500JSONResponse) VisitPostAuthGoogleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAuthGoogleCallbackRequestObject struct {
	Params GetAuthGoogleCallbackParams
}

type GetAuthGoogleCallbackResponseObject interface {
	VisitGetAuthGoogleCallbackResponse(w http.ResponseWriter) error
}

type GetAuthGoogleCallback302ResponseHeaders struct {
	Location  string
	SetCookie string
}

type GetAuthGoogleCallback302Response struct {
	Headers GetAuthGoogleCallback302ResponseHeaders
}

func (response GetAuthGoogleCallback302Response) VisitGetAuthGoogleCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(302)
	return nil
}

type GetAuthGoogleCallback401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAuthGoogleCallback401JSONResponse) VisitGetAuthGoogleCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAuthGoogleCallback404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAuthGoogleCallback404JSONResponse) VisitGetAuthGoogleCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAuthGoogleCallback500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetAuthGoogleCallback500JSONResponse) VisitGetAuthGoogleCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthRefreshRequestObject struct {
	Params PostAuthRefreshParams
}

type PostAuthRefreshResponseObject interface {
	VisitPostAuthRefreshResponse(w http.ResponseWriter) error
}

type PostAuthRefresh200ResponseHeaders struct {
	SetCookie string
}

type PostAuthRefresh200JSONResponse struct {
	Body struct {
		Status string `json:"status"`
	}
	Headers PostAuthRefresh200ResponseHeaders
}

func (response PostAuthRefresh200JSONResponse) VisitPostAuthRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostAuthRefresh401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostAuthRefresh401JSONResponse) VisitPostAuthRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthRefresh403JSONResponse struct{ ForbiddenJSONResponse }

func (response PostAuthRefresh403JSONResponse) VisitPostAuthRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthRefresh404JSONResponse struct{ NotFoundJSONResponse }

func (response PostAuthRefresh404JSONResponse) VisitPostAuthRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthRefresh500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostAuthRefresh500JSONResponse) VisitPostAuthRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse struct {
	Status string `json:"status"`
}

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealth401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetHealth401JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetHealth403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetHealth403JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetHealth404JSONResponse struct{ NotFoundJSONResponse }

func (response GetHealth404JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetHealth500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetHealth500JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Google authentication
	// (POST /api/v1/auth/google)
	PostAuthGoogle(ctx context.Context, request PostAuthGoogleRequestObject) (PostAuthGoogleResponseObject, error)
	// Google Authorization Code Callback
	// (GET /api/v1/auth/google/callback)
	GetAuthGoogleCallback(ctx context.Context, request GetAuthGoogleCallbackRequestObject) (GetAuthGoogleCallbackResponseObject, error)
	// Refresh access token
	// (POST /api/v1/auth/refresh)
	PostAuthRefresh(ctx context.Context, request PostAuthRefreshRequestObject) (PostAuthRefreshResponseObject, error)
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PostAuthGoogle operation middleware
func (sh *strictHandler) PostAuthGoogle(ctx echo.Context) error {
	var request PostAuthGoogleRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthGoogle(ctx.Request().Context(), request.(PostAuthGoogleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthGoogle")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostAuthGoogleResponseObject); ok {
		return validResponse.VisitPostAuthGoogleResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAuthGoogleCallback operation middleware
func (sh *strictHandler) GetAuthGoogleCallback(ctx echo.Context, params GetAuthGoogleCallbackParams) error {
	var request GetAuthGoogleCallbackRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthGoogleCallback(ctx.Request().Context(), request.(GetAuthGoogleCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthGoogleCallback")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAuthGoogleCallbackResponseObject); ok {
		return validResponse.VisitGetAuthGoogleCallbackResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostAuthRefresh operation middleware
func (sh *strictHandler) PostAuthRefresh(ctx echo.Context, params PostAuthRefreshParams) error {
	var request PostAuthRefreshRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthRefresh(ctx.Request().Context(), request.(PostAuthRefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthRefresh")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostAuthRefreshResponseObject); ok {
		return validResponse.VisitPostAuthRefreshResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx echo.Context) error {
	var request GetHealthRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx.Request().Context(), request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		return validResponse.VisitGetHealthResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXbW/bVBT+K9aFj27tNUWa8q3K2NYNbdM6BFIVVa590nhNfL3rm6IwRZptBJtaVKi6",
	"jk5MExOwMGg7USFeWvFnDlm6f4Huvc6LE6fpeKlA8KVqfM89z/E553nO8W1i06pPPfB4QPK3iW8xqwoc",
	"mPxVoHTZhULASjfoMnjikQOBzVyfu9QjeVKYu35eU2c6ccUTW14hOvGsKojfASst8MSCwa2ay8Ahec5q",
	"oJPALkPVEm553RfWAWeut0QaDZ1cBMsBlsKWAGX5vAfw7oSAmBgPcUzkg+gN4SfwqReAzMN5yhZdx1FR",
	"2NTj4HHxr+X7Fde2hEvjZkDlcQ/wdQYlkievGb0UG+o0MK4xuliB6jngllt5kzHKFGw6yGkzp/WwGzqZ",
	"9Tgwz6rMAVsBpu6dbkhvmKbWiUJTYWiJsU6uUH6e1jzn1NM0rV2hXFPYDZ287Vk1XqbMfR9OP5YzWgpe",
	"mCQuBEKGF0E7Rn1g3FXt5sjDDFrohLu8AtmE6XX+fGKmdzwVuy1OF2+CzVVQYNeYy+tzIjjo4/ul9/hM",
	"jZeHOXPpnRvajG1DECjmaK6nFTp8z2S/Ja27/E+CsHz3MtRV9lyvRIeRLI+7E3WuWb5Lui898HQFWKCs",
	"z0yak6bIDvXBE4d5kps0J3NEJ77Fy/LVDMt3jZUzhqiMsUTpkkqjTwM+DH9BnmtXZ88VMHyK8Q5GzzH6",
	"EuN9ytrbBy/XvicSjMk+mnVInlyjgcyaukoGBCRnTg2j5MwpjYHjMlERPRE2af4WVR2abs6sGDHcPXr2",
	"8VHzsL158PLREwx/wvgZxndktN9htIfx3QyB08kc8ImkdseABNzigGHTpg4srABzSy4wjDZerH3U2n2Y",
	"pZwNXVBgFJe6STHSHBGXcuMvpbRw2pwef6OrSA1dSNf4C1kK288Wkp8v6iSoVasWq/daRbwMeDxRFpEY",
	"aykQTBQHpCg8ZHSgYVuVyqJlL4u4loAfX+XW+h5G+xgfYnwPo43W+gMMP22tb2G0iuFjjMKhprwAfT1Z",
	"6GDpqSk/PwpyFaN77e1fjr5Yw/A+RmsYPh4IosP6WzVg9b6RTx14tWGfNZxbe7+2d7bam80RKLI1/xwM",
	"Rk2Mv8H4cAQEyOof57L49/Nc6U2H3quC23GM0Y8Yf4Xx591C/FGGY/REqER0gNHPGN8V/oRo7GPYlEpy",
	"X8hIDzBl0NuhMNo4au60dh/ineivVYV/EMdnktBkybQCdUDrcmqI4AxKDILy6BkzJrvRRnuzieEHGH79",
	"Yus5hg/E/6NqFW10iLotxEDWIHs8XU/CGtKAzPGdvMTCqy7XCcrI/VrPrlAvJGNw+z/BlcGPlSFyTqne",
	"OPEymF7KhN7UgvGrV2KXsXIN7YpTpqldvZyWhJOxtn+vwrCZqtP/47mPup1OVAnTuovo8HQug1VRS2/m",
	"IJ65NovRD1JuPxF/w12MP8P4W0nFEKOnksZ7QggFDz/MIuEF4BcVyr+kM/9r3aKqo9llkGtSp0uqbmCL",
	"LknfHPpcmi8KyQkkVtZiJaZ9pUwDrikbopMaq5A8KXPu5w2j0jnPnzXPmlK/kggGPamVv+8zS+Bn7Dfh",
	"Iwx3fzvY6lnKV2kUG78HAAD//+XvQAv4EQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
