// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package testutil

import (
	"github.com/brqnko/anti-yt/backend/internal/core/jwt_d"
	"github.com/google/uuid"
	"sync"
	"time"
)

// Ensure, that ServiceMock does implement jwt_d.Service.
// If this is not the case, regenerate this file with moq.
var _ jwt_d.Service = &ServiceMock{}

// ServiceMock is a mock implementation of jwt_d.Service.
//
//	func TestSomethingThatUsesService(t *testing.T) {
//
//		// make and configure a mocked jwt_d.Service
//		mockedService := &ServiceMock{
//			SignRegisterTokenFunc: func(authorizationID uuid.UUID, jti uuid.UUID, serverURL string) (string, time.Time, error) {
//				panic("mock out the SignRegisterToken method")
//			},
//			SignUserAccessTokenFunc: func(userID uuid.UUID, jti uuid.UUID, serverURL string) (string, time.Time, error) {
//				panic("mock out the SignUserAccessToken method")
//			},
//			TokenDurationFunc: func() time.Duration {
//				panic("mock out the TokenDuration method")
//			},
//			VerifyRegisterTokenFunc: func(token string) (uuid.UUID, uuid.UUID, error) {
//				panic("mock out the VerifyRegisterToken method")
//			},
//			VerifyUserAccessTokenFunc: func(token string) (uuid.UUID, uuid.UUID, time.Time, error) {
//				panic("mock out the VerifyUserAccessToken method")
//			},
//		}
//
//		// use mockedService in code that requires jwt_d.Service
//		// and then make assertions.
//
//	}
type ServiceMock struct {
	// SignRegisterTokenFunc mocks the SignRegisterToken method.
	SignRegisterTokenFunc func(authorizationID uuid.UUID, jti uuid.UUID, serverURL string) (string, time.Time, error)

	// SignUserAccessTokenFunc mocks the SignUserAccessToken method.
	SignUserAccessTokenFunc func(userID uuid.UUID, jti uuid.UUID, serverURL string) (string, time.Time, error)

	// TokenDurationFunc mocks the TokenDuration method.
	TokenDurationFunc func() time.Duration

	// VerifyRegisterTokenFunc mocks the VerifyRegisterToken method.
	VerifyRegisterTokenFunc func(token string) (uuid.UUID, uuid.UUID, error)

	// SignYouTubeImportStateTokenFunc mocks the SignYouTubeImportStateToken method.
	SignYouTubeImportStateTokenFunc func(userID uuid.UUID, importSubscriptions, importLikes bool, serverURL string) (string, error)

	// SignOIDCStateTokenFunc mocks the SignOIDCStateToken method.
	SignOIDCStateTokenFunc func(platform, serverURL string) (string, error)

	// VerifyYouTubeImportStateTokenFunc mocks the VerifyYouTubeImportStateToken method.
	VerifyYouTubeImportStateTokenFunc func(token string) (uuid.UUID, bool, bool, error)

	// VerifyOIDCStateTokenFunc mocks the VerifyOIDCStateToken method.
	VerifyOIDCStateTokenFunc func(token string) (string, error)

	// VerifyUserAccessTokenFunc mocks the VerifyUserAccessToken method.
	VerifyUserAccessTokenFunc func(token string) (uuid.UUID, uuid.UUID, time.Time, error)

	// calls tracks calls to the methods.
	calls struct {
		// SignRegisterToken holds details about calls to the SignRegisterToken method.
		SignRegisterToken []struct {
			// AuthorizationID is the authorizationID argument value.
			AuthorizationID uuid.UUID
			// Jti is the jti argument value.
			Jti uuid.UUID
			// ServerURL is the serverURL argument value.
			ServerURL string
		}
		// SignUserAccessToken holds details about calls to the SignUserAccessToken method.
		SignUserAccessToken []struct {
			// UserID is the userID argument value.
			UserID uuid.UUID
			// Jti is the jti argument value.
			Jti uuid.UUID
			// ServerURL is the serverURL argument value.
			ServerURL string
		}
		// TokenDuration holds details about calls to the TokenDuration method.
		TokenDuration []struct {
		}
		// VerifyRegisterToken holds details about calls to the VerifyRegisterToken method.
		VerifyRegisterToken []struct {
			// Token is the token argument value.
			Token string
		}
		// SignYouTubeImportStateToken holds details about calls to the SignYouTubeImportStateToken method.
		SignYouTubeImportStateToken []struct {
			UserID              uuid.UUID
			ImportSubscriptions bool
			ImportLikes         bool
			ServerURL           string
		}
		// SignOIDCStateToken holds details about calls to the SignOIDCStateToken method.
		SignOIDCStateToken []struct {
			Platform  string
			ServerURL string
		}
		// VerifyYouTubeImportStateToken holds details about calls to the VerifyYouTubeImportStateToken method.
		VerifyYouTubeImportStateToken []struct {
			Token string
		}
		// VerifyOIDCStateToken holds details about calls to the VerifyOIDCStateToken method.
		VerifyOIDCStateToken []struct {
			Token string
		}
		// VerifyUserAccessToken holds details about calls to the VerifyUserAccessToken method.
		VerifyUserAccessToken []struct {
			// Token is the token argument value.
			Token string
		}
	}
	lockSignRegisterToken     sync.RWMutex
	lockSignUserAccessToken   sync.RWMutex
	lockSignYouTubeImportStateToken  sync.RWMutex
	lockSignOIDCStateToken           sync.RWMutex
	lockVerifyYouTubeImportStateToken sync.RWMutex
	lockVerifyOIDCStateToken  sync.RWMutex
	lockTokenDuration         sync.RWMutex
	lockVerifyRegisterToken   sync.RWMutex
	lockVerifyUserAccessToken sync.RWMutex
}

// SignRegisterToken calls SignRegisterTokenFunc.
func (mock *ServiceMock) SignRegisterToken(authorizationID uuid.UUID, jti uuid.UUID, serverURL string) (string, time.Time, error) {
	if mock.SignRegisterTokenFunc == nil {
		panic("ServiceMock.SignRegisterTokenFunc: method is nil but Service.SignRegisterToken was just called")
	}
	callInfo := struct {
		AuthorizationID uuid.UUID
		Jti             uuid.UUID
		ServerURL       string
	}{
		AuthorizationID: authorizationID,
		Jti:             jti,
		ServerURL:       serverURL,
	}
	mock.lockSignRegisterToken.Lock()
	mock.calls.SignRegisterToken = append(mock.calls.SignRegisterToken, callInfo)
	mock.lockSignRegisterToken.Unlock()
	return mock.SignRegisterTokenFunc(authorizationID, jti, serverURL)
}

// SignRegisterTokenCalls gets all the calls that were made to SignRegisterToken.
// Check the length with:
//
//	len(mockedService.SignRegisterTokenCalls())
func (mock *ServiceMock) SignRegisterTokenCalls() []struct {
	AuthorizationID uuid.UUID
	Jti             uuid.UUID
	ServerURL       string
} {
	var calls []struct {
		AuthorizationID uuid.UUID
		Jti             uuid.UUID
		ServerURL       string
	}
	mock.lockSignRegisterToken.RLock()
	calls = mock.calls.SignRegisterToken
	mock.lockSignRegisterToken.RUnlock()
	return calls
}

// SignUserAccessToken calls SignUserAccessTokenFunc.
func (mock *ServiceMock) SignUserAccessToken(userID uuid.UUID, jti uuid.UUID, serverURL string) (string, time.Time, error) {
	if mock.SignUserAccessTokenFunc == nil {
		panic("ServiceMock.SignUserAccessTokenFunc: method is nil but Service.SignUserAccessToken was just called")
	}
	callInfo := struct {
		UserID    uuid.UUID
		Jti       uuid.UUID
		ServerURL string
	}{
		UserID:    userID,
		Jti:       jti,
		ServerURL: serverURL,
	}
	mock.lockSignUserAccessToken.Lock()
	mock.calls.SignUserAccessToken = append(mock.calls.SignUserAccessToken, callInfo)
	mock.lockSignUserAccessToken.Unlock()
	return mock.SignUserAccessTokenFunc(userID, jti, serverURL)
}

// SignUserAccessTokenCalls gets all the calls that were made to SignUserAccessToken.
// Check the length with:
//
//	len(mockedService.SignUserAccessTokenCalls())
func (mock *ServiceMock) SignUserAccessTokenCalls() []struct {
	UserID    uuid.UUID
	Jti       uuid.UUID
	ServerURL string
} {
	var calls []struct {
		UserID    uuid.UUID
		Jti       uuid.UUID
		ServerURL string
	}
	mock.lockSignUserAccessToken.RLock()
	calls = mock.calls.SignUserAccessToken
	mock.lockSignUserAccessToken.RUnlock()
	return calls
}

// TokenDuration calls TokenDurationFunc.
func (mock *ServiceMock) TokenDuration() time.Duration {
	if mock.TokenDurationFunc == nil {
		panic("ServiceMock.TokenDurationFunc: method is nil but Service.TokenDuration was just called")
	}
	callInfo := struct {
	}{}
	mock.lockTokenDuration.Lock()
	mock.calls.TokenDuration = append(mock.calls.TokenDuration, callInfo)
	mock.lockTokenDuration.Unlock()
	return mock.TokenDurationFunc()
}

// TokenDurationCalls gets all the calls that were made to TokenDuration.
// Check the length with:
//
//	len(mockedService.TokenDurationCalls())
func (mock *ServiceMock) TokenDurationCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockTokenDuration.RLock()
	calls = mock.calls.TokenDuration
	mock.lockTokenDuration.RUnlock()
	return calls
}

// VerifyRegisterToken calls VerifyRegisterTokenFunc.
func (mock *ServiceMock) VerifyRegisterToken(token string) (uuid.UUID, uuid.UUID, error) {
	if mock.VerifyRegisterTokenFunc == nil {
		panic("ServiceMock.VerifyRegisterTokenFunc: method is nil but Service.VerifyRegisterToken was just called")
	}
	callInfo := struct {
		Token string
	}{
		Token: token,
	}
	mock.lockVerifyRegisterToken.Lock()
	mock.calls.VerifyRegisterToken = append(mock.calls.VerifyRegisterToken, callInfo)
	mock.lockVerifyRegisterToken.Unlock()
	return mock.VerifyRegisterTokenFunc(token)
}

// VerifyRegisterTokenCalls gets all the calls that were made to VerifyRegisterToken.
// Check the length with:
//
//	len(mockedService.VerifyRegisterTokenCalls())
func (mock *ServiceMock) VerifyRegisterTokenCalls() []struct {
	Token string
} {
	var calls []struct {
		Token string
	}
	mock.lockVerifyRegisterToken.RLock()
	calls = mock.calls.VerifyRegisterToken
	mock.lockVerifyRegisterToken.RUnlock()
	return calls
}

// SignYouTubeImportStateToken calls SignYouTubeImportStateTokenFunc.
func (mock *ServiceMock) SignYouTubeImportStateToken(userID uuid.UUID, importSubscriptions, importLikes bool, serverURL string) (string, error) {
	if mock.SignYouTubeImportStateTokenFunc == nil {
		panic("ServiceMock.SignYouTubeImportStateTokenFunc: method is nil but Service.SignYouTubeImportStateToken was just called")
	}
	callInfo := struct {
		UserID              uuid.UUID
		ImportSubscriptions bool
		ImportLikes         bool
		ServerURL           string
	}{
		UserID:              userID,
		ImportSubscriptions: importSubscriptions,
		ImportLikes:         importLikes,
		ServerURL:           serverURL,
	}
	mock.lockSignYouTubeImportStateToken.Lock()
	mock.calls.SignYouTubeImportStateToken = append(mock.calls.SignYouTubeImportStateToken, callInfo)
	mock.lockSignYouTubeImportStateToken.Unlock()
	return mock.SignYouTubeImportStateTokenFunc(userID, importSubscriptions, importLikes, serverURL)
}

// SignYouTubeImportStateTokenCalls gets all the calls that were made to SignYouTubeImportStateToken.
func (mock *ServiceMock) SignYouTubeImportStateTokenCalls() []struct {
	UserID              uuid.UUID
	ImportSubscriptions bool
	ImportLikes         bool
	ServerURL           string
} {
	var calls []struct {
		UserID              uuid.UUID
		ImportSubscriptions bool
		ImportLikes         bool
		ServerURL           string
	}
	mock.lockSignYouTubeImportStateToken.RLock()
	calls = mock.calls.SignYouTubeImportStateToken
	mock.lockSignYouTubeImportStateToken.RUnlock()
	return calls
}

// SignOIDCStateToken calls SignOIDCStateTokenFunc.
func (mock *ServiceMock) SignOIDCStateToken(platform, serverURL string) (string, error) {
	if mock.SignOIDCStateTokenFunc == nil {
		panic("ServiceMock.SignOIDCStateTokenFunc: method is nil but Service.SignOIDCStateToken was just called")
	}
	callInfo := struct {
		Platform  string
		ServerURL string
	}{
		Platform:  platform,
		ServerURL: serverURL,
	}
	mock.lockSignOIDCStateToken.Lock()
	mock.calls.SignOIDCStateToken = append(mock.calls.SignOIDCStateToken, callInfo)
	mock.lockSignOIDCStateToken.Unlock()
	return mock.SignOIDCStateTokenFunc(platform, serverURL)
}

// SignOIDCStateTokenCalls gets all the calls that were made to SignOIDCStateToken.
func (mock *ServiceMock) SignOIDCStateTokenCalls() []struct {
	Platform  string
	ServerURL string
} {
	var calls []struct {
		Platform  string
		ServerURL string
	}
	mock.lockSignOIDCStateToken.RLock()
	calls = mock.calls.SignOIDCStateToken
	mock.lockSignOIDCStateToken.RUnlock()
	return calls
}

// VerifyYouTubeImportStateToken calls VerifyYouTubeImportStateTokenFunc.
func (mock *ServiceMock) VerifyYouTubeImportStateToken(token string) (uuid.UUID, bool, bool, error) {
	if mock.VerifyYouTubeImportStateTokenFunc == nil {
		panic("ServiceMock.VerifyYouTubeImportStateTokenFunc: method is nil but Service.VerifyYouTubeImportStateToken was just called")
	}
	callInfo := struct {
		Token string
	}{
		Token: token,
	}
	mock.lockVerifyYouTubeImportStateToken.Lock()
	mock.calls.VerifyYouTubeImportStateToken = append(mock.calls.VerifyYouTubeImportStateToken, callInfo)
	mock.lockVerifyYouTubeImportStateToken.Unlock()
	return mock.VerifyYouTubeImportStateTokenFunc(token)
}

// VerifyYouTubeImportStateTokenCalls gets all the calls that were made to VerifyYouTubeImportStateToken.
func (mock *ServiceMock) VerifyYouTubeImportStateTokenCalls() []struct {
	Token string
} {
	var calls []struct {
		Token string
	}
	mock.lockVerifyYouTubeImportStateToken.RLock()
	calls = mock.calls.VerifyYouTubeImportStateToken
	mock.lockVerifyYouTubeImportStateToken.RUnlock()
	return calls
}

// VerifyOIDCStateToken calls VerifyOIDCStateTokenFunc.
func (mock *ServiceMock) VerifyOIDCStateToken(token string) (string, error) {
	if mock.VerifyOIDCStateTokenFunc == nil {
		panic("ServiceMock.VerifyOIDCStateTokenFunc: method is nil but Service.VerifyOIDCStateToken was just called")
	}
	callInfo := struct {
		Token string
	}{
		Token: token,
	}
	mock.lockVerifyOIDCStateToken.Lock()
	mock.calls.VerifyOIDCStateToken = append(mock.calls.VerifyOIDCStateToken, callInfo)
	mock.lockVerifyOIDCStateToken.Unlock()
	return mock.VerifyOIDCStateTokenFunc(token)
}

// VerifyOIDCStateTokenCalls gets all the calls that were made to VerifyOIDCStateToken.
func (mock *ServiceMock) VerifyOIDCStateTokenCalls() []struct {
	Token string
} {
	var calls []struct {
		Token string
	}
	mock.lockVerifyOIDCStateToken.RLock()
	calls = mock.calls.VerifyOIDCStateToken
	mock.lockVerifyOIDCStateToken.RUnlock()
	return calls
}

// VerifyUserAccessToken calls VerifyUserAccessTokenFunc.
func (mock *ServiceMock) VerifyUserAccessToken(token string) (uuid.UUID, uuid.UUID, time.Time, error) {
	if mock.VerifyUserAccessTokenFunc == nil {
		panic("ServiceMock.VerifyUserAccessTokenFunc: method is nil but Service.VerifyUserAccessToken was just called")
	}
	callInfo := struct {
		Token string
	}{
		Token: token,
	}
	mock.lockVerifyUserAccessToken.Lock()
	mock.calls.VerifyUserAccessToken = append(mock.calls.VerifyUserAccessToken, callInfo)
	mock.lockVerifyUserAccessToken.Unlock()
	return mock.VerifyUserAccessTokenFunc(token)
}

// VerifyUserAccessTokenCalls gets all the calls that were made to VerifyUserAccessToken.
// Check the length with:
//
//	len(mockedService.VerifyUserAccessTokenCalls())
func (mock *ServiceMock) VerifyUserAccessTokenCalls() []struct {
	Token string
} {
	var calls []struct {
		Token string
	}
	mock.lockVerifyUserAccessToken.RLock()
	calls = mock.calls.VerifyUserAccessToken
	mock.lockVerifyUserAccessToken.RUnlock()
	return calls
}
