// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package middleware_d_test

import (
	"context"
	"github.com/brqnko/anti-yt/backend/internal/core/discord_d"
	"sync"
)

// Ensure, that DiscordServiceMock does implement discord_d.Service.
// If this is not the case, regenerate this file with moq.
var _ discord_d.Service = &DiscordServiceMock{}

// DiscordServiceMock is a mock implementation of discord_d.Service.
//
//	func TestSomethingThatUsesService(t *testing.T) {
//
//		// make and configure a mocked discord_d.Service
//		mockedService := &DiscordServiceMock{
//			SendWebhookMessageFunc: func(ctx context.Context, message string) error {
//				panic("mock out the SendWebhookMessage method")
//			},
//		}
//
//		// use mockedService in code that requires discord_d.Service
//		// and then make assertions.
//
//	}
type DiscordServiceMock struct {
	// SendWebhookMessageFunc mocks the SendWebhookMessage method.
	SendWebhookMessageFunc func(ctx context.Context, message string) error

	// calls tracks calls to the methods.
	calls struct {
		// SendWebhookMessage holds details about calls to the SendWebhookMessage method.
		SendWebhookMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Message is the message argument value.
			Message string
		}
	}
	lockSendWebhookMessage sync.RWMutex
}

// SendWebhookMessage calls SendWebhookMessageFunc.
func (mock *DiscordServiceMock) SendWebhookMessage(ctx context.Context, message string) error {
	if mock.SendWebhookMessageFunc == nil {
		panic("DiscordServiceMock.SendWebhookMessageFunc: method is nil but Service.SendWebhookMessage was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Message string
	}{
		Ctx:     ctx,
		Message: message,
	}
	mock.lockSendWebhookMessage.Lock()
	mock.calls.SendWebhookMessage = append(mock.calls.SendWebhookMessage, callInfo)
	mock.lockSendWebhookMessage.Unlock()
	return mock.SendWebhookMessageFunc(ctx, message)
}

// SendWebhookMessageCalls gets all the calls that were made to SendWebhookMessage.
// Check the length with:
//
//	len(mockedService.SendWebhookMessageCalls())
func (mock *DiscordServiceMock) SendWebhookMessageCalls() []struct {
	Ctx     context.Context
	Message string
} {
	var calls []struct {
		Ctx     context.Context
		Message string
	}
	mock.lockSendWebhookMessage.RLock()
	calls = mock.calls.SendWebhookMessage
	mock.lockSendWebhookMessage.RUnlock()
	return calls
}
