// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package middleware_d_test

import (
	"context"
	"github.com/brqnko/anti-yt/backend/internal/core/database_d"
	"github.com/google/uuid"
	"sync"
	"time"
)

// Ensure, that JtiBlacklistRepositoryMock does implement database_d.JtiBlacklistRepository.
// If this is not the case, regenerate this file with moq.
var _ database_d.JtiBlacklistRepository = &JtiBlacklistRepositoryMock{}

// JtiBlacklistRepositoryMock is a mock implementation of database_d.JtiBlacklistRepository.
//
//	func TestSomethingThatUsesJtiBlacklistRepository(t *testing.T) {
//
//		// make and configure a mocked database_d.JtiBlacklistRepository
//		mockedJtiBlacklistRepository := &JtiBlacklistRepositoryMock{
//			InsertJTIFunc: func(ctx context.Context, jti uuid.UUID, expiresAt time.Time) error {
//				panic("mock out the InsertJTI method")
//			},
//			IsJtiExistFunc: func(ctx context.Context, jti uuid.UUID) (bool, error) {
//				panic("mock out the IsJtiExist method")
//			},
//		}
//
//		// use mockedJtiBlacklistRepository in code that requires database_d.JtiBlacklistRepository
//		// and then make assertions.
//
//	}
type JtiBlacklistRepositoryMock struct {
	// InsertJTIFunc mocks the InsertJTI method.
	InsertJTIFunc func(ctx context.Context, jti uuid.UUID, expiresAt time.Time) error

	// IsJtiExistFunc mocks the IsJtiExist method.
	IsJtiExistFunc func(ctx context.Context, jti uuid.UUID) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// InsertJTI holds details about calls to the InsertJTI method.
		InsertJTI []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Jti is the jti argument value.
			Jti uuid.UUID
			// ExpiresAt is the expiresAt argument value.
			ExpiresAt time.Time
		}
		// IsJtiExist holds details about calls to the IsJtiExist method.
		IsJtiExist []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Jti is the jti argument value.
			Jti uuid.UUID
		}
	}
	lockInsertJTI  sync.RWMutex
	lockIsJtiExist sync.RWMutex
}

// InsertJTI calls InsertJTIFunc.
func (mock *JtiBlacklistRepositoryMock) InsertJTI(ctx context.Context, jti uuid.UUID, expiresAt time.Time) error {
	if mock.InsertJTIFunc == nil {
		panic("JtiBlacklistRepositoryMock.InsertJTIFunc: method is nil but JtiBlacklistRepository.InsertJTI was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Jti       uuid.UUID
		ExpiresAt time.Time
	}{
		Ctx:       ctx,
		Jti:       jti,
		ExpiresAt: expiresAt,
	}
	mock.lockInsertJTI.Lock()
	mock.calls.InsertJTI = append(mock.calls.InsertJTI, callInfo)
	mock.lockInsertJTI.Unlock()
	return mock.InsertJTIFunc(ctx, jti, expiresAt)
}

// InsertJTICalls gets all the calls that were made to InsertJTI.
// Check the length with:
//
//	len(mockedJtiBlacklistRepository.InsertJTICalls())
func (mock *JtiBlacklistRepositoryMock) InsertJTICalls() []struct {
	Ctx       context.Context
	Jti       uuid.UUID
	ExpiresAt time.Time
} {
	var calls []struct {
		Ctx       context.Context
		Jti       uuid.UUID
		ExpiresAt time.Time
	}
	mock.lockInsertJTI.RLock()
	calls = mock.calls.InsertJTI
	mock.lockInsertJTI.RUnlock()
	return calls
}

// IsJtiExist calls IsJtiExistFunc.
func (mock *JtiBlacklistRepositoryMock) IsJtiExist(ctx context.Context, jti uuid.UUID) (bool, error) {
	if mock.IsJtiExistFunc == nil {
		panic("JtiBlacklistRepositoryMock.IsJtiExistFunc: method is nil but JtiBlacklistRepository.IsJtiExist was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Jti uuid.UUID
	}{
		Ctx: ctx,
		Jti: jti,
	}
	mock.lockIsJtiExist.Lock()
	mock.calls.IsJtiExist = append(mock.calls.IsJtiExist, callInfo)
	mock.lockIsJtiExist.Unlock()
	return mock.IsJtiExistFunc(ctx, jti)
}

// IsJtiExistCalls gets all the calls that were made to IsJtiExist.
// Check the length with:
//
//	len(mockedJtiBlacklistRepository.IsJtiExistCalls())
func (mock *JtiBlacklistRepositoryMock) IsJtiExistCalls() []struct {
	Ctx context.Context
	Jti uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		Jti uuid.UUID
	}
	mock.lockIsJtiExist.RLock()
	calls = mock.calls.IsJtiExist
	mock.lockIsJtiExist.RUnlock()
	return calls
}
