openapi: 3.1.0

info:
  title: anti-yt api
  description: anti-yt api
  version: 1.0.0

servers:
  - url: 'https'

paths:
  /health:
    description: "Health check"
    get:
      summary: "Health check"

